TheAlgorithms/Python

sorts/quick_sort.py

This is safety measure against the worst case scenario - sorted input and O(n^2) complexity

[Quicksort]Added shuffling of input

---

README.md

Selection Sort Description, links, GIF

Update README.md : Selection Sort

---

sorts/heap_sort.py

This is a python implementation of heap sort algorithm.

added implementation for heap sort algorithm

---

other/nested_brackets.py

I added a common algorithm problem that uses a stack to determine if brackets are balanced

added nested brackets problem

---

dynamic_programming/longest common subsequence.py

LCS Problem Statement: Given two sequences, find the length of longest subsequence present in both of them.
A subsequence is a sequence that appears in the same relative order, but not necessarily continious.
Example:"abc", "abg" are subsequences of "abcdefgh".

Create longest common subsequence.py

---

dynamic_programming/longest_sub_array.py

The title "Dynamic Programming Solution to edit distance problem" is of different problem(typo error)

Corrected title in longest_sub_array

---

machine_learning/gradient_descent.py

Gradient Descent is widely used in Machine Learning for optimizing cost of hypothesis functions.

Added Gradient Descent Algorithm

---

README.md

Corrected Markdown

---

machine_learning/scoring_functions.py

very first version of scoring functions added. will continuously add metrics and explanations

scoring functions added

---

dynamic_programming/fastfibonacci.py

Added a dynamic program calculating the nth Fibonacci number in O(log(n)) making use of matrix multiplication.

Added fastfibonacci.py

---

sorts/counting_sort.py

I check that already exist a pull request to add counting sort (#133) but, unfortunately hasn't linear time complexity or is a stable version of counting sort, two important features of counting sort. I made my own, trying to fix this issues.

Add counting sort

---

searches/binary_search.py
searches/interpolation_search.py

Fixed spelling of coma inside input function to comma

Fixed spelling of coma to comma

---

sorts/radix_sort.py

#130 fixed radix sort for python 3

#130 fixed radix sort for python 3

---

other/euclidean_gcd.py

The purpose of this PR is to add The Euclidean GCD algorithm.

Adding Euclidean GCD algorithm

---

Graphs/A*.py

As no one was working on this for a long time. Hence I added an implementation of A*

Added A* Algorithm

---

data_structures/Stacks/next.py

Element       NGE
4      -->   5
5      -->   25
2      -->   25
25     -->   -1

Added Next Greater Element

---

searches/ternary_search.py

A python implementation of the ternary search algorithm.

Added Ternary Search Algorithm

---

dynamic_programming/longest_increasing_subsequence_O(nlogn).py

Wrote a neat, complete and easy to understand code for Longest Strictly Increasing Subsequence in dynamic programming section in O(nlogn) time complexity.

Added Code in Dynamic Programming section for Longest Strictly Increasing Subsequence in O(nlogn) time

---

dynamic_programming/FloydWarshall.py

upload simple Floyd-Warshall Algorithm (No path stored)

Floyd Warshall Algorithm

---

data_structures/Binary Tree/FenwickTree.py
data_structures/Binary Tree/SegmentTree.py

Add simple Segment Tree (No optimization)

Add Segment tree

---

data_structures/Binary Tree/FenwickTree.py
data_structures/Binary Tree/LazySegmentTree.py
data_structures/Binary Tree/SegmentTree.py

Lazy Segment Tree 
with lazy approach, the segment tree will be able to update in O(lg N) instead of O(Nlg N)

Lazy Segment Tree

---

data_structures/LinkedList/singly_LinkedList.py

Updating singly-linked list to include a reverse method using the three-way shuffle method.

Adding reverse() to singly-linked list

---

machine_learning/scoring_functions.py

I add MBD because i think it's also important for developer to understand the bias of the created model

add mean bias deviation in scoring functions

---

machine_learning/scoring_functions.py

Lines like 19, 20, 29, 30, etc. use np but it is never defined.

import numpy as np

---

Project Euler/Problem 07/sol2.py

I've Made An Easier Solution To Problem 7
Upon Executing The File, You Will Be Asked `Enter The N'th Prime Number You Want To Get` And After You Specify It You Will Get The N'th Prime Number

Project Euler - Easier Solution To Problem 7

---

Project Euler/Problem 04/sol1.py

Little embellishment of the code.
I put some comments and put readable identifiers. 
I documented the code.

Refactoring solv1.py

---

dynamic_programming/abbreviation.py

https://www.hackerrank.com/challenges/abbr/problem

add abbrevation solution to dp

---

other/password_generator.py

Without these changes, Python syntax errors are raised.
flake8 should be run by this repo's .travis.yml file but it is currently turned off.

Pass flake8 tests

---

dynamic_programming/matrix_chain_order.py

Implementation of Matrix Chain Order

MatrixChainOrder

---

sorts/pancake_sort.py
sorts/tree_sort.py

Add pancake sort and tree sort algorithm.

Add sorts for python3

---

linear-algebra-python/README.md
linear-algebra-python/src/lib.py

I added two new functions for creating random vectors and a random matrices.

added two new functions 

---

data_structures/LinkedList/singly_LinkedList.py

__int__ should be __init__ i think?

function '__init__' miss a 'i'

---

networking_flow/Ford-Fulkerson.py
networking_flow/Ford_Fulkerson.py
networking_flow/Minimum_cut.py

Add networking flow on Ford-Fulkerson Algorithm.

Networking flow add

---

Maths/SimpsonRule.py
Maths/TrapezoidalRule.py

@ltdouthit __print()__ is a function in Python 3

from __future__ import print_function For Python 3

---

Project Euler/Problem 01/sol3.py

* Put the import at the begin of the file. Otherwise I get   
>  from __future__ import print_function
^
SyntaxError: from __future__ imports must occur at the beginning of the file

I fixed the sol3.py of problem 1

---

hashes/chaos_machine.py

* I added a option for termination the program instead of a endless loop.  
* Now with ```e``` or ```E``` the program terminates. 
* I fixed the assert-statments

added a option for termination the program

---

searches/tabuTestData.txt
searches/tabu_search.py
searches/test_tabu_search.py

I added Tabu Search for a Travelling Salesman Problem in the searches file. Analytical comments are available for each method. I also added tests for the methods of the Algorithm. Please let me know if you would like to accept my commit.
Thank you in advance.

Tabu Search

---

sorts/bogosort.py

Found a misspelling, stript should be strip

typo: strip

---

dynamic_programming/knapsack.py

Added a test case to knapsack.py

Added test case to knapsack.py

---

README.md

Fixed the average and worst case scenarios of merge sort.

merge sort average&worst case scenarios changed Issue #340

---

hashes/sha1.py

Added new code for SHA1 algorithm written in Python. Also contains a test to compare results with the result of hashlib.sha1

Added SHA1 algorithm in hashes folder

---

Maths/fibonacciSeries.py

A simple Fibonacci Series implementation in python

Add Fibonacci Series Using Recursion

---

ArithmeticAnalysis/NewtonRaphsonMethod.py

Just small corrections to grammar and spelling, no code change.

Grammar corrections

---

README.md

* ROT13
* RSA
* XOR
* Interpolation search
* Jump search
* QuickSelect Search
* Tabu Search
in README.md

Added Descriptions in README.md for cipher and search algorithms.

---

Neural_Network/FCN.ipynb

Fully connected Neural Net using keras on Mnist

fully connected neural net

---

Project Euler/Problem 31/sol1.py

This adds the solution to the problem 31 in Project Euler.

Add Problem 31 solution

---

machine_learning/logistic_regression.py

implementation of logistic regression for binary classification

Logistic regression implementation

---

data_structures/Binary Tree/binary_seach_tree.py

added sasslabel

---

README.md

Removed the Wikipedia reference links, wrote code for the Exclusive Disjunction Operator and added link for Heap Sort Wikipedia page

Improved README and added Exclusive Disjunction Operator

---

dynamic_programming/matrix_chain_order.py

Remove unnecessary loop in matrix_chain_order.py

---

matrix/matrix_multiplication_addition.py

Addition and multiplication algorithm of two square matrix

Addition and multiplication algorithm of two square matrix

---

binary_tree/basic_binary_tree.py
graphs/basic_graphs.py
matrix/matrix_multiplication_addition.py

Binary tree basic algorithms to check whether given binary tree is full binary tree or not and algorithm to find the height of binary tree.

Graph algorithms

---

Maths/find_hcf.py
Maths/find_lcm.py
binary_tree/basic_binary_tree.py
graphs/basic_graphs.py
matrix/matrix_multiplication_addition.py
other/palindrome.py

added recursive and non recursive hcf, lcm and palindrome program.

HCF, LCM and Palidrome algorithm

---

project_euler/problem_10/sol2.py

solution using functional programming. The solution could be more DRY if imports from `Python/Maths `were possible :) ``

Create project Euler problem 10 sol2.py

---

graphs/Directed and Undirected (Weighted) Graph

Added functions to get all nodes for some algorithms and time calculation for dfs and bfs.

All Python Version 3

---

analysis/compression_analysis/psnr.py

fixed wrong image's path while debuggin in VSCode

make images' path specific

---

ciphers/affine_cipher.py
ciphers/rsa_cipher.py
data_structures/binary tree/AVLtree.py
data_structures/binary tree/binary_search_tree.py

Hello,
This is a little patch to fix several `DeprecationWarning: invalid escape sequence`.

Fix DeprecationWarning: invalid escape sequence

---

dynamic_programming/rod_cutting.py

Added the Rod Cutting algorithm that solves the titular problem from Cormer et al. Also, I included in comments some documentation about the definition and solution of the problem.

Added Rod Cutting to DP Section

---

project_euler/problem_03/sol2.py

use Floor division instead of Floating point division to return answer as integer.

Project Euler problem 3 small fix

---

project_euler/problem_07/sol3.py

Solution using a generator to process inputs that are large. 
We should also probably make this repo a package to allow for better code reuse. Instead of copy pasting `checkPrime()`, it would be nice to directly import it.

Project Euler problem 7  new solution using checkPrime()

---

project_euler/problem_04/sol2.py

1. 3 digit numbers should include 100. 
2. maintaining a list in memory is not required.

Project Euler problem 4 sol 2 small fix

---

project_euler/problem_09/sol3.py

clean solution to project Euler problem 9 with list comp.

Create project Euler problem 9 sol3.py

---

project_euler/problem_08/sol2.py

intuitive solution using functional programming

Create project Euler problem 8 sol2.py

---

data_structures/stacks/stack.py

The method returns the true when the stack is empty

Fix '__bool__' method

---

ciphers/trafid_cipher.py

Hello, I've implemented Trifid cipher, I would appreciate contributing in such an interesting project!

Added Trafid Cipher

---

README.md

I want to enhance the README.md file.

Add animation for heap sort.

---

maths/BinaryExponentiation.py

Calculates base^(power) using only O(logn) multiplications

add-binary-exponentiation

---

sorts/bucket_sort.py

fix spelling on line 44

---

data_structures/binary tree/treap.py

Added basic implementation of treap. In future it is possible to add mass operations and implicit key treap.

Added treap

---

graphs/check_bipartite_graph_dfs.py

It's a really nice code and I'll try to add some features from R studio to improve the outcome.

Implement check_bipartite_graph using DFS.

---

ciphers/Atbash.py

I have added the Atbash Cipher for Python

Atbash Cipher for Python

---

CONTRIBUTING.md

File looks more elegant now ;-)

Fixed typo and capitalized some words

---

data_structures/binary_tree/red_black_tree.py

I wrote a RedBlackTree class and some test cases for it.

Add Red-Black Binary Search Trees

---

graphs/BFS.py

I modified the Docstrings at the beginning of the file to fix D400, W0105, and E402.

Modified Docstrings to Fix Errors

---

dynamic_programming/climbing_stairs.py

@SandersLin Your review please?

Fix error message and format with python/black

---

matrix/nth_fibonacci_using_matrix_exponentiation.py

@AnupKumarPanwar @ParthS007 @poyea Could I please get a quick review on this one because I made a mistake here that __breaks the build for new pull requests__.

Use correct function names in nth_fibonacci_using_matrix_exponentiation.py

---

divide_and_conquer/closest_pair_of_points.py

pytests for closest_pair_of_points.py

---

arithmetic_analysis/newton_raphson_method.py
ciphers/caesar_cipher.py
ciphers/morse_code_implementation.py
ciphers/trafid_cipher.py
ciphers/xor_cipher.py
data_structures/binary_tree/fenwick_tree.py
data_structures/binary_tree/lazy_segment_tree.py
data_structures/binary_tree/segment_tree.py
data_structures/queue/double_ended_queue.py
data_structures/stacks/stock_span_problem.py
machine_learning/logistic_regression.py
maths/Quadratic Equations(Complexes Numbers)
maths/quadratic_equations_complex_numbers.py
other/fischer_yates_shuffle.py

No space between __print__ and __(__.

print() is a function just like every other function

---

hashes/md5.py
hashes/sha1.py

hashes/md5.py has tabs vs spaces inconsistency, it was also resolved.

Added pytests to hashes/md5.py

---

maths/test_prime_check.py

Adds [a few more tests](https://travis-ci.org/TheAlgorithms/Python/builds/570502718#L620) to our automated Pytests.

Add maths/test_prime_check.py

---

maths/matrix_exponentiation.py

I messed up and broke the build.  Can I please get a rapid review?

Fix the build typo: fn --> fn1

---

machine_learning/scoring_functions.py

Added doctests as requested in #1085 , more specifically to scoring_functions.py.
Closed the previous PR because of the nightmare.

added doctests to scoring_functions.py

---

divide_and_conquer/mergesort.py

It should be added in divide and conquer

mergesort added

---

maths/greatest_common_divisor.py

GCD was wrongly written as "Greater Common Divisor", instead of "Greatest Common Divisor".

Rename GCD File

---

linear_algebra/src/lib.py

missing 'c' in eulidianLength and eulidian. Should be euclidianLength and euclidian.

fixed some typos in euclidian and euclidianLength

---

DIRECTORY.md
scripts/build_directory_md.py

minor changes in format of DIRECTORY.md

---

maths/binomial_coefficient.py

Added binomial coefficient

---

maths/collatz_sequence.py

Changed a few spellings and grammar

Some grammatical and spelling corrections

---

project_euler/problem_20/sol4.py

Added solution 4 for problem 20

added solution 4 for problem_20

---

web_programming/get_imdbtop.py

Python code that lists the best 'n' movie in IMDb based on the entered value

Python program that listing top 'n' movie in imdb

---

arithmetic_analysis/secant_method.py

Implementation of Secant Method.

Addition of Secant Method

---

dynamic_programming/longest_increasing_subsequence_o(nlogn).py

* Import typing
* Fix bug on line 9
* Doctest for the algorithm

Doctest, type hints and bug in LIS_O(nlogn)

---

data_structures/binary_tree/non_recursive_segment_tree.py

A non-recursive Segment Tree implementation with range query and single item update.

Non-recursive Segment Tree implementation

---

maths/ceil.py
maths/floor.py

* `math.floor()`  algorithm implement
* `math.ceil()` algorithm implement
@cclauss Please review

add floor()

---

data_structures/linked_list/from_sequence.py
data_structures/linked_list/print_reverse.py
data_structures/linked_list/singly_linked_list.py

- Changed existing file to conform to PEP8
- Added visual representations of LinkedLists
- Added two programs

Improved on Singly Linked List Programs

---

ciphers/rsa_factorization.py

I revised my implementation and found out that I have miss a inner loop for t.  x and y should be recalculated everytime when t is divisble by 2. I have also included a more readble source for this algorithm.

fix implementation errors.

---

data_structures/queue/circular_queue.py

Circular FIFO Queue implementation using Python list with fixed range.
Time complexity 
1. Enqueue(put) - O(1)
2. Dequeue(get) - O(1)
data_structures/queue/circular_queue.py

Adding circular_queue.py

---

web_programming/current_stock_price.py

Added "current stock price", web scrapper to fetch current stock prices using python and beautiful soup

added current stock price

---

maths/pythagoras.py

Distance between two points in space.

Pythagoras

---

optimization/hill_climbing.py
optimization/requirements.txt
searches/hill_climbing.py

I have added a hill climbing algorithm with an interface. The interface allows the algorithm to be ported into different problems. Let me know what can be improved in this.

added hill climbing algorithm

---

data_structures/linked_list/deque_doubly.py
searches/hill_climbing.py
sorts/recursive_bubble_sort.py

Changes to data_structures/linked_list/deque_doubly.py and sorts/recursive_bubble_sort.py are psd/black changes.

Typos in comments in hill_climbing.py

---

.github/workflows/directory_writer.yml
DIRECTORY.md

@Catastrophe666 Thanks for pointing out that this was missing!

git add DIRECTORY.md

---

divide_and_conquer/strassen_matrix_multiplication.py

Adds a whitespace character so that master branch is not failing

Corrects failing check in master

---

maths/armstrong_numbers.py

Adding Armstrong number

---

searches/binary_search.py

Fixes: #1703 Proposal for partially implementing the interface from the bisect module in binary_search.py. No type annotations for consistency with the original file.

Augment binary search algorithms

---

ciphers/transposition_cipher.py

relevant documentation added

---

strings/manacher.py

Fixes #1720
Manacher's algorithm in string section is enhanced.
I have done following
I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
[ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #1720 .

Implement Manacher's algorithm

---

maths/chudnovsky_algorithm.py

Add Chudnovskys algorithm for calculating many digits of pi

---

maths/quadratic_equations_complex_numbers.py

Use Python's complex number module cmath for the calculation of the
roots
This also now fully computes the roots. Previous implementation did not handle the final division with complex roots:
ex: `QuadraticEquation(1,-6,25) -> ('(-6+8.0 * i) / 2', '(-6+8.0 * i) / 2')`
but it should be `quadratic_roots(1,-6,25) -> ((3+4j), (3-4j))`

Update quadratic equations solver

---

.github/workflows/autoblack.yml
linear_algebra/src/rayleigh_quotient.py
maths/modular_exponential.py
maths/monte_carlo_dice.py

https://github.com/actions/checkout/releases

uses: actions/checkout@v2

---

machine_learning/random_forest_classifier.py
machine_learning/random_forest_regressor.py

Added Random Forest Classifier with Iris Dataset. A confusion matrix is added for result visualization.

Added Random Forest Classifier

---

.github/workflows/directory_writer.yml
DIRECTORY.md

Try to chek if `github.ref == 'refs/heads/master'` on push. Do write the directory if it's true.

Effective directory writer

---

.github/workflows/directory_writer.yml
DIRECTORY.md

directory_writer: actions/checkout@v1 # Use v1, NOT v2

---

strings/rabin_karp.py

fix: typo
* [X ] Fix a bug or typo in an existing algorithm?
* [X ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ X] This pull request is all my own work -- I have not plagiarized.
* [ X] I know that pull requests will not be merged if they fail the automated tests.
* [ X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X ] All new Python files are placed inside an existing directory.

Typo in comment rabin_karp.py

---

DIRECTORY.md
data_structures/binary_tree/binary_search_tree_recursive.py

Binary search tree using recursion

Binary search tree using recursion

---

CONTRIBUTING.md

CONTRIBUTING.md: Fix comments about the black formatter

---

CONTRIBUTING.md

fixed error in type hint syntax.

fixed error in type hint syntax CONTRIBUTING.md

---

cellular_automata/README.md

Related to https://github.com/TheAlgorithms/Python/issues/1613#issuecomment-618175224 @8Dion8 Your review please.  Once this land, this directory would be a great place for you to add your work.

Add cellular_automata directory

---

project_euler/problem_31/sol1.py

Fix typo in Project Euler sol1.py

---

.github/stale.yml
.github/workflows/stale.yml

Update close comment

---

data_structures/heap/max_heap.py

Binary max heap implementation

Add type hints to max_heap.py

---

blockchain/chinese_remainder_theorem.py

import doctest is not relevant with algorithms. move it under main section.

change doctest line

---

ciphers/hill_cipher.py
other/euclidean_gcd.py

Added recursive method for Euclidean algorithm.
Added doctests and type hints for existing implementation.

Euclidean recursive method + doctests + type hints

---

sorts/shell_sort.py

Improved shell sort syntax
I think it has improved in terms of memory.

Enhance shell sort syntax

---

.github/workflows/codespell.yml
.travis.yml
DIRECTORY.md

Added TravisBuddy (https://github.com/bluzi/travis-buddy) and github action (https://github.com/plettich/python_codespell_action) to get information about errors under comments.
Hope it helps with #1910  :smiley: 
Tested on my forked repo: https://github.com/mateuszz0000/Python/pull/3

Errors notifications under pull requests

---

web_programming/fetch_github_info.py

Fix a little bug about "__main__"

fix fetch_github_info __main__ bug

---

conversions/decimal_to_any.py
hashes/sdbm.py

PR implements easy to go hash algorithm sdbm

implement sdbm hash algorithm

---

backtracking/rat_in_maze.py

Fix line break after binary operator

Fix line break after binary operator

---

backtracking/knight_tour.py
dynamic_programming/max_non_adjacent_sum.py
project_euler/problem_551/sol1.py

Euler problem 551 sol 1: Reduce McCabe code complexity

---

DIRECTORY.md
matrix/matrix_operation.py

black matrix_operation.py

---

conversions/prefix_conversions.py

initial commit of prefix-conversions

---

linear_algebra/src/test_linear_algebra.py
maths/number_of_digits.py
maths/perfect_number.py
web_programming/daily_horoscope.py

Re-blacken

---

searches/binary_search.py

Fix method name in recursive binary search doctests.

Fix doctests

---

optimization/requirements.txt

Removed optimization empty directory

---

data_structures/binary_tree/basic_binary_tree.py
maths/number_of_digits.py

fix number_of_digits bug

---

strings/check_anagrams.py

Created check_anagrams.py in strings

---

data_structures/binary_tree/lazy_segment_tree.py

fixed variable naming and removed unnecessary type hints in lazy_segment_tree.py as suggested in pr#2303

lazy_segment_tree.py-style-fixes

---

maths/ugly_numbers.py

Created ugly_numbers.py in Python/maths

---

maths/fibonacci_sequence_recursion.py

Added type hints for maths/fibonacci_sequence_recursion.

---

data_structures/binary_tree/red_black_tree.py

Adding type hints to RedBlackTree

---

sorts/radix_sort.py

Update radix_sort: fix bugs and add related tests

---

conversions/octal_to_decimal

octal_to_decimal converter

---

conversions/binary_to_decimal

binary_to_decimal converter

---

searches/double_linear_search_recursion.py
searches/simple_binary_search.py

Added double linear search recursion

---

scripts/validate_filenames.py

Fix copy / paste oversight

---

conversions/binary_to_octal.py

Update and rename bin_to_octal.py to binary_to_octal.py

---

project_euler/problem_48/sol1.py

Corrected the problem statement of problem_48 of project_euler.

---

backtracking/minimax.py

added type hints and doctests for minimax algorithm

---

strings/check_anagrams.py

Fixed bugs

---

.github/workflows/codespell.yml
DIRECTORY.md

@mateuszz0000 Your review, please.  Pretend that you do not know what `-L` stands for.  How many keystrokes and clicks does it take to confirm the purpose of this option?

Use self-documenting option instead of cryptic option

---

README.md

Follow-up on #2511
As mentioned in https://github.com/TheAlgorithms/Python/pull/2511#issuecomment-701163537

Add badges for code style and pre-commit in README.md

---

sorts/bucket_sort.py

Fixed bucket sort

---

.github/workflows/auto_close_empty_issues.yml

Fix pre-commit errors in auto_close_empty_issues.yml from #2756

Fix pre-commit error in GitHub action file

---

project_euler/problem_30/sol1.py

Fixes issues with Project Euler problem 30 solution as described in #2786

bring problem_30 solution in line with project style guidelines

---

project_euler/problem_99/sol1.py

Hacktoberfest 2020: Rename method for project_euler/problem_99

---

project_euler/problem_37/sol1.py

Hacktoberfest 2020: Add solution method for project_euler/problem_37

---

project_euler/problem_27/problem_27_sol1.py
project_euler/problem_27/sol1.py

Add problem url and default values to solution() function
Related to #2786

Hacktoberfest 2020 - coding style with default argument for project_euler problem 27

---

project_euler/problem_71/sol1.py

Added solution for [problem 71](https://projecteuler.net/problem=71)

Hacktoberfest: Added Project Euler Problem 71: Fixes #2695

---

project_euler/problem_56/sol1.py

[Project Euler] Fix code style for problem 56

---

DIRECTORY.md
backtracking/sudoku.py

Added sudoku type hints [Hacktober Fest]

---

.github/CODEOWNERS
DIRECTORY.md

CODEOWNERS: Proper spelling of my userid

---

computer_vision/README.md

Fixed English grammar for Computer Vision

---

project_euler/problem_11/sol2.py

Docstring must have been leftover from some FizzBuzz method. 
Now it describes the actual code.

Fix docstring for Euler problem 11, solution 2

---

project_euler/problem_11/sol1.py

Docstring must have been leftover from some FizzBuzz method.
Now it describes the actual code.

Fix docstring for Euler problem 11, solution 1

---

project_euler/problem_72/sol1.py

Added a solution to the Project Euler 72 - Counting fractions

Hacktoberfest - Added a solution to Project Euler 72

---

ciphers/affine_cipher.py

Fixed **cipher/affine_cipher.py** from randomly throwing `SystemExit: The affine cipher becomes weak when key B is set to 0. Choose different key` exception.

fixed error in cipher/affine_cipher.py

---

.pre-commit-config.yaml
DIRECTORY.md

Some doctests use print(x, sep=" ") and black will not fix inside triple quotes.
It is too confusing for new contributors to understand this and how to fix.

.pre-commit-config.yaml: Disable trailing-whitespace fixer

---

project_euler/problem_173/sol1.py

We shall define a square lamina to be a square outline with a square "hole" so that the shape possesses vertical and horizontal symmetry. For example, using exactly thirty-two square tiles we can form two different square laminae:
With one-hundred tiles, and not necessarily using all of the tiles at one time, it is possible to form forty-one different square laminae.
Using up to one million tiles how many different square laminae can be formed?
Reference: [https://projecteuler.net/problem=173](url)

Added solution for Project Euler problem 173. 

---

graphs/minimum_spanning_tree_prims.py
graphs/tests/test_min_spanning_tree_prim.py

And also to increase the coverage as stated in #2128

test/graphs/prim: writing a test case to verify the correctness of the algorithm

---

quantum/half_adder.py

Qiskit: Add Quantum Half Adder

---

scripts/validate_filenames.py

Removed new line to match rest of python file formatting.

removed extra line to match rest of file

---

maths/lucas_series.py

Added another method to calculate lucas_numbers

Update lucas_series.py to include another method

---

other/two_pointer.py

Added solution for the **Two Sum** problem using the two pointer technique. 
P.S: Trying to get into Open Source and what better way than **Hacktoberfest**  #2510

Added two pointer solution for two sum problem

---

strings/reverse_letters.py

Reverses letters of individual words means not adjusting the position of words.

Added reverse_letters.py

---

quantum/README.md

Added References and tutorial links for Python based Quantum computing using IBM Qiskit

Added IBM Qiskit References

---

.github/workflows/directory_writer.yml
.github/workflows/stale.yml

This was just used for a test, things seemed to work fine.

No issues so far

---

searches/quick_select.py

Shortened code

---

divide_and_conquer/peak.py

Peak of unimodal list DNC algorithm

---

.github/workflows/build.yml
README.md

Update related to the change in CI testing

---

.github/workflows/stale.yml

Maybe this might fix the action not closing any issues/PR problem.

Run latest stale action

---

.github/stale.yml
.github/workflows/stale.yml

I think before the action came we were using the stale bot already so the app is already installed in this repository. I have added the config file for it and we will monitor the bot for a number of days and determine whether to switch or not.
https://github.com/TheAlgorithms/Python/pull/1594 I can confirm the app has been installed in this repository. Go to the configure option on the app page: https://github.com/apps/stale and you will see TheAlgorithms repository there and when you go to the configure option for the repository you will see all the repositories this app has been installed in this organization.
@cclauss

Try the stale bot instead of stale action

---

backtracking/all_subsequences.py
backtracking/coloring.py
backtracking/hamiltonian_cycle.py
backtracking/knight_tour.py
backtracking/minimax.py
backtracking/n_queens_math.py
backtracking/sudoku.py

```console
$ mypy --strict backtracking/
Success: no issues found in 13 source files
```

[mypy] Add/fix type annotations for backtracking algorithms

---

LICENSE.md

There is a small infomation on License.I change it to *2016-2021*.
So I think it's true format.Maybe I am not a good coder.Anyway I wanna help you.
Thanks for your merging!!!

Update License Year

---

cellular_automata/conways_game_of_life.py
cellular_automata/one_dimensional.py

[mypy] Add/fix type annotations for cellular automata

---

matrix/rotate_matrix.py
matrix/tests/test_matrix_operation.py

[mypy] Added/fixed type annotations for "rotate_matrix.py" & "test_matrix_operation.py"

---

electronics/electric_power.py
electronics/ohms_law.py
scheduling/first_come_first_served.py
scheduling/round_robin.py
scheduling/shortest_job_first.py

```
$  mypy electronics/
Success: no issues found in 2 source files
```

[mypy] Add/fix type annotations for electronics algorithms

---

web_programming/covid_stats_via_xpath.py

[mypy] Added/fixed type annotations for "covid_stats_via_xpath.py"

---

.github/workflows/pre-commit.yml
DIRECTORY.md

Give fast feedback to contributors https://github.com/psf/black#github-actions

GitHub Actions: fast-fail on black formatting issues

---

.pre-commit-config.yaml
DIRECTORY.md
machine_learning/k_nearest_neighbours.py
maths/polynomial_evaluation.py
searches/hill_climbing.py

Update our pre-commit dependencies

---

bit_manipulation/binary_shifts.py

Remove unnecessary if else condition

Minor improvement in binary_shifts.py

---

maths/bailey_borwein_plouffe.py

Unnecessary line removed
Remove default value of exponential_term as exponential_term doesn't need a default value

Minor change to bailey_borwein_plouffe.py

---

strings/lower.py

Fixed typo in strings/lower.py: "lowecase" -> "lowercase"

Fixed typo in docstring

---

other/password_generator.py

Simplify password_generator()

---

README.md

- Add Discord badge in `README.md`.

feat: Add Discord badge in `README.md`

---

requirements.txt

Removed keras dependency from requirements.txt

---

requirements.txt

Removes the condition for python version for `tensorflow` in `requirements.txt`

Removes python_version condition on tensorflow

---

.github/workflows/approve_workflow_run.yml

Ref: #4369
I don't know how to test this but this seems correct. Would you mind taking a look at it? @cclauss 
Some references I took:
- https://docs.github.com/en/rest/reference/actions#approve-a-workflow-run-for-a-fork-pull-request
- https://docs.github.com/en/actions/reference/authentication-in-a-workflow#example-2-calling-the-rest-api
- Webhook payload which will be delivered: https://github.com/octokit/webhooks/blob/master/payload-examples/api.github.com/workflow_run/requested.with-conclusion.payload.json (accessed using `github.event`)

feat: action to approve workflow run

---

.github/workflows/approve_workflow_run.yml

fix(action): testing and fixing errors

---

sorts/msd_radix_sort.py

I implemented the MSD radix sort algorithm, that was already implemented again, this
time in-place.

Implemented MSD radix sort algorithm in-place

---

CONTRIBUTING.md

CONTRIBUTING.md: Write for current Python

CONTRIBUTING.md: Write for current Python

---

maths/average_median.py

* Added type hints to maths/average_median.py
* Wikipedia link added

Average median type hint

---

maths/basic_maths.py

* Function prime_factors, number_of_divisors, sum_of_divisors has to have input check, because 0 input causes infinite loop
* Doctest initialization on script start

basic_maths input check

---

graphs/scc_kosaraju.py

Fixes: #{4052} [mypy] fix mypy error: graph 

---

hashes/sha1.py

fixed an indentation mistake
* [x ] Fix a bug or typo in an existing algorithm?

fixed   #4529

---

graphs/a_star.py

Modified the a_star [dot] py for making readable

---

graphs/even_tree.py

Fix mypy errors at even_tree algo

Fix mypy errors at even_tree algo

---

graphs/frequent_pattern_graph_miner.py
graphs/markov_chain.py

[mypy] Fix type annotations for graphs

---

maths/armstrong_numbers.py
maths/average_median.py
maths/series/harmonic_series.py

[mypy] Fix type annotations for maths

---

dynamic_programming/fractional_knapsack_2.py
dynamic_programming/knapsack.py
dynamic_programming/longest_increasing_subsequence.py

[mypy] Fix type annotations for  dynamic programming

---

compression/huffman.py
maths/double_factorial_iterative.py

The double factorial iterative algorithm was added.

Double factorial iterative

---

.github/workflows/build.yml
DIRECTORY.md

@dhruvmanila Is this useful/needed given that we do not pin our dependencies?
https://mypy-lang.blogspot.com/2021/06/mypy-0910-released.html

mypy --install-types --non-interactive .

---

data_structures/disjoint_set/disjoint_set.py

I added a check condition `x==y` and if this condition becomes 
true then `return`.

Fixed #4764

---

backtracking/n_queens_math.py

I corrected the grammar in the comments of backtracking/n_queens_math.py

Correct grammar in backtracking/n_queens_math.py

---

sorts/patience_sort.py

fix: comment

---

project_euler/problem_112/sol1.py

Improve Project Euler problem 112 solution 1 - the top 10 slowest solution on Travis CI logs (under `slowest 10 durations`: `4.70s call     scripts/validate_solutions.py::test_project_euler[problem_112/sol1.py]`):
* Improve solution (locally ~2 times - from ~3.5 seconds to ~1.7 seconds)

Improve Project Euler problem 112 solution 1

---

project_euler/problem_078/sol1.py

Improve Project Euler problem 078 solution 1:
* Add `solution` `doctest`s (`solution(1) = 1` and `solution(9) = 14` which failed in current implementation)
* Improve `solution` function (it passes added tests)

Improve Project Euler problem 078 solution 1

---

project_euler/problem_072/sol1.py

Improve Project Euler problem 072 solution 1 - the top 8 slowest solution on Travis CI logs (under `slowest 10 durations`: `3.92s call     scripts/validate_solutions.py::test_project_euler[problem_072/sol1.py]`):
* Improve solution (locally 3+ times - from 3+ seconds to ~1 seconds)

Improve Project Euler problem 072 solution 1

---

project_euler/problem_493/sol1.py

Added solution for euler problem 493

---

strings/check_anagrams.py

Fix build issues due to count

---

DIRECTORY.md
web_programming/search_books_by_isbn.py

Fix comment

---

project_euler/problem_045/sol1.py
web_programming/get_user_tweets.py

Fixed typo for codespell

---

DIRECTORY.md

Yesterday hexagonal_numbers.py was created. Added that file in this list(maths/series/hexagonal_numbers.py)

Add Hexagonal Numbers in this list

---

DIRECTORY.md
project_euler/problem_012/sol2.py

Improve Project Euler problem 012 solution 2 - the top 9 slowest solution on GitHub Actions logs (under `slowest 10 durations`: `4.35s call     scripts/validate_solutions.py::test_project_euler[problem_012/sol2.py]`):
* Improve solution (locally 6+ times - from 3+ seconds to ~0.5 seconds)

Improve Project Euler problem 012 solution 2

---

physics/newtons_second_law_of_motion.py

Added newtons_second_law_of_motion.py in physics directory.
Fixes: #5288

Added newtons_second_law_of_motion.py

---

scheduling/shortest_job_first.py

fix typo on line 126

---

project_euler/problem_010/sol1.py

Improve Project Euler Problem 10 Sol-1

---

mypy.ini
other/fischer_yates_shuffle.py

[mypy] Fix `other/fischer_yates_shuffle.py`

---

other/least_recently_used.py

[mypy] fix type annotations for other/least-recently-used.py

---

web_programming/fetch_well_rx_price.py

Scraping prescription drug prices from Rx site using the prescription drug name and zipcode

---

LICENSE.md

Year change

---

ciphers/shuffled_shift_cipher.py
data_structures/stacks/dijkstras_two_stack_algorithm.py
divide_and_conquer/inversions.py
maths/volume.py
strings/manacher.py

Fix some typos.

---

strings/word_occurrence.py

word_occurence -> word_occurrence

Fix typo in word_occurrence.py

---

ciphers/enigma_machine2.py

* [x ] This pull request is all my own work -- I have not plagiarized.
* [x ] I know that pull requests will not be merged if they fail the automated tests.
* [x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x ] All filenames are in all lowercase characters with no spaces or dashes.
* [x ] All functions and variable names follow Python naming conventions.
* [x ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x ] All functions have …

Tiny spelling error

---

strings/hamming_distance.py

I added the algorithm to calculate the hamming distance between two strings.

Add hamming distance

---

.gitignore

Updated .gitignore for Visual Studio

Updated .gitignore for Visual Studio

---

physics/horizontal_projectile_motion.py

* [x ] Fix a bug or typo in an existing algorithm?
* [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.

typo corrected: heart -> Earth

---

DIRECTORY.md
project_euler/problem_114/sol1.py

Add Project Euler problem 114 solution 1:

Add Project Euler problem 114 solution 1

---

strings/dna.py

**added an algorithm, which: given one side of a _DNA strand_ returns the other, complementary side of the same strand
[how genomes work](https://www.genome.gov/genetics-glossary/acgt#:~:text=ACGT%20is%20an%20acronym%20for,and%20cytosine%20pairs%20with%20guanine.)**

adding the dna algorithm

---

other/maximum_subarray.py

Added code for Maximum subarray sum

Added code for Maximum Subarray Sum

---

.pre-commit-config.yaml
DIRECTORY.md

Fix pre-commit.ci: additional_dependencies: [types-requests]

---

.github/CODEOWNERS

Removes user @mateuszz0000 that does not exist, or seems to have been renamed to @L3str4nge.
According to the git blame, @L3str4nge is the one that originally updated this file. By reading the comments in #3280, it seems like @mateuszz0000 was changed to @L3str4nge.
I don't think it is a security issue, if I read correctly the ["About code owners"](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) guide, but I guess it's worth keeping thinks up to date. @L3str4nge does not seem to be active on this repo anymore, but I can update the PR to change @mateuszz0000 with @L3str4nge.

fix: remove non-existing user from CODEOWNERS

---

CONTRIBUTING.md

Updating CONTRIBUTING.md docs with a Discord Server Invite link.

Discord Server invite

---

physics/lorentz_transformation_four_vector.py

correct spelling according to: https://en.wikipedia.org/wiki/Lorentz_transformation

lorenz -> lorentz

---

maths/segmented_sieve.py

Add typing to maths/segmented_sieve.py

---

maths/volume.py

Add volume of hollow circular cylinder, Exceptions

---

maths/abs.py

Add typing to maths/abs.py

---

maths/ceil.py

Add typing to maths/ceil.py

---

maths/floor.py

Add typing to maths/floor.py

---

maths/add.py

https://stackoverflow.com/questions/50928592/mypy-type-hint-unionfloat-int-is-there-a-number-type

Add typing to maths/add.py

---

maths/sum_of_arithmetic_series.py

Add typing to maths/sum_of_arithmetic_series.py

---

data_structures/queue/linked_queue.py

Remove extra Semicolon

---

data_structures/binary_tree/binary_tree_traversals.py

Makes binary tree `:meth:make_tree` function more understandable.
Instead of 
```py
return Node(1, Node(2, Node(4), Node(5)), Node(3))
```
there is a visual example of the tree and the nodes are created manually without passing multiple parameters

refactor: Make code more understandable

---

boolean_algebra/norgate.py

remove useless bool() call

---

.github/CODEOWNERS
DIRECTORY.md

chore: remove inactive user from CODEOWNERS

---

.pre-commit-config.yaml

Add ``yesqa`` (flake8-plugin) to ``pre-commit``
https://github.com/asottile/yesqa

ci: Add ``yesqa`` (flake8-plugin) to ``pre-commit``

---

computer_vision/horn_schunck.py

Updated the namespace of `convolve` in `computer_vision/horn_schunck.py` from `scipy.ndimage.filters` to `scipy.ndimage`, as the former is depreciated (see the [release notes](https://docs.scipy.org/doc/scipy/release.1.8.0.html#clear-split-between-public-and-private-api) for SciPy release 1.8.0 for more details).
Fixes #7299

Fix Horn-Schunck depreciated namespace

---

maths/maclaurin_series.py

… for cos approximation
- Renamed maclaurin_sin.py to maclaurin_series.py to be more inclusive
- Added maclaurin_cos() function to maclaurin_series.py to approximate cos(x)

Maclaurin approximation of cos

---

maths/maclaurin_series.py

Remove unnecessary brackets
* [x ] This pull request is all my own work -- I have not plagiarized.

Simplify the code in maclaurin_series

---

maths/factors.py

Reduced Time Complexity to O(sqrt(n))

---

quantum/superdense_coding.py

Replace deprecated `qasm_simulator` with `aer_simulator` (#7308)

---

web_programming/get_top_billioners.py

Previous commit failed pre-commit

fix: Fix line too long in doctest

---

strings/is_spain_national_id.py
strings/spain_national_id_validator.py

Implemented algorithm to validate Spain National ID. Due to obvious reasons, the ID used is the one that actas as placeholder in government sites and it is not assigned to nobody.
Fixes: #7574

Add Spain National ID validator (#7574)

---

physics/horizontal_projectile_motion.py

The shape of the trajectory of projectile is a parabola.

corrected the shape of trajectory

---

computer_vision/cnn_classification.py

Updated documentation of cnn_classification.py

---

bit_manipulation/highest_set_bit.py

Add function for highest set bit location

---

strings/barcode_validator.py

Updated a typo in print statement

---

maths/karatsuba.py

Remove unnecessary else statement

---

ciphers/caesar_cipher.py

very character -> every character

fix typo in caesar_cipher.py

---

strings/is_srilankan_phone_number.py

Srilankan phone number validation

---

strings/text_justification.py

Added algorithm for Text Justification in Strings

---

CONTRIBUTING.md

Correcting typos in CONTRIBUTING.md

Correcting typos in CONTRIBUTING.md

---

DIRECTORY.md
data_structures/heap/binomial_heap.py
other/activity_selection.py
searches/binary_tree_traversal.py

Some files were completely excluded from flake8 checks. 
- Remove file-level suppressions
- Fix simple warnings
- Suppress long line indocstring

Remove file-level flake8 suppression

---

ciphers/simple_keyword_cypher.py

Fix grammatical mistakes in `simple_keyword_cypher.py`

---

sorts/README.md

Updated the readme section for sorts.

Updated info

---

quantum/quantum_teleportation.py

Fixes the `qasm_simulator` deprecation

fix(quantum): Correct simulator deprecation

---

data_structures/hashing/double_hash.py

Description of Double hasing

---

hashes/README.md

Added description of hashing algorithm for better understanding.

Added Readme file to document the hashing algorithm.

---

other/quine.py

Created a Quine script to the directory `other`. A quine is an script the prints its own source code, in this case ignoring docstring and shebang.

Adding a Quine in Python.

---

bit_manipulation/index_of_rightmost_set_bit.py

Added algorithm for finding the zero-based index of first set bit in a given non-negative integer from the right side, i.e. rightmost set bit

Added algorithm for finding index of rightmost set bit

---

physics/shear_stress.py

Corrected filename and function names. Sheer stress should be shear stress. 
Added a brief description and  Wikipedia URL.

Shear stress: typo + Wikipedia URL

---

electronics/ind_reactance.py

Adding new file ind_reactance.py for calculating inductive reactance, frequency or inductance.

Adding inductive reactance calculation

---

DIRECTORY.md
maths/number_of_digits.py

```
num_digits(262144): 6 -- 0.2226011250168085 seconds
num_digits_fast(262144): 6 -- 0.13145116699161008 seconds
num_digits_faster(262144): 6 -- 0.09273383300751448 seconds
num_digits(1125899906842624): 16 -- 0.6056742920191027 seconds
num_digits_fast(1125899906842624): 16 -- 0.15698366600554436 seconds
num_digits_faster(1125899906842624): 16 -- 0.1027024170034565 seconds
num_digits(1267650600228229401496703205376): 31 -- 1.1957934170495719 seconds
num_digits_fast(1267650600228229401496703205376): 31 -- 0.15552304196171463 seconds
num_digits_faster(1267650600228229401496703205376): 31 -- 0.13062308297958225 seconds
```

maths/number_of_digits.py: Streamline benchmarks

---

DIRECTORY.md
maths/prime_numbers.py

prime_numbers.py: Tighten up the benchmarks

---

maths/liouville_lambda.py

algorithm: Liouville lambda function

---

maths/decimal_to_fraction.py

Add algorithm to convert decimal number to its simplest fraction form

---

DIRECTORY.md
bit_manipulation/numbers_different_signs.py

add numbers different signs algorithm.

---

maths/prime_sieve_eratosthenes.py

Change `prime_sieve_eratosthenes.py` to return a list of ints rather than print to avoid side effects
Also added more doctests

Change prime_sieve_eratosthenes.py to return list

---

.github/ISSUE_TEMPLATE/other.yml

- Add the other/miscellaneous form.
- Closes #8133.

docs: add the other/miscellaneous form

---

.github/stale.yml
.github/workflows/ruff.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
hashes/sha1.py
machine_learning/sequential_minimum_optimization.py
neural_network/convolution_neural_network.py
project_euler/README.md
pyproject.toml
web_programming/download_images_from_google_query.py

New gitter link  added or replaced

---

electronics/apparent_power.py

added reference link.

---

maths/is_palindrome.py

Added is_palindrome.py

---

ciphers/mixed_keyword_cypher.py

Wrapped final print statement in if __name__ == "__main__" function as requested.

add __main__ around print

---

graphs/greedy_best_first.py

fix typo graphs/greedy_best_first.py

---

.github/workflows/build.yml
DIRECTORY.md

Re-enable some tests that were disabled in #6591.
Partial fix for #8818

GitHub Actions build: Add more tests

---

.github/workflows/build.yml
quantum/bb84.py

Fix failing pytest quantum/bb84.py

---

.devcontainer/Dockerfile

[skip-ci] In .devcontainer/Dockerfile: `pipx install pre-commit ruff`
Fixes #8891

In .devcontainer/Dockerfile: pipx install pre-commit ruff

---

DIRECTORY.md
README.md

chore: use newest Discord invite link

---

searches/linear_search.py

Fix linear_search docstring return value

---

fractals/sierpinski_triangle.py

The window will now remain open after the fractal is finished being drawn, and will only close upon your click.

Window closing fix

---

dynamic_programming/tribonacci.py

Added implementation for Tribonacci sequence using dp

---

neural_network/activation_functions/leaky_rectified_linear_unit.py

Added Leaky ReLU Activation Function

---

neural_network/back_propagation_neural_network.py

* [ x ] Fix a bug or typo in an existing algorithm?
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new Python files are placed inside an existing directory.
* [ x ] All filenames are in all lowercase characters with no spaces or dashes.
* [ x ] All functions and variable names follow Python naming conventions.
* [ x ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* …

Style sigmoid function in harmony with pep guideness

---

.github/workflows/ruff.yml
DIRECTORY.md

https://docs.astral.sh/ruff/settings/#output-format

Fix ruff warning

---

maths/binary_exponentiation_2.py

Add typing to binary_exponentiation_2.py

---

maths/binary_exponentiation.py

Add typing to binary_exponentiation.py

---

maths/binary_exponentiation_3.py

Add typing to binary_exponentiation_3.py

---

maths/binomial_coefficient.py

Add typng to binomial_coefficient.py

---

maths/maclaurin_series.py

Fix a few failing build doctests on Python 3.12.

Fix accuracy in maclaurin_series on Python 3.12

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json

Upgrade our Devcontainer to Python 3.12 on Debian bookworm

---

sorts/stooge_sort.py

Add typing to stooge_sort.py

---

sorts/shell_sort.py

Add typing to shell_sort.py

---

sorts/selection_sort.py

Add typing to selection_sort.py

---

CONTRIBUTING.md

- Added a markdown header under Contributing for issues.
- Added paragraph to say not to open new issues

Update contributing guidelines to say not to open new issues for algorithms

---

arithmetic_analysis/lu_decomposition.py
maths/karatsuba.py

Karatsuba type annotation

---

arithmetic_analysis/lu_decomposition.py
maths/hardy_ramanujanalgo.py

hardy_ramanujanalgo type annotation

---

electronics/resistor_color_code.py

Added resistor_color_code.py in electronics/. Program calculates the resistance of a given n -  band resistor using the color code system

feat: :sparkles: calculating the resitance of resistor using color codes

---

neural_network/activation_functions/mish.py

Added Mish Activation Function

---

neural_network/activation_functions/mish.py

Changed Mish Activation Function to use Softplus

---

machine_learning/loss_functions/huber_loss.py

Added Huber Loss Function

---

data_structures/linked_list/is_palindrome.py

@SaiHarshaK Fixes https://github.com/TheAlgorithms/Python/pull/10081#discussion_r1349651289

Remove backslashes from is_palindrome.py

---

maths/factorial.py

seperation between description and docstrings

---

arithmetic_analysis/lu_decomposition.py
machine_learning/k_means_clust.py

Contributes to #9718
before:
```
("sum", np.sum),
*******************
("mean_with_na", np.mean),
```
after:
```
("sum", "sum"),
******************
("mean_with_na", "mean"),
```
the change removes the warning:
```
/home/runner/work/Python/Python/machine_learning/k_means_clust.py:236: FutureWarning: The provided callable <function sum at 0x7f20c02034c0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
.agg(
```
And
```
/home/runner/work/Python/Python/machine_learning/k_means_clust.py:236: FutureWarning: The provided callable <function mean at 0x7f3d7db1c5e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. …
```

k_means_clust - change to remove warning

---

data_structures/arrays/find_triplets_with_0_sum.py

add find triplets with 0 sum (3sum)

---

maths/basic_maths.py

Improves #9943
The Euler's Phi function doctest is worse than the other functions' doctests in the same file, only covering one case and lacking exception handling for negative numbers, unlike the other functions. This pull request adds exception handling for negative numbers, and expands the doctest with two other cases, to bring it up to standard.

Expand euler phi function doctest

---

bit_manipulation/missing_number.py

fix: incorrect range detection in find_missing_number

---

graphs/a_star.py

Adding more tests to a star algorithm
Fixes #9943

test: adding more tests to a star algorithm

---

.github/ISSUE_TEMPLATE/feature_request.yml

Modify feature_request.yml to indicate any issues about implementations of new algorithms will be closed.
See #9343

Add note to feature_request.yml about not opening issues for new algorithms

---

bit_manipulation/count_number_of_one_bits.py

Fix benchmark to test with the provided number instead on 25

---

strings/join.py

Added test cases to join.py

---

.github/pull_request_template.md

Adding test scenarios to pull request template

docs: add test scenarios to pull request template

---

sorts/selection_sort.py

Updated Selection Sort

---

strings/frequency_finder.py

Adding doctests to frequency_finder.py

---

sorts/merge_sort.py

This enhanced code includes improved variable naming, error handling for user input, and more detailed docstrings. It's now more robust and readable.

Code Enhancements in merge_sort.py

---

maths/primelib.py

Contributes to #9943 - Add doctest for maths/primelib

Add a doctest to maths/primelib

---

data_structures/hashing/hash_map.py
data_structures/heap/heap.py

Added doctest to hash_map.py

---

maths/power_using_recursion.py

Fix typo power_using_recursion.py

---

strings/detecting_english_programmatically.py

Added doctest to detecting_english_programmatically.py

---

backtracking/knight_tour.py

Fix typo in knight_tour.py

---

backtracking/n_queens.py

Add doctest to is_safe function

---

sorts/quick_sort.py

Optimized quicksort implementation for clarity and performance.

optimize quicksort implementation

---

.github/workflows/directory_writer.yml

Same as TheAlgorithms/Rust#647 - it contains the description of the problem, which this PR solves.

fix: use `GITHUB_ACTOR` in `git config`

---

.github/workflows/directory_writer.yml
.github/workflows/project_euler.yml

This PR updates the `actions/setup-python` to `v5`.

chore: update `actions/setup-python` to `v5`

---

data_structures/binary_tree/red_black_tree.py

---
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [red_black_tree.py](https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/red_black_tree.py#L454), method: `is_left`, a logical equality check operation was performed with the same operand on both sides. The comparison operation always returns either true or false. Such logical short circuits in code lead to unintended behavior. iCR suggested that the logical operation should be reviewed for correctness.
The expression `self.parent.left is self.parent.left is self` is not clear in its intent. The chaining of is operators can make it hard to understand what exactly is being checked.
*This section is only relevant if your project requires contributors to sign a …

Fixed Inappropriate Logical Expression

---

computer_vision/README.md

fixes #11256 : computer vision link update in .computer_vision/README.md

---

.github/CODEOWNERS

(I don't know how to add the checkmark to the markdown boxes... I'm new to contributing and this is one of my firsts ever, so sorry about that.)
* [ ✓ ] Documentation change?
* [ ✓ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ✓ ] This pull request is all my own work -- I have not plagiarized.
* [ ✓ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ✓ ] All filenames are in all lowercase characters with no spaces or dashes.

Fixed lines that needed to be uncommented after Hacktoberfest

---

linear_algebra/src/conjugate_gradient.py
machine_learning/decision_tree.py
machine_learning/k_means_clust.py
machine_learning/sequential_minimum_optimization.py
neural_network/back_propagation_neural_network.py
neural_network/convolution_neural_network.py
neural_network/input_data.py
neural_network/two_hidden_layers_neural_network.py
pyproject.toml

Enable ruff NPY002 rule

---

data_structures/binary_tree/segment_tree.py

Changed the N to self.N in show_data in segment_tree.py
Fixes #11232

Fix a bug in segment_tree.py

---

divide_and_conquer/power.py

add doctest/document to actual_power and document to power

---

machine_learning/sequential_minimum_optimization.py

Fix grammar and spelling mistakes, along with minor formatting changes. Most importantly, "cancer" had been consistently misspelled as "cancel", including in function names.

Fix grammar and spelling mistakes in `sequential_minimum_optimization.py`

---

conversions/weight_conversion.py

Add a new test to weight_conversion to handle conversion errors.
* [ x ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new Python files are placed inside an existing directory.
* [ x ] All filenames are in all lowercase characters with no spaces or dashes.
* [ x ] All functions and variable names follow Python naming conventions.
* [ x ] All …

Tests/add new test case weight_conversion

---

maths/numerical_analysis/integration_by_simpson_approx.py

Fix typo in Thomas Simpson's name. See: https://en.wikipedia.org/wiki/Thomas_Simpson

Fix typo in integration_by_simpson_approx.py

---

.github/workflows/build.yml

Drop https://six.readthedocs.io

Drop six from our GitHub Actions

---

dynamic_programming/floyd_warshall.py

Contributes to https://github.com/TheAlgorithms/Python/issues/9943

Adding Doctests to floyd_warshall.py

---

data_structures/stacks/next_greater_element.py

The docstrings for all functions have been revised to provide more comprehensive explanations. These enhancements include detailed descriptions of the functions parameters, return values, and the time complexities associated with the algorithms they utilize.

Improve comments, docstrings in next_greatest_element.py

---

strings/min_cost_string_conversion.py

Removed incorrect type hints

---

dynamic_programming/longest_common_subsequence.py

- Add test cases of the longest_common_subsequence (increase test case coverage for that file by 5%)

feat: add testcases for longest_common_subsequence

---

CONTRIBUTING.md

Updated the example command for running ruff to use `ruff check .` instead of just `ruff .`, as the latter syntax has been removed. This ensures contributors use the correct command when running ruff locally before submitting pull requests.
The change addresses the following error that users may encounter with the outdated command:
```
error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```

Update ruff usage example in CONTRIBUTING.md

---

scripts/validate_filenames.py

`validate_filenames.py` Shebang `python` for Windows

---

DIRECTORY.md
matrix/matrix_based_game.py

Added matrix based color game algorithm

---

maths/volume.py

Fix sphinx/build_docs warnings for maths/volume

Fix sphinx/build_docs warnings for maths/volume

---

maths/special_numbers/armstrong_numbers.py

#9943 : improve coverrage test for armstrong number

---

maths/perfect_number.py

Add additional doctests, fix grammatical errors for maths/perfect_number.py

---

computer_vision/README.md

Remove inaccessible URL.
Remove an inaccessible URL in computer_vision/README.md Line 11.
Fixes #12382

Remove inaccessible URL in computer_vision/README.md

---

other/bankers_algorithm.py
other/davis_putnam_logemann_loveland.py
other/scoring_algorithm.py

Fix sphinx/build_docs warnings for other

Fix sphinx/build_docs warnings for other

---

ciphers/autokey.py
ciphers/caesar_cipher.py
ciphers/decrypt_caesar_with_chi_squared.py
ciphers/enigma_machine2.py
ciphers/rsa_factorization.py
ciphers/simple_keyword_cypher.py
ciphers/trifid_cipher.py

Fix sphinx/build_docs warnings for ciphers

Fix sphinx/build_docs warnings for ciphers

---

maths/numerical_analysis/intersection.py

Added doctest to intersection.py

Contributes to #9943

---

maths/power_using_recursion.py

I have added doctest in the power_using_recusion algorithm in maths directory 
Contributes to #9943

Added doctest to /maths/power_using_recursion.py

---

strings/min_cost_string_conversion.py

- Add test case for assemble_transformation in strings/min_cost_string_conversion and increase the test coverage by around 5%

feat: add testcase of assemble_transformation

---

sorts/quick_sort_3_partition.py

Add doctest for quick_sort_3_partition. Contributes to #9943

---

.github/workflows/sphinx.yml
DIRECTORY.md

Speed up our slowest GitHub Action by running it on an ARM processor.
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
In this example, using an ARM processor can cut execution times in half!
https://github.com/TheAlgorithms/Python/actions/workflows/sphinx.yml

Sphinx runs on ubuntu 24.04 arm

---

data_structures/arrays/sudoku_solver.py

Update docstrings in the functions definitions.
* [] Add an algorithm?
* [] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [] Documentation change?
* [] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

Update docstrings in the functions definitions.

---

divide_and_conquer/power.py

To fix the inaccuracies and allow handling of negative exponents and bases, the key issue lies in how negative numbers are handled in the power calculation, especially when dividing.
```python
>>> power(4, 6)
4096
>>> power(2, 3)
8
>>> power(-2, 3)
-8
>>> power(2, -3)
0.125
>>> power(-2, -3)
-0.125
```

Fix And Add power.py

---

data_structures/linked_list/from_sequence.py

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

maths/decimal_to_fraction.py

Improved test coverage in  decimal_to_fraction.py

---

maths/decimal_to_fraction.py

Fixes issue # 8936 

---

data_structures/linked_list/doubly_linked_list_two.py

Generic type hint in DDL

---

scripts/validate_solutions.py

Enable `uv run scripts/validate_solutions.py` or `pipx run scripts/validate_solutions.py`
* https://peps.python.org/pep-0723
* https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies
`scripts/validate_solutions.py`:
```diff
+ # /// script
+ # requires-python = ">=3.13"
+ # dependencies = [
+ #     "pytest",
+ #     "requests",
+ # ]
+ # ///
```

Add PEP723 header to scripts/validate_solutions.py

---

scripts/validate_filenames.py

```diff
- #!python
+ #!/usr/bin/env python3
```
https://docs.python.org/3/using/windows.html#shebang-lines
https://docs.python.org/3/library/venv.html#how-venvs-work
Closes: #12549

Add a proper shebang line to scripts/validate_filenames.py

---

scripts/build_directory_md.py

Contributes to https://github.com/TheAlgorithms/Python/issues/9943

Adding doctest for md_prefix function in build_directory_md.py
