- QuickSort.py
I like the idea of having the implementation of some classic algorithms implemented in Python: the pseudo code is similar to the code and being able to run it straight away really helped me through the Algorithm class I took. I'd like to contribute :+1:
> Add quicksort

- BubbleSort.py
- InsertionSort.py
- LinearSearch.py
- MergeSort.py
- QuickSort.py
- README.md
Thought I would offer a contribution to make some of the code more pythonic.
> Improvements

- .travis.yml
- README.md
Add travis-ci integration (Need to be additionally configured via https://travis-ci.org)
> Travis integration (Add .travis.yml)

- README.md
- sorts/bogosort.py
- sorts/bubble_sort.py
- sorts/heap_sort.py
- sorts/insertion_sort.py
- sorts/merge_sort.py
- sorts/quick_sort.py
- sorts/selection_sort.py
- sorts/shell_sort.py
Added the Shell Sort algorithm and fixed the spelling in the other sorts.  I also added function documentation to heap_sort.py
> Added Shell Sort

- searches/linear_search.py
The documentation comment said "binary search" when it should say "linear search".
> Fixed typo in linear_search.py

- sorts/bubble_sort.py
I think bubble_sort has some thing which can be optimized.
> for better bubble sort

- other/password_generator.py
Uses import random for namespace cleanliness
Uses list instead of string for 'chars' variable in order to shuffle, increases randomness
Instead of string formatting, uses string concatenation because (currently) it is simpler
> Add another randomness into the password generator

- other/word_patterns.py
Uses 'with' statement when opening files to guarantee files are closed even when the process is interrupted.
> Uses 'with' instead of manually closing files

- dynamic_programming/longest_sub_array.py
Given an array, to find the longest and continuous sub array and get the max sum of the sub array in the given array.
> add sum of the longest sub array

- data_structures/Heap/heap.py
The code contains all basic operations associated with Heap Data Structure.
> Code for Heap data structure

- dynamic_programming/longest_increasing_subsequence.py
The program now returns the entire longest increasing subsequence instead of returning only the length. Also: Code optimized and entirely explained in comments
> Script Output: The entire longest increasing subsequence instead of it's length

- traverals/binary_tree_traversals.py
Previously, the entry in tree was terminated by negative (which was the base condition for termination of entry loop). Now i've re-edited the code and have the user input any number of his choice. Added a feature that the user can terminate the entry in the tree at any point of time by just pressing 'N' or 'n' which is being checked at every input points. If a number is entered in place of 'N' or 'n', that number is entered into the node.
> Added feature for negative number input

- .gitignore
- .travis.yml
- data_structures/Binary Tree/binary_seach_tree.py
Add the structures Binary Search Tree, code with example
> Add Binary Search Tree in data_structures

- searches/binary_search.py
I think it will be helpful for a beginner.
> Add bin-search implement by recursion

- dynamic_programming/k_means_clustering_tensorflow.py
The k-means clustering is done by using tensorflow which is the vital and growing machine learning library of google.
> Added one of the most important machine learning algorithm

- ciphers/playfair_cipher.py
Create a playfair cipher implementation as described on https://en.wikipedia.org/wiki/Playfair_cipher#Description
> Playfair cipher

- data_structures/Queue/QueueOnList.py
`front` is added so that dequeue can be done any number of times.Without `front`,it displays only `self.entries[0]` as _dequeued._
> Added front to indicate the starting of the Queue

- data_structures/Trie/Trie.py
Regarding #105 I've worked on a Trie implementation using a dict
> Trie implementation

- Neural_Network/neuralnetwork_bp3.py
I add bp neural network with 3 layers into Neural Network File
> add neuralnetwork_bp3.py

- machine_learning/decision_tree.py
I've implemented a basic decision tree in python as an example of how they work. Although the class I've created only works on one dimensional data sets, the reader should be able to generalize it to higher dimensions or non-continuous labels should they need to.
I believe that decision trees should be in this repository because they're fundamental in any machine learning course and are important in the field.
> Implementation of a regression tree in python

- data_structures/Graph/P01_BreadthFirstSearch.py
- data_structures/Graph/P02_DepthFirstSearch.py
Reverts TheAlgorithms/Python#148
> Revert "There were 2 codes for BFS and DFS in data-structure/Graph."

- dynamic_programming/fibonacci.py
- searches/binary_search.py
- searches/linear_search.py
- sorts/bogosort.py
- sorts/bubble_sort.py
- sorts/cocktail_shaker_sort.py
- sorts/gnome_sort.py
- sorts/insertion_sort.py
- sorts/merge_sort.py
- sorts/quick_sort.py
- sorts/selection_sort.py
- sorts/shell_sort.py
- traverals/binary_tree_traversals.py
For python 2.x and 3.x compatibility: 3.x has **not** raw_input builtin
->
For python 2.x and 3.x compatibility: 3.x has **no** raw_input builtin
> Fix: typo in multiple files.

- data_structures/Graph/dijkstra_algorithm.py
Added Object Oriented code for dijkstra algorithm in graph folder.
> Added Dijkstra Algorithm

- data_structures/AVL/AVL.py
- data_structures/Binary Tree/binary_seach_tree.py
> working on #93

- data_structures/Binary Tree/FenwickTree.py
Add Fenwick Tree (Binary Index Tree)
Update index i with value val in O(lg N)
Query from interval [0,i] in O(lg N)
> Add Fenwick Tree

- other/nested_brackets.py
algorithm now able to process string with characters other than brackets
> fixed issue#171

- data_structures/UnionFind/tests_union_find.py
- data_structures/UnionFind/union_find.py
Added an implementation of the UnionFind algorithm. Wrote some tests too (nothing exceptional, only to cover some basic cases).
> Created Union-Find algorithm

- Multi_Hueristic_Astar.py
Implemented the paper www.cs.cmu.edu/~venkatrn/papers/ijrr16.pdf
> Added Multi Heuristic Astar

- data_structures/Binary Tree/binary_search_tree.py
- Added delete node function
- Added a customizable traversalTree function that gets a list of nodes in the tree
- Created an __str__ function that returns an string with all the nodes in the tree in order
- Added a bigger testing example
> Added delete function to binary_search_tree.py and print function

- data_structures/Graph/BellmanFord.py
- data_structures/Graph/Dijkstra.py
- data_structures/Graph/FloydWarshall.py
PR includes the following algorithms:
1. Dijkstra's Algorithm
2. Bellman-Ford Algorithm
3. Floyd-Warshall Algorithm
> Add shortest path algorithms

- strings/knuth-morris-pratt.py
Hi there, love your repo and would love to contribute I'm currently at university and learning more and more complex algorithms and I'm learning a lot more through implementing them.
Here's the knuth-morris-pratt string search hopefully more to come :)
> Added a python implementation of knuth-morris-pratt string search algo

- File_Transfer_Protocol/ftp_send_receive.py
Python code to send & receive files via ftp protocols
> File Transfer Protocols

- data_structures/Graph/even_tree.py
https://www.hackerrank.com/challenges/even-tree/problem
> add even tree problem

- sorts/normal_distribution_QuickSort_README.md
As in the file there were not spaces given properly so heading were not showing as per expected
> Fixed heading's formatting errors

- Project Euler/Problem 16/sol1.py
- Project Euler/Problem 20/sol1.py
- Project Euler/README.md
Solution to the Problem 16  has been added.
> Problem 16 Added

- File_Transfer_Protocol/ftp_client_server.py
client server connection via file transfer protocol
> ftp client server connection

- ciphers/playfair_cipher.py
flake8 results:
```
./ciphers/playfair_cipher.py:88:25: F821 undefined name 'chunk'
for char1, char2 in chunk(ciphertext, 2):
^
```
> chunk() --> chunker() to resolve an undefined name

- Bisection.py
- Intersection.py
- NeutonMethod.py
- searches/jump_search.py
Bisection uses the Bolzano theorem, the others 2 find the root faster by using the derivative of the function
> Three methods to find the roots of non-linear functions

- ciphers/XOR_cipher.py
This class implements the XOR-cipher algorithm and provides some useful methods for encrypting and decrypting strings and files.
You will find detailed docstrings in each method.
* encrypt : list of char
* decrypt : list of char
* encrypt_string : str
* decrypt_string : str
* encrypt_file : boolean
* decrypt_file : boolean
> XOR cipher algorithm

- ciphers/XOR_cipher.py
> improvement XOR_cipher.py

- .travis.yml
The owner of the this repo would need to go to https://travis-ci.org/profile and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.  Flake8 will find bugs and code smells.
>  Add automated flake8 testing of pull requests

- data_structures/LinkedList/singly_LinkedList.py
Line 15: insert_tail(Head.next, data) --> Head.next.insert_tail(data)
Fixes: $ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./data_structures/LinkedList/singly_LinkedList.py:14:13: F821 undefined name 'insert_tail'
insert_tail(Head.next, data)
^
1     F821 undefined name 'insert_tail'
```
Also formats the code to be compliant with [PEP8](http://pep8.org).
> Fix unresolved name: insert_tail()

- searches/binary_search.py
In binary_search_by_recursion, if you search array for a value that does not exist, you will get this error:
RecursionError: maximum recursion depth exceeded in comparison
To fix this, first check to make sure that the value is between left and right points like this:
if (right < left):
return None
A similar construct has already been applied to binary_search, but did not exist in the recursive alternative.
> Fixed recursion error in binary_search_by_recursion

- README.md
A small edit. Average case for quicksort changed from O(n^2) to O(n log n). Sited:
https://en.wikipedia.org/wiki/Quicksort
> Updated average case for Quicksort

- Project Euler/Problem 10/sol1.py
@daniel-s-ingram Similar changes needed on Problems 25 and 28 so they can run on Python 3.
flake8 testing of https://github.com/TheAlgorithms/Python on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./Project Euler/Problem 10/sol1.py:5:11: F821 undefined name 'xrange'
for i in xrange(2, int(sqrt(n))+1):
^
./Project Euler/Problem 10/sol1.py:17:11: F821 undefined name 'xrange'
for i in xrange(3, n, 2):
^
./Project Euler/Problem 25/sol1.py:10:12: F821 undefined name 'xrange'
for i in xrange(2, n+1):
^
./Project Euler/Problem 28/sol1.py:7:11: F821 undefined name 'xrange'
for i in xrange(1, int(ceil(n/2.0))):
^
4     F821 undefined name 'xrange'
```
> xrange() was removed in Python 3 in favor of range()

- data_structures/hashing/__init__.py
- data_structures/hashing/double_hash.py
- data_structures/hashing/hash_table.py
- data_structures/hashing/hash_table_with_linked_list.py
- data_structures/hashing/number_theory/prime_numbers.py
- data_structures/hashing/quadratic_probing.py
Hashing functions module added to data_structures.
> hash functions added

- searches/jump_search.py
Try to run this on Python 2.7.10.
An error occurs, the error log like this:
_Traceback (most recent call last):
File "jump_search.py", line 25, in <module>
index = jump_search(arr, x)
File "jump_search.py", line 7, in jump_search
while arr[min(step, n)-1] < x:
TypeError: list indices must be integers, not float_
the fix make the code can be run under python2 & python3.
> fix type error (except an int) in jumpmp_search line 7.

- Project Euler/Problem 01/sol4.py
I fixed the solution 4 of problem 1.
> fixed solution 4 of problem 1

- sorts/quick_sort_3partition.py
When I study about sorting algorithm, I saw another version of quick-sort which is called 3-way quicksort.
In that site, 3-way quicksort is explained as 
"The 3-way partition variation of quick sort has slightly higher overhead compared to the standard 2-way partition version. Both have the same best, typical, and worst case time bounds, but this version is highly adaptive in the very common case of sorting with few unique keys."
I create pull request, just because other students like me notice that there is other version of quick-sort.
> quicksort_3_partition

- README.md
- ciphers/elgamal_key_generator.py
#317 issue (closed)
Hello!
I'm working on Elgamal cipher and this request is for my "key generator" code
Regards,
> Create new cipher - Elgamal cipher key generator

- sorts/bubble_sort.py
The current implementation efficiency is **O(n^2)** always.
Now it allow for better performance, for example when the collection is already sorted or slightly disordered. It can achieve **Best case performance O(n)**.
> Break if the collection is sorted

- hashes/chaos_machine.py
__raw_input()__ was removed in Python 3 in favor of __input()__.  This change ensure similar functioning in both Python 2 and Python 3.
> Properly define raw_input() in Python 3

- data_structures/Binary Tree/SegmentTree.py
Remove redundant parameters in segment tree methods. Fixes #310
> refactor-segment-tree

- dynamic_programming/knapsack.py
Added a function which implements knapsack using memory functions. Also I updated the test cases to include test cases for the memory function implementation.
> Added code for memory function implementation

- ciphers/Onepad_Cipher.py
flake8 testing of https://github.com/TheAlgorithms/Python on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ciphers/Onepad_Cipher.py:11:17: F821 undefined name 'random'
k = random.randint(1, 300)
^
1     F821 undefined name 'random'
1
```
These kind of errors should be automatically detected by #218
> Undefined name: import random in Onepad_Cipher.py

- sorts/bucket_sort.py
I decided to use the local insertion sort to fix this algorithim, if you need to use other implementation of that let me know please.
> Use local insertion sort (solves #334)

- searches/sentinel_linear_search.py
Add sentinel linear search algorithm (also known as "sentinel search" or "linear search with sentinel").
References:
- https://thecodeaddict.wordpress.com/tag/sentinel-search/
- http://www.delorie.com/gnu/docs/avl/libavl_26.html
> searches: add sentinel linear search algorithm

- strings/levenshtein-distance.py
Add the Levenshtein distance string metric.
> Levenshtein distance is a string metric for measuring the difference between two sequences.
Reference: https://en.wikipedia.org/wiki/Levenshtein_distance
> Levenshtein distance

- Graphs/ArticulationPoints.py
- Graphs/CheckBipartiteGraph_BFS.py
- Graphs/FindingBridges.py
- Graphs/KahnsAlgorithm_long.py
- Graphs/KahnsAlgorithm_topo.py
- Graphs/MinimumSpanningTree_Prims.py
- Maths/BasicMaths.py
- Maths/SegmentedSieve.py
- Maths/SieveOfEratosthenes.py
- Finding Articulation points in Undirected Graph
- Check whether a graph is bipartite or not using BFS
- Finding bridges in Undirected graph
- Finding longest distance in Directed Acyclic Graph using Kahns Algorithm
- Using Kahn's Algorithm to find Topological ordering of Directed Acyclic Graph using BFS
- MinimumSpanning Tree using Prim's Algorithm
- Basic Maths functions
- Finding prime numbers using Segmented Sieve ( Space complexity is reduced in Segmented sieve )
- Sieve of Eratosthenes ( To find prime numbers )
> Extra Algorithms added

- README.md
Part of #374 issue:
Added descriptions to these algorithms: 
- Bucket sort
- Cocktail shaker sort
- Radix sort
- Topological sort
> Added Algorithm descriptions to README.md

- README.md
Updated README.md to include description of Heap Sort
> Updated README.md to include Heap Sort

- Maths/PrimeCheck.py
Added a new Algorithm to check if a number is prime or not. It takes one + half the amount of iterations of the square root of the number. Returns Boolean value.
> Added a new Algorithm to check if a number is prime or not.

- .lgtm.yml
Fixes: #492
Tests for the issues raised in #485, #486, and #500
Ready for review. @harshildarji @ParthS007 @AlexDvorak
> LGTM: Start testing on Python 3 instead of Python 2

- maths/PrimeCheck.py
As the for-loop was looping by two numbers, it would stop at 1 number less than the root of prime squares, resulting it in incorrectly classifying the squares as prime numbers. Incrementing the loop ensures the next number is also considered resulting in accurate classification.
> Updated primecheck.py to accurately classify squares of prime numbers as composite numbers.

- data_structures/heap/heap.py
Fix for dividing by float:
python3 error: TypeError: 'float' object cannot be interpreted as an integer 
python2 error: TypeError: range() integer start argument expected, got float.
> fix division by float issue in range heap.py

- Maths/abs.py
- Maths/absMax.py
- Maths/absMin.py
absmax.py and absmin.py bugs fixed. I think absmax.py and absmin.py, are the Numbers with the max output absolute value and the min output absolute value.please check pull request #623.And  my version output example : absMax.py【a = [-13, 2, -11, -12] print(absMax(a)) # = -13】， this absMax print -13 ; absMin.py【 a = [-3,-1,2,-11] print(absMin(a)) # = -1】， this absMin print -1 . please check it.
> absMax.py and absMin.py bugs fixed.just make it better.

- project_euler/problem_12/sol1.py
although this script outputs the correct answer for the project Euler task,  `count_divisors(4)` returns 4 which is not correct. The reason is for prefect squares, its square root get counted twice, Note that for my simple hack, precision is lost once your numbers get truly large due to float point operations begin limited in precision.
> fix small error in project Euler problem 12 sol1.py

- data_structures/stacks/balanced_parentheses.py
Fixed #620 and added more examples.
> Balanced parentheses fix

- data_structures/linked_list/swapNodes.py
I am adding a program to swap two nodes in a Linked list
> Adding a program for swap nodes in linkedlist

- strings/manacher.py
manacher's algorithm to find palindromic string in linear time complexity
> manacher's algorithm to find palindromic string

- searches/test_tabu_search.py
Hello,
This fixes several `assertEquals()` for `assertEqual()` in tests.
> Fix use of deprecated assertEquals() in tests

- ciphers/rsa_cipher.py
- ciphers/transposition_cipher_encrypt_decrypt_file.py
- file_transfer_protocol/ftp_client_server.py
- file_transfer_protocol/ftp_send_receive.py
- hashes/sha1.py
- other/anagrams.py
- other/detecting_english_programmatically.py
- searches/tabu_search.py
- sorts/external-sort.py
- strings/min_cost_string_conversion.py
Use the `with` context manager to prevent resource leaks.
> Fix ResourceWarning: unclosed file

- digital_image_processing/filters/median_filter.py
Create digital image processing folder, and add median filter algorithm in filters folder.
Other filters will be added later.
> Add median filter algorithm

- Maths/average.py
- Maths/avrage.py
- Maths/find_lcm.py
- ciphers/base64_cipher.py
calculate and print the avrage of number list.
> Editing base64, Adding average file, Editing find_lcm

- traversals/binary_tree_traversals.py
Add iteration version for pre-order, in-order and post-order
> Add iteration version for Binary Tree Traverse

- sorts/radix_sort.py
Remove useless variable, and use `placement` as a loop variable to fix  #336  .
> Fix sorts/radix_sort

- maths/newton_raphson.py
Implemented Newton-Raphson method using pure python. Third party library is used only for visualizing error variation with each iteration.
> Implementation of Newton-Raphson method

- project_euler/problem_08/sol1.py
small off by one error. Boundary condition: if` len(number) =13` , we would need to check exactly 1 combination, namely the number itself. However ` for i in range(len(number)-13):` will iterate 0 times.
> Update project Euler problem 8 sol1.py small off by one error

- ciphers/hill_cipher.py
A python class that implements the Hill cipher algorithm.
> Added hill_cipher.py

- Maths/extended_euclidean_algorithm.py
Added the extended euclidean algorithm to the Maths directory.
> Added extended euclidean algorithm

- data_structures/stacks/balanced_parentheses.py
- data_structures/stacks/infix_to_prefix_conversion.py
- data_structures/stacks/postfix_evaluation.py
Fixed issue #620 
Added infix to prefix conversion & Postfix evaluation
> fixed balanced_parentheses, Added infix-prefix & postfix evaluation

- matrix/matrix_multiplication_addition.py
Added functions for matrix transposition, identity, minor, determinant, and inverse.
> More matrix algorithms

- dynamic_programming/bitmask.py
Added Bitmask and DP code for resolving issue #703.
> Bitmasking and DP added

- binary_tree/basic_binary_tree.py
Added a function to perform InOrder traversal on the binary tree.
> InOrder Traversal for Binary Tree

- Graphs/edmonds_karp_Multiple_SourceAndSink.py
Edmonds Karp algorithm is traditionally with only one source and one sink. What do you do if you have multiple sources and sinks? This algorithm is a generalized algorithm that regardless of however many sinks and sources you have, will allow you to use this algorithm. It does this by using the traditional algorithm but adding an artificial source and sink that allows with "infinite" weight.
> Created a generalized algo to edmonds karp

- sorts/quick_sort.py
According to PEP 8 naming conventions, variable in function should be lowercase
> Rename some variables name in quick_sort.py

- searches/binary_search.py
To avoid confusion all 'sorted' to 'ascending sorted' in comments
> update 'sorted' to 'ascending sorted' in comments

- other/sierpinski_triangle.py
http://www.lpb-riannetrujillo.com/blog/python-fractal/ moved to http://www.riannetrujillo.com/blog/python-fractal/
> fix: replaced outdated url

- maths/PrimeCheck.py
Current implementation is buggy and hard to read.
* Negative values were raising a TypeError due to `math.sqrt`
* 1 was considered prime, it is not.
* 2 was considered not prime, it is.
The implementation has been corrected to fix the bugs and to enhance
readability.
A docstring has been added with the definition of a prime number.
A complete test suite has been written, it tests the 10 first primes, a
negative value, 0, 1 and some not prime numbers.
closes #795
> [FIX] maths/PrimeCheck

- compression/huffman.py
Implemented Huffman Coding, taught in courses as a basic compression algorithm.
> Added Huffman Coding Algorithm

- sorts/merge_sort.py
- sorts/merge_sort_fastest.py
Replace
```
def merge_sort(LIST):
start = []
end = []
while len(LIST) > 1:
a = min(LIST)
b = max(LIST)
start.append(a)
end.append(b)
LIST.remove(a)
LIST.remove(b)
if LIST: start.append(LIST[0])
end.reverse()
return (start + end)
```
with
```
def merge_sort(collection):
start, end = [], []
while len(collection) > 1:
min_one, max_one = min(collection), max(collection)
start.append(min_one)
end.append(max_one)
collection.remove(min_one)
collection.remove(max_one)
end.reverse()
return start + collection + end
```
> More elegant coding for merge_sort_fastest

- graphs/check_bipartite_graph_dfs.py
It's similar to check_bipartite_graph_bfs.
> Implement check_bipartite_graph using DFS.

- .travis.yml
- project_euler/problem_17/sol1.py
- project_euler/problem_19/sol1.py
Identity is not the same thing as equality.  We want the latter.
$ __python__
```python
>>> raw = 'ra'
>>> raw += 'w'
>>> raw
'raw'
>>> raw == 'raw'
True
>>> raw is 'raw'
False
>>> 0 == 0.0
True
>>> 0 is 0.0
False
```
[flake8](http://flake8.pycqa.org) testing of https://github.com/TheAlgorithms/Python on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./project_euler/problem_17/sol1.py:25:7: F632 use ==/!= to compare str, bytes, and int literals
if i%100 is not 0:
^
./project_euler/problem_19/sol1.py:33:40: F632 use ==/!= to compare str, bytes, and int literals
if day > days_per_month[month-1] and month is not 2:
^
./project_euler/problem_19/sol1.py:36:21: F632 use ==/!= to compare str, bytes, and int literals
elif day > 29 and month is 2:
^ …
```
> Use ==/!= to compare str, bytes, and int literals

- sorts/bucket_sort.py
Simplify the code make it easy to read.
> Simplify the code

- other/nqueens.py
> Add NQueens backtracking search implementation

- sorts/pigeon_sort.py
Simple algorithm for Pigeon Hole Sort.
I opted to make it the more human-understandable as possible. Also added some simple comments just to tell what's going on inside the code.
It's recommended to see a video of this algorithm before trying to understand it.
> Add Pigeon Hole Sort

- neural_network/convolution_neural_network.py
Hey!
I fixed spelling, coding style in function declaration.
> Fix spelling in neural_network/convolution_neural_network.py

- README.md
This PR adds a suggestion to use gitpod.io for contributing and generally playing around with the algorithms. 
We've developed Gitpod to lower friction for collaboration on GitHub and other code hosting platforms by skipping the local setup, maintenance of such and automating workflows. It's free for open-source.
We could configure Gitpod with a Dockerfile so it preinstalls certain tools or python packages, but it looked like most algorithms worked out of the box so I skipped additional configuration.
> Lower barrier for contributions and learning

- graphs/DFS.py
The old iterative DFS is wrong. The order it explores the graph is not in a DFS way. I think my code is correct.
Reference:
- <https://www.techiedelight.com/depth-first-search/>
- <https://www.geeksforgeeks.org/iterative-depth-first-traversal/>
> Correct the wrong iterative DFS implementation

- ciphers/Atbash.py
@sateslayer and @AnupKumarPanwar your reviews please.
LGTM tests are failing because of the Python syntax error in #425
> Atbash.py: Both raw_input() and unichr() were removed in Python 3

- sorts/Odd-Even_transposition_parallel.py
- sorts/Odd-Even_transposition_single-threaded.py
Here are single and multi-threaded implementations of Odd-Even transposition sort.
It is an O(n) sorting algorithm that performs its swaps simultaneously.
https://en.wikipedia.org/wiki/Odd%E2%80%93even_sort
> Odd-Even Transposition Sort

- graphs/DFS.py
explored set should not append the root/start outside of the while loop because the root/start is already in explored set and stack would be empty after the first pop. The "if v in explored" statement then triggers "continue" then it would exit the loop. As a result, this implementation would always return {'A'}.
> Corrected wrong DFS implementation

- graphs/floyd_warshall.py
I've added comments to make understanding this method a little easier for those that are not familiar.  This should close out #727 .
Other changes:
1. added if __name__ == '__main__' rather than the "# MAIN" comment
2. put in return for distances and vertices.  Previously everything was just printed out, but someone may find it useful to have the algorithm return something.
3. Other PEP8 changes
4.  Added example input and expected output as a check to make sure any future changes will give the same output.
> Add docstring and comments per Issue #727

- other/primelib.py
Since `j` is redefined before it is used, it makes more sense to declare it with the value `None` instead of `1`.
This fixes a [warning from lgtm](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/66c4afbd0f28f9989f35ddbeb5c9263390c5d192/files/other/primelib.py?sort=name&dir=ASC&mode=heatmap)
> Change Declaration of Var 'j' to None

- arithmetic_analysis/lu_decomposition.py
- arithmetic_analysis/newton_method.py
- maths/Hanoi.py
- maths/abs.py
- maths/average.py
- maths/find_lcm.py
- sorts/bucket_sort.py
- sorts/gnome_sort.py
- sorts/tests.py
- sorts/topological_sort.py
- sorts/tree_sort.py
- sorts/wiggle_sort.py
I modified the file to make Pylint happier and make the code more readable.
> Added Whitespace and Docstring

- maths/basic_maths.py
- maths/factorial_python.py
- maths/factorial_recursive.py
- maths/find_lcm.py
- sorts/pancake_sort.py
I edited several files to increase compliance with PyLint, PEP8, etc.
> Improve Formatting and Code Quality

- strings/Boyer_Moore_Search.py
#697, I have added Boyer Moore search function(bad character heuristic). Please review and let me know if any changes are required. Thanks. ;)
> add ons in string directory - Boyer_Moore_Search

- sorts/Odd-Even_transposition_parallel.py
- Removed two unused variables.
- Changed `a` to `_` since the `a` variable is never used.
This addresses [3 alerts from lgtm](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/d55bbcd204dfbd436914a5f9031a6a8fdf22f6f4/files/sorts/Odd-Even_transposition_parallel.py?sort=name&dir=ASC&mode=heatmap).
> Removed Unused Variables

- conversions/decimal_to_binary.py
- conversions/decimal_to_octal.py
- maths/average_median.py
I created:
- A program to calculate the median of a list of numbers.
- A decimal to binary converter.
- A decimal to octal converter.
> Implement Three New Algorithms

- ciphers/caesar_cipher.py
I removed `import sys` because it is not used in the program.
This addresses a [recommendation from lgtm](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/66c4afbd0f28f9989f35ddbeb5c9263390c5d192/files/ciphers/caesar_cipher.py?sort=name&dir=ASC&mode=heatmap)
> Removed Unused `import sys`

- hashes/enigma_machine.py
Enigma machine algorithm simulator added to project.
> Enigma_machine

- maths/newton_raphson.py
`error = abs(f(a))` was declared on line 24 and line 32. It is unnecessary to have in both places.
I removed the second instance since it wastes resources to keep redefining the variable inside the for loop.
This fixes an [issue found by lgtm](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/66c4afbd0f28f9989f35ddbeb5c9263390c5d192/files/maths/newton_raphson.py?sort=name&dir=ASC&mode=heatmap)
> Removed Unnecessary Assignment for 'error' Var

- conversions/decimal_to_hexadecimal.py
I didn't update the directory because I noticed that the other conversion algorithms were not listed
> added decimal to hexadecimal conversion

- .travis.yml
- dynamic_programming/longest_increasing_subsequence_O(nlogn).py
- requirements.txt
Let’s make sure that there is no global code in Python files so that we can run Pytest across the repo.
Ready for review.  This has allowed us to discover and open #983,#984,#985,#986,#987,#988,#989  Once those issues are fixed we can simplify the pytest command in a future pull request. @PatOnTheBack
> Pytest the entire repo

- sorts/bucket_sort.py
Update Bucket Sort time complexity analysis
> Update Bucket Sort time complexity analysis

- dynamic_programming/factorial.py
calculating factorial using memoization added
> adding factorial

- matrix/nth_fibonacci_using_matrix_exponentiation.py
- matrix/nth_fibonnacci_using_matrix_exponentiation.py
- Implemented matrix exponentiation for finding nth fibonnaci.
- Complexity is about O(nlog(n)*8), here 8 is for matrix multiplication of size 2 by 2.
> Added matrix exponentiation approach for finding fibonacci number.

- matrix/rotate_matrix.py
@obelisk0114 Your review please?
> rotate_matrix.py: Add type hints for return values

- README.md
The following badges were added
* Docs
* Python Version
* Contributions
* Hits
> Add badges to the top of README.md

- .travis.yml
- graphs/bfs.py
- maths/volume.py
- other/primelib.py
- project_euler/problem_13/sol1.py
> Travis CI: Add a flake8 test for unused imports

- .travis.yml
- DIRECTORY.md
- scripts/build_directory_md.py
Rewrite __scripts/build_directory_md.py__ for ease of maintenance.
> Rewrite build_directory_md.py

- maths/Lucas_Lehmer_primality_test.py
- maths/lucas_lehmer_primality_test.py
Add Lucas–Lehmer test for Mersenne prime testing.
> Add Lucas_Lehmer_primality_test

- project_euler/problem_10/sol3.py
edit new solution using sieve-of-eratosthenes to solve problem 10 of project Euler
> project_euler/problem_10

- conversions/decimal_to_binary.py
Fixes #1090
bin(num) in decimal_to_binary.py can now convert ZERO and negative decimal numbers to binary. Consistent with built-in python bin(x) function.
> bin(num). convert ZERO and negative decimal numbers to binary.

- maths/zellers_congruence.py
Let me know of any other improvements I can make. :+1: 
```shell
Marvins-MBP:maths marvinmichum$ python3 zellers_congruence.py --help
usage: zellers_congruence.py [-h] date_input
Find out what day of the week nearly any date is or was. Enter date as a
string in the mm-dd-yyyy or mm/dd/yyyy format
positional arguments:
date_input  Date as a string (mm-dd-yyyy or mm/dd/yyyy)
optional arguments:
-h, --help  show this help message and exit
```
```python
>>> import ZellersCongruence as z
>>> z.zeller('10/10/2018')
Your date 10/10/2018, is a Wednesday!
>>> z.zeller('04-23-1991')
Your date 04-23-1991, is a Tuesday!
>>> z.zeller('01-31-1976')
Your date 01-31-1976, is a Saturday!
```
```shell
Marvins-MBP:maths marvinmichum$ python3 zellers_congruence.py -v
Trying:
zeller('01-31-2010')
Expecting: …
```
> Zeller's Congruence Algorithm

- maths/Quadratic Equations(Complexes Numbers)
Created function that solves quadratic equations treating the cases with complexes numbers. Giving an answer with the imaginary unit "i".
> Create Quadratic Equations(Complexes Numbers)

- maths/quadratic_equations_complex_numbers.py
The original file name was `Create Quadratic Equations(Complexes Numbers)`, not only improper filename but also without `.py` extension.
So in this commit, I changed the filename and also removed `from __future__ import print_function` as this repo no longer supports legacy python.
> remove from __future__, propre filename

- .travis.yml
This PR allows us to see which of our files are still fail pytests.  As we fix each file so that it passes pytest, we can remove the custom configuration to simplify our testing script.  This PR replaces #1055 by running each of our currently failing pytests in __allow_failures__ mode so that we can see them fail without failing the entire Travis CI run.
> Travis CI: Run each failing pytest in allow_failures mode

- machine_learning/logistic_regression.py
Removed issue of unused variables.
Referencing issue #1024 regarding the issue of unused variables in logistic_regression
> Infinite loop was fixed.

- digital_image_processing/filters/median_filter.py
- digital_image_processing/test_digital_image_processing.py
All previous corrections from #1111 kept
> Add digital image processing tests

- networking_flow/minimum_cut.py
Also reformatted the code with psf/black.
> Add doctests to networking_flow/minimum_cut.py

- backtracking/sudoku.py
I have added sudoku.py which is a program to solve the famous sudoku puzzle in python. Please review it and suggest improvements/comments, if any.
> Added sudoku solving program in backtracking algorithms

- project_euler/problem_56/sol1.py
> Solution for Problem Euler 56

- dynamic_programming/knapsack.py
Also reformatted parts of the original file.
> ENH: Added a functionality to make it possible to reconstruct an optimal subset for the dynamic programming problem

- boolean_algebra/quine_mc_cluskey.py
>>>compare_string('0010','0110')
'0_10'
>>> is_for_table('__1','011',2)
True
The above doctests were added
> added doctests for compare_string and is_for_table

- traversals/binary_tree_traversals.py
Added a few doctests 
```python
>>> root = TreeNode(1)
>>> tree_node2 = TreeNode(2)
>>> tree_node3 = TreeNode(3)
>>> tree_node4 = TreeNode(4)
>>> tree_node5 = TreeNode(5)
>>> tree_node6 = TreeNode(6)
>>> tree_node7 = TreeNode(7)
>>> root.left, root.right = tree_node2, tree_node3
>>> tree_node2.left, tree_node2.right = tree_node4 , tree_node5
>>> tree_node3.left, tree_node3.right = tree_node6 , tree_node7
>>> pre_order(root)
1 2 4 5 3 6 7 
>>> in_order(root)
4 2 5 1 6 3 7 
>>> post_order(root)
4 5 2 6 7 3 1 
>>> level_order(root)
1 2 3 4 5 6 7 
>>> level_order_actual(root)
1 
2 3 
4 5 6 7 
>>> pre_order_iter(root)
1 2 4 5 3 6 7 
>>> in_order_iter(root)
4 2 5 1 6 3 7 
>>> post_order_iter(root)
4 5 2 6 7 3 1 
```
> Added a few doctests for traversals

- .github/stale.yml
This PR adds stale.yml in .github folder to automatically label issues and PRs which are unresponsive for 14 days and close them after 7 days of inactivity after labeling them.
> add .github/stale.yml

- dynamic_programming/longest_common_subsequence.py
The comparison at line 53 was not checking if (j > 0). Issue #1024
> Fix possible error in longest_common_subsequence.py

- project_euler/problem_551/sol1.py
Hello,
This would be my first contribution, so if there is anything I could have done better, I would greatly appreciate any feedback.
Thanks!
> solution to problem 551 from project euler

- matrix/sherman_morrison.py
I created method to apply Sherman-Morrison formula to Matrix.
Sherman-Morrison formula is important to reduce time complexity on calculating inverse matrix on some special cases. This formula is also used to improve BFGS update performance. For deeper stuffs please look into this documents:
https://en.wikipedia.org/wiki/Sherman%E2%80%93Morrison_formula
https://en.wikipedia.org/wiki/Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm
https://en.wikipedia.org/wiki/Quasi-Newton_method
> Created Sherman Morrison method

- data_structures/heap/binomial_heap.py
Implementing the binomial heap data structure.
Reference: Advanced Data Structures, Peter Brass
> Add Binomial Heap

- matrix/matrix_class.py
This is far from done but just a little project I was working on for fun that I thought would be nice to add to this repo eventually.  I still need to add determinants, cofactors, etc. but I thought it might be good to post this and see if I got any advice / criticisms of things to think or if you guys thought it looked good to keep going the way it is.  I just noticed that you guys are now recommending running Python Black, which I haven't done yet but will get to soon.  Anyway, let me know what you think!
> Added OOP approach to matrices

- matrix/matrix_class.py
@jasper256 Your review please.
> Simplifications to matrix_class.py

- maths/kth_lexicographic_permutation.py
Function that computes the kth lexicographic permtation of 0,1,2,...,n-1 in O(n^2) time
> Add Kth lexicographic permutation

- data_structures/trie/trie.py
Hi, Thank you for this awesome repository. @cclauss kindly review the changes.
> Add delete to trie.py + tests

- data_structures/heap/binomial_heap.py
- divide_and_conquer/convex_hull.py
- matrix/matrix_operation.py
- neural_network/convolution_neural_network.py
- strings/boyer_moore_search.py
#1024 @cclauss 
$ flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
0
> Fix lgtm error display #1024

- maths/matrix_exponentiation.py
Fixes #1180  Added the **matrix_exponentiation.py** file in **maths directory**
> Added Matrix Exponentiation

- data_structures/heap/min_heap.py
I have added MinHeap data structure with decrease key function in O(logn) time. I have also added sample usage at the bottom. 
Please let me know if there are any changes.
> Min head with decrease key functionality

- machine_learning/dbscan/dbscan.ipynb
- machine_learning/dbscan/dbscan.py
Adding the dbscan algorithm in two formats, a jupyter notebook file for the storytelling and a .py file for people that just want to look at the code. The code in both is essentially the same. With a few things different in the .py file for plotting the clusters.
> DBSCAN algorithm

- maths/polynomial_evaluation.py
Added code for evaluating a polynomail f(x) for a value of x.
> maths-polynomial_evalutation

- sorts/pancake_sort.py
- sorts/pigeon_sort.py
Doctests in the following files to be added: ```pigoen_sort.py```, ```pancake_sort.py```
> Add doctests for sorting algorithms

- sorts/bogo_bogo_sort.py
Hi,
Added code for bogobogosort in seperate PR. Thanks for the previous feedback.
Hope this helps!
> added bogobogosort

- maths/softmax.py
Adding the softmax function to the math category.
> adding softmax function

- project_euler/problem_23/sol1.py
This PR adds the solution to the Project Euler's problem 23
> Add problem 23 solution

- project_euler/problem_32/solution.py
This PR adds the solution to the Project Euler's Problem 32
> Add problem 32 solution

- linear_algebra/README.md
Update formatting to better indicate matrix and vector sections
> Update Linear Algebra Readme

- sorts/selection_sort.py
We don't need swap if `least == i`
> optimization

- dynamic_programming/abbreviation.py
- dynamic_programming/fibonacci.py
> Adding missing Doctests 

- maths/polynomial_evaluation.py
Also docstrings compliant with PEP 257 and mypy type hinting
> added horner's method

- linear_algebra/src/lib.py
I have fixed some minor issues in linear_algebra/src/lib.py
> Fixing Some Minor Issues

- maths/find_max_recursion.py
- maths/find_min_recursion.py
Find max and min value using Divide and Conquer algorithms
> Divide and Conquer

- maths/factorial_python.py
- wrapped the algorithm with function;
- add docstring;
- renamed variables / constants.
> update non-recursive factorial

- searches/fibonacci_search.py
added a search methodology in python
> added fibonacci_search.py

- machine_learning/decision_tree.py
Modified the mean_squared_error to be a static method
Created the Test_Decision_Tree class
Consists of two methods
1. **helper_mean_squared_error_test**: This method calculates the mean squared error manually without using numpy. Instead, a for loop is used for the same.
2. **test_one_mean_squared_error**: This method considers a simple test case and compares the results by the helper function and the original mean_squared_error method of Decision_Tree class. This is done using asert
keyword.
Execution:
PyTest installation
```
pip3 install pytest 
```
OR 
```
pip install pytest
```
Test function execution
```
pytest decision_tree.py
```
> Added Pytests for Decission Tree mean_squared_error method

- other/magicdiamondpattern.py
Written a program to print diamond pattern with stars in python 3.7
> adding program to print diamond pattern

- .travis.yml
- maths/hardy_ramanujanalgo.py
> Implementation of Hardy Ramanujan Algorithm in /maths

- sorts/double_sort.py
I have made all the changes requested .
> Double sort (Added with required updates)

- data_structures/linked_list/singly_linked_list.py
Fixes #1397
I have changed the "Head" to "head"(making it more Pythonic) and also "tamp" to "temp"(Better readability) in singly linked list(under data structures)
PS: I'm a newbie at opensource , so if I have done something wrong please do tell. I wish to learn as much as possible
Thanks
> Readability improvements to singly_linked_list.py

- sorts/bubble_sort.py
A timer has been added which calculates the time of execution of a sort , i.e. bubble sort.
> The time complexity of every algorithms make its value 

- other/password_generator.py
Completed alternative_password_generator which properly shuffles the password and also considers the characters that must be in password.
> Added alternative way to generate password in password_generator.py

- strings/aho-corasick.py
Aho - Corasick string matching algorithm, that creates automaton and searches multiple keywords from a string in a linear fashion.
[Aho-Corasick Algorithm Wikipedia](https://en.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm)
> Aho-Corasick String Matching Algorithm

- project_euler/problem_06/sol4.py
- project_euler/problem_20/sol3.py
Added new solutions for problem_06 and problem_20 for project_euler
> Project Euler problems 06, 20

- ciphers/shuffled_shift_cipher.py
a modified shift cipher algorithm with the explanation in the docstrings
> introduced shuffled_shift_cipher.py in /ciphers

- linear_algebra/README.md
- linear_algebra/src/lib.py
- linear_algebra/src/tests.py
Hi.
This is my first pull request so just let me know if there is anything else I should do. I thought the linear algebra class was missing a pretty important aspect of real valued matrices so thought it should be included.
It uses Laplace expansion to find the determinate recursively. It a pretty slow algorithm but it does the trick.
> Added determinate function

- arithmetic_analysis/gaussian_elimination.py
This code implements the Gaussian elimination method for solving linear systems.
- The gaussian elimination function scales the matrix representing the linear system into a triangular matrix.
- The retroactive resolution function, in turn, uses the triangular matrix to find each of the solution's variables from bottom to top.
> Add gaussian_elimination.py for solving linear systems

- ciphers/deterministic_miller_rabin.py
- maths/miller_rabin.py
There's a miller-rabin primality test in the cipher folder, but I figured a deterministic one for "small" numbers would be interesting. Deterministic (meaning True is prime) for n < ~ 3.32 e 24, probabilistic for larger. With Miller Rabin, a False is always composite- no false negatives.
See https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test for details.
> Adding deterministic miller rabin primality test

- project_euler/problem_20/sol4.py
- project_euler/problem_25/sol3.py
Added solution 3 for problem 25.
> added solution 3 for problem_25

- maths/find_max.py
- maths/find_min.py
> rename and add doctest 

- dynamic_programming/max_sub_array.py
More examples and comment description for `max_sub_array.py`.
> Improve doctest and comment for maximum sub-array problem

- neural_network/perceptron.py
additional housekeeping done by fixing missing doc strings, uninformative variable names etc.
> :white_check_mark: added tests for Perceptron in Neural Networks

- maths/average_mode.py
Finds the mode in the input data.
> average_mode.py

- maths/perfect_square.py
> perfect square

- dynamic_programming/longest_increasing_subsequence.py
* Type hint for the algorithm
* Doctests added
> Doctest and typing for longest_increasing_subsequence.py

- .travis.yml
- backtracking/all_combinations.py
- backtracking/all_permutations.py
- backtracking/all_subsequences.py
- backtracking/sum_of_subsets.py
- boolean_algebra/quine_mc_cluskey.py
- ciphers/xor_cipher.py
- compression/peak_signal_to_noise_ratio.py
- data_structures/stacks/infix_to_prefix_conversion.py
- data_structures/stacks/postfix_evaluation.py
- dynamic_programming/rod_cutting.py
- other/magicdiamondpattern.py
- other/nested_brackets.py
- project_euler/problem_27/problem_27_sol1.py
- searches/interpolation_search.py
Run https://github.com/python/cpython/blob/master/Tools/scripts/reindent.py on files that use tabs instead of spaces for indentation.
> Fix indentation contains tabs (flake8 E101,W191)

- strings/word_occurence.py
This PR request is related to an algorithm that counts the occurrences of all the words in a sentence.
> Word Occurence Script Added

- .coveragerc
- .travis.yml
- DIRECTORY.md
- requirements.txt
Also added coverage report in .travis.yml file.
> Add pytest-cov

- fuzzy_logic/fuzzy_operations.py
- machine_learning/polymonial_regression.py
- neural_network/gan.py
- web_programming/crawl_google_results.py
When running tests with pytest, some modules execute code in main scope
and open plots or browser windows, etc.
Moved such code under `if __name__ == "__main__"`.
> Remove code with side effects from main

- data_structures/linked_list/circular_linked_list.py
Adds a definition for a `CircularLinkedList` that provides the following functionality.
> Adds operations for circular linked list

- graphs/bellman_ford.py
* Fix out-of-range error on line 41
* Add a type hint
> Improve bellman_ford.py

- .github/workflows/stale.yml
A GitHub Actions-based alternative to #1158 because no one seems to have the access rights required to turn on https://probot.github.io/apps/stale/ for this repo.  @onlinejudge95
> GitHub Action to mark stale issues and pull requests

- machine_learning/linear_discriminant_analysis.py
I have fixed #1601 issue in this PR
> converting generator object to a list object

- sorts/unknown_sort.py
Fixes: #328
Here the old file merge_sort_fastest is renamed to unknown_sort. Because it is not merge sort algorithm.
Comments are updated accordingly.
This commit fixes issue #328 .
> address merge_soft duplicate files

- sorts/pigeonhole_sort.py
this is an implementation of pigeonhole sorting in python language which has a time complexity of O(n+ range)
> pigeonhole sorting in python

- conversions/decimal_to_octal.py
The return value for large numbers is now not in scientific notation.
> Fixed issue #1368

- digital_image_processing/convert_to_negative.py
- digital_image_processing/test_digital_image_processing.py
Added code to convert a colored image to its negative.
> digital_image_processing/convert_to_negative

- dynamic_programming/coin_change.py
- linear_algebra/src/lib.py
I put some test cases to verify the algorithm.
> adding doctests on coin_change.py and fixed some typos

- graphs/bfs_shortest_path.py
Hi, added docstrings/doctests and a function that returns distance (number of edges) of shortest path. Let me know if further changes needed.
> Add docstr and algorithm to BFS shortest path module 

- maths/combinations.py
- maths/gamma.py
- maths/radians.py
- strings/lower.py
- strings/split.py
- strings/upper.py
Added from python math library combinations,gamma and radian methods. From the python string library split,upper, and lower were added.
> Added to maths and strings

- sorts/recursive_insertion_sort.py
Hey,
Please let me know how this looks. If there are any issues, I'll be sure to change them.
> A recursive insertion sort

- data_structures/linked_list/swap_nodes.py
- sorts/heap_sort.py
> enhance swapping code in link

- project_euler/problem_30/soln.py
Solution for problem 30 of Euler Project
> Solution for problem 30 of Euler Project

- graphs/prim.py
Hi, added a min heap implementation of Prim's MST algorithm with doctests. I also added type hints and formatted some docstrings to include runtime info and a link to a Wikipedia article. Let me know if any further changes needed. Thanks.
> Add prim alg with min heap

- .github/workflows/codespell.yml
- maths/area_under_curve.py
- maths/armstrong_numbers.py
- maths/line_length.py
- maths/numerical_integration.py
Suppress the BINARY FILE warnings.
> codespell --quiet-level=2

- graphics/bezier_curve.py
> Added implementation for Bezier Curve, under a new graphics directory. 

- .github/pull_request_template.md
- CONTRIBUTING.md
Resolves:  #1716 
Closes: #1716 
Fixes: #1716
> Mandates referencing issue in PR

- maths/collatz_sequence.py
- Add more doc tests and type checking to make sure only natural
numbers are used
- Simplified the algorithm slightly
This new version is also between 10-15% faster for really
long sequences
`python -m timeit -s 'from maths.collatz_sequence import collatz_sequence' 'collatz_sequence(989345275647)'` (1348 steps)
Old algorithm: 
> 1000 loops, best of 5: 369 usec per loop
New algorithm: 
> 1000 loops, best of 5: 313 usec per loop
> Improve collatz_sequence algorithm

- machine_learning/random_forest_regressor.py
Added Random Forest Regressor and tested with flake8. Example dataset is Boston house price.
> Added Random Forest Regressor and tested with flake8

- .travis.yml
- ciphers/transposition_cipher.py
- ciphers/xor_cipher.py
- hashes/hamming_code.py
- linear_algebra/src/test_linear_algebra.py
> Travis CI: Don’t allow bare exceptions

- maths/montecarlo.py
- scheduling/first_come_first_served.py
> Fixes black failures

- dynamic_programming/max_sum_contiguous_subsequence.py
- searches/hill_climbing.py
Fixes following LGTM issues
1. [Implementing __eq__](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/ee5e954b9ed82bbe885bf42bbc446c213a43bd4e/files/searches/hill_climbing.py#x2978473143457f06:1)
2. [Multiple definitions](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/ee5e954b9ed82bbe885bf42bbc446c213a43bd4e/files/dynamic_programming/max_sum_contiguous_subsequence.py?sort=name&dir=ASC&mode=heatmap#x5e72d15036130bb6:1)
> Fixes LGTM issues

- ciphers/mixed_keyword_cypher.py
- data_structures/binary_tree/binary_search_tree.py
- graphs/a_star.py
- hashes/hamming_code.py
- linear_algebra/src/polynom-for-points.py
- matrix/matrix_operation.py
Fixes LGTM warnings of variables not being used
> Fixes unused variable errors in LGTM

- data_structures/binary_tree/binary_search_tree.py
- dynamic_programming/optimal_binary_search_tree.py
- hashes/hamming_code.py
- maths/bisection.py
- searches/tabu_search.py
- strings/aho-corasick.py
* Fixes failing `black` checks from #1740  
* Fixes [Testing equality to None](https://lgtm.com/projects/g/TheAlgorithms/Python/alerts?mode=tree&ruleFocus=7900090) alerts on LGTM
> Fixes black failures from Previous PR

- maths/monte_carlo_dice.py
I made a program to find the probability of a sum appearing when throwing dices.
> Add Monte Carlo dice simulation algorithm

- geodesy/lamberts_ellipsoidal_distance.py
Addition of a more accurate algorithm to calculate distances between two points on the Earth's surface. This method treats the Earth as an oblate ellipsoid.
Tests can be cross-referenced [here](https://geographiclib.sourceforge.io/scripts/geod-google.html) - This is a much more precise algorithm than Lambert's but can be used for comparison.
Insert lat1, lon1 lat2, lon2 into the "Inverse" field and "Calculate" to verify tests. s12 value is the geodesic
* [x ] Add an algorithm?
> Implemented geodesy - Lambert's ellipsoidal distance

- maths/monte_carlo.py
extend estimation of area under curve of y=x using monte carlo simulation to any given lower and upper bound.
> extend estimation of area under curve of y=x using monte carlo simulation to any given lower and upper bound

- maths/monte_carlo.py
estimates area under a curve defined by non-negative real-valued continuous function within a continuous interval using monte-carlo
> estimate area under a curve defined by non-negative real-valued continuous function within a continuous interval using monte-carlo

- digital_image_processing/filters/bilateral_filter.py
> Add bilateral filter

- data_structures/linked_list/skip_list.py
> Added SkipList

- maths/relu.py
> add relu function

- .github/workflows/autoblack.yml
- ciphers/rot13.py
- sorts/comb_sort.py
Checkout v2 is too strict for autoblack
> autoblack: actions/checkout@v1  # Use v1, NOT v2

- .travis.yml
- DIRECTORY.md
- maths/pi_monte_carlo_estimation.py
> Travis CI: Fix Travis linter errors

- data_structures/hashing/double_hash.py
- data_structures/hashing/hash_table.py
- data_structures/hashing/hash_table_with_linked_list.py
- data_structures/hashing/quadratic_probing.py
> Fix rehashing function will not call insert_data function

- data_structures/stacks/next_greater_element.py
All recommended changes are included.
> All suggeted changes within additional time limit tests

- data_structures/stacks/next_greater_element.py
- maths/allocation_number.py
> psf/black changes to next_greater_element.py

- strings/check_pangram.py
Just changing the word "panagram" which does not exist to "pangram". https://dictionary.cambridge.org/dictionary/english/pangram
> Fix typo "panagram" -> "pangram"

- CONTRIBUTING.md
- data_structures/linked_list/middle_element_of_linked_list.py
> README.md: sumab() --> sum_ab() for consistancy

- neural_network/perceptron.py
These are ValueErrors, not AttributeErrors.
> Test the exception conditions

- CONTRIBUTING.md
- DIRECTORY.md
We are seeing too many _how-to examples_ for using existing Python packages so we should define what we want algorithm contributions to be.
> CONTRIBUTING.md: What is an Algorithm?

- digital_image_processing/sepia.py
- digital_image_processing/test_digital_image_processing.py
Added sepia tone in digital_image_processing.
> Added sepia tone

- digital_image_processing/dithering/burkes.py
- digital_image_processing/test_digital_image_processing.py
One of dithering algorithm using for converting greyscale image to black and white version. Algorithm uses error diffusion for that.
> Added Burkes dithering algorithm.

- ciphers/a1z26.py
- data_structures/binary_tree/binary_search_tree.py
- digital_image_processing/test_digital_image_processing.py
https://travis-ci.com/github/TheAlgorithms/Python/builds/162930523#L1050
data_structures/binary_tree/binary_search_tree.py:156
/home/travis/build/TheAlgorithms/Python/data_structures/binary_tree/binary_search_tree.py:156: DeprecationWarning: invalid escape sequence \
> Fix invalid escape sequence in binary_search_tree.py

- backtracking/coloring.py
> Graph coloring

- linear_algebra/src/rayleigh_quotient.py
> Changed the deprecated `np.matrix` to `np.ndarray`

- backtracking/hamiltonian_cycle.py
> Hamiltonian Cycle

- machine_learning/support_vector_machines.py
> support_vector_machines.py increase error tolerance to suppress convergence warnings

- data_structures/binary_tree/segment_tree_other.py
enhanced segment tree implementation and more pythonic
> enhanced segment tree implementation and more pythonic

- data_structures/stacks/stack.py
> Check if a item exist in stack or not

- maths/armstrong_numbers.py
> added method for checking armstrong number

- project_euler/problem_26/sol1.py
Adding a solution for Euler Problem 26.
> Solution for Euler Problem 26

- DIRECTORY.md
- maths/armstrong_numbers.py
- project_euler/problem_26/sol1.py
- web_programming/crawl_google_results.py
Try with the search term "pizza" to see why this was done in #1932
> Deal with maps

- data_structures/queue/queue_on_list.py
> change method name from front to get_front

- ciphers/decrypt_caesar_with_chi_squared.py
I have created a new algorithm that decodes ciphertext encoded with the Caesar cipher using the chi-squared test. What the algorithm does is it cycles through every possible key (26 unless another alphabet is specified) and for every key it decodes the message with that key. For every letter in the decoded message, the function first calculates the amount of times the letter should appear in the message (p) using letter frequencies in the English language and the amount of times the letter actually appears in the message (a). It then plugs the two into the chi-squared formula to calculate the margin of error for that key:
```
((a - p)^2)/p
```
The value is then added to the chi-squared total. The key with the lowest total is the most likely key to be the original encryption key.
* …
> Added new algorithm: cracking caesar cipher with the chi-squared test

- sorts/sleepsort.py
> Added sleep-sort

- digital_image_processing/resize/resize.py
- digital_image_processing/test_digital_image_processing.py
Added resizing algorithm: nearest neighbour
> Added Nearest neighbour algorithm

- maths/Kadane's_algorithm.py
- maths/kadanes_algorithm.py
> Kadanes_algorithm

- .travis.yml
- DIRECTORY.md
Turn the screws all the way down.  This allows us to remove ignored tests one-at-a-time to achieve _gradual compliance_ with all flake8 checks.
> Travis CI: Strict flake8

- sorts/iterative_merge_sort.py
> Iterative merge sort implementation

- maths/prime_numbers.py
The old algorithm checked to see if a number, n, was divisible by any number 2 - (n-1), but by pigeon hole principle it's only necessary to check up to sqrt(n). I changed the algorithm so it wouldn't do unnecessary checks.
> improved prime number generator to check only up to sqrt(n) instead of n

- maths/aliquot_sum.py
I added a new algorithm in the maths directory that finds the aliquot sum of a number.
Algorithm explanation: https://en.wikipedia.org/wiki/Aliquot_sum
* [N/A] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.
> Added file aliquot_sum.py

- sorts/strand_sort.py
I didn't find strand sort (https://en.wikipedia.org/wiki/Strand_sort) implemenation so here it is.
> Added strand sort

- ciphers/hill_cipher.py
Added doctests to the hill cipher algorithm and added type hints. This addresses the issue the #1788 . 
There was a previous attemp #1862 to fix the issue but it wasn't merged.
> Add tests and type hints to hill cipher

- DIRECTORY.md
- ciphers/hill_cipher.py
> hill_cipher.py: gcd() -> greatest_common_divisor()

- maths/area.py
In this program it consists of various area calculation of different geometrical shapes such as (square,rectangle) and many other shapes.
added a new file area.py file
> consists of area of various geometrical shapes

- data_structures/linked_list/singly_linked_list.py
- maths/bailey_borwein_plouffe.py
> Precision must be a nonnegative integer

- DIRECTORY.md
- data_structures/linked_list/singly_linked_list.py
> singly_linked_list.py: psf/black

- ciphers/atbash.py
Added update for atbash cipher:
- doctests,
- type hints
- little performance improvement
> Update atbash cipher (doc, doctest, performance)

- graphs/bidirectional_a_star.py
> Graphs : Bidirectional A*

- graphs/greedy_best_first.py
> Graphs : Greedy Best First

- graphs/bidirectional_a_star.py
- machine_learning/astar.py
- scheduling/shortest_job_first_algorithm.py
- sorts/tree_sort.py
In the current state Bidirectional A* was not working due to an issue in the available vertices check. Could've been highlighted sooner but I only realized it as I added more doctests. Sorry about that.
> Fixes in Bidirectional A*

- sorts/bead_sort.py
Added bead sort aka gravity sort
> Added bead sort

- divide_and_conquer/mergesort.py
Fixes #2023
Merge sort variable name updated along with some comments are added
> Merge sort Update variable names

- .travis.yml
- DIRECTORY.md
Our autoblack GitHub Action will get us to black compliance without forcing each contributor to learn about, install, and use psf/black on every pull request.
> .travis.yml: Revert to using autoblack

- DIRECTORY.md
- graphs/minimum_spanning_tree_boruvka.py
Added Boruvka's Minimum Spanning Tree Algorithm
> added Boruvka's MST algorithm

- DIRECTORY.md
- web_programming/current_weather.py
> current_weather, weather_forecast, weather_onecall

- strings/jaro_winkler.py
Added Jaro Winkler algorithm for measuring similarity between two sequences.
https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance
> Jaro winkler

- DIRECTORY.md
- data_structures/linked_list/circular_linked_list.py
- strings/jaro_winkler.py
Add more len() and delete() tests
> circular_linked_list: Add more len() tests

- sorts/cocktail_shaker_sort.py
Added missing doctests and typehints in sorts/cocktail_shaker_sort.py
> Doctests + typehints in cocktail shaker sort

- sorts/cycle_sort.py
- fix function return value, because it wasn't list
- added algorithm source url
- added doctests
- added typehints
> Refactor cycle_sort

- sorts/cycle_sort.py
Removed boilerplate comments and unused variables
> Removed boilerplate comments and unused variables in cycle_sort

- .travis.yml
- greedy_method/test_knapsack.py
I noticed a little bit spam by Travis notifications so maybe changing them only on fail will be better.
https://github.com/bluzi/travis-buddy#disable-success-message
> Added travis notifications only on fail

- DIRECTORY.md
- strings/remove_duplicate.py
Refactor string/remove_duplicate.py to one liner version.
> Refactor remove duplicates to more pythonic

- greedy_method/greedy_knapsack.py
- greedy_method/test_knapsack.py
@Apoorve73 Your review please.
> calc_profit always returns an int

- maths/perfect_cube.py
To find whether a number is a perfect cube or not.
perfect_cube(27)   ----> True
perfect_cube(4)     ----> False
perfect_cube(8)     ----> True
> created perfect_cube.py

- strings/z_function.py
> Add Z-function algorithm implementation

- backtracking/rat_in_maze.py
implement rat in maze algorithm. #2103
> implement rat in maze algorithm.

- pytest.ini
Add pytest.ini which registers a custom marker "mat_ops" that can be used to filter pytest calls. (`pytest -m mat_ops` will _only_ test these functions; `pytest -m "not mat_ops"` will test _everything but_ these functions)
Fixes #1917.
> Add pytest init file to define custom mark mat_ops

- graphs/bidirectional_breadth_first_search.py
> Graphs : Bidirectional Breadth-First Search

- dynamic_programming/max_non_adjacent_sum.py
> Added maximum non-adjacent sum

- DIRECTORY.md
- graphs/connected_components.py
Find out connected components for given graph. 
* Add an algorithm?
* I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* This pull request is all my own work -- I have not plagiarized.
* I know that pull requests will not be merged if they fail the automated tests.
* This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* All new Python files are placed inside an existing directory.
* All filenames are in all lowercase characters with no spaces or dashes.
* All functions and variable names follow Python naming conventions.
* All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* All functions have …
> Implement connected components algorithm for graphs

- DIRECTORY.md
- graphs/strongly_connected_components.py
Algorithm for finding out strongly connected components in a graph
* Add an algorithm?
* I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* This pull request is all my own work -- I have not plagiarized.
* I know that pull requests will not be merged if they fail the automated tests.
* This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* All new Python files are placed inside an existing directory.
* All filenames are in all lowercase characters with no spaces or dashes.
* All functions and variable names follow Python naming conventions.
* All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* All functions …
> Strongly connected components

- DIRECTORY.md
- strings/prefix_function.py
Prefix function implementation, another usage of knuth-morris-pratt algorithm
* Add an algorithm?
* I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* This pull request is all my own work -- I have not plagiarized.
* I know that pull requests will not be merged if they fail the automated tests.
* This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* All new Python files are placed inside an existing directory.
* All filenames are in all lowercase characters with no spaces or dashes.
* All functions and variable names follow Python naming conventions.
* All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* …
> Implement prefix function, knuth-morris-pratt another usage

- compression/lempel_ziv.py
- compression/lempel_ziv_decompress.py
* Implemented lempel-ziv-welch  compression/decompression algorithm
> Add lempel ziv compression

- backtracking/knight_tour.py
> Added (Open) Knight Tour Algorithm

- machine_learning/k_means_clust.py
Add nice feature to convert Dataframe with clustering number in it to excel style format. It is easily readable and also has a lot of features in it to navigate through data.(like mean, mean_with_zero, median, max, min and etc.)
> add visualization of k means clustering as excel format

- backtracking/knight_tour.py
- dynamic_programming/max_non_adjacent_sum.py
- hashes/hamming_code.py
> hamming_code.py: Reduce McCabe code complexity

- other/markov_chain.py
> Added Markov Chain

- DIRECTORY.md
- other/markov_chain.py
- sorts/radix_sort.py
> Add doctests to radix_sort()

- sorts/odd_even_transposition_single_threaded.py
* typehints
* changed variable names
* changed function name
> Refactor odd_even_transposition_single_threaded

- other/lru_cache.py
> Added LRU Cache

- other/lfu_cache.py
> Added LFU Cache

- searches/double_linear_search.py
> double_linear_search algorithm

- graphs/gale_shapley_bigraph.py
Implementation of a Nobel prize-winning algorithm that determines a stable matching in a bipartite graph.
> Gale Shapley Algorithm

- .github/workflows/autoblack.yml
- .github/workflows/codespell.yml
- dynamic_programming/max_non_adjacent_sum.py
- dynamic_programming/minimum_cost_path.py
- graphs/connected_components.py
- machine_learning/k_means_clust.py
> isort --profile black --recursive .

- graphs/directed_and_undirected_(weighted)_graph.py
1. Simplify imports
2. __ is not a valid variable name for a variable that is referred to multiple times.
> Numerous fixes to directed_and_undirected_(weighted)_graph.py

- matrix/matrix_operation.py
> enhance the ability of add

- graphs/breadth_first_search_shortest_path.py
> Fix typo: Adjancent -> Adjacent

- genetic_algorithm/basic_string.py
> Add a missing "genetic algorithm" folder with a basic algorithm inside

- machine_learning/data_transformations.py
* [] Fix a bug or typo in an existing algorithm?
* [] Documentation change?
> Added Normalization and Standardization Algorithms

- scheduling/round_robin.py
- web_programming/daily_horoscope.py
> added daily horoscope scrapper script

- maths/binomial_distribution.py
Added a binomial distribution algorithm
(also added in the same file a factorial function that is being used
by the binomial distribution function)
> Added a binomial distribution formula calculator algorithm

- sorts/merge_insertion_sort.py
Wikipedia URL
https://en.wikipedia.org/wiki/Merge-insertion_sort
I did black and flake 8 process.
> Add merge insertion sort

- maths/area.py
fix flake8 syntax errors;
fix doctests;
> update variable names for consistency using standard formula terms;

- conversions/temperature_conversions.py
> add Rankine scale

- conversions/temperature_conversions.py
> added tests

- maths/number_of_digits.py
`Fixes: #2220 `
I have added 2 methods for <code>[maths/number_of_digits.py](https://github.com/TheAlgorithms/Python/blob/master/maths/number_of_digits.py)</code>:
1. <code>num_digits2()</code>: Also an O(n) algorithm approach.
2. <code>num_digits_fast()</code>: An O(1) algorithm for counting the number of digits
closes #2220
> Updated maths/number_of_digits.py

- arithmetic_analysis/bisection.py
> added type hints and doctests to arithmetic_analysis/bisection.py

- maths/area.py
> remove function overhead

- maths/perfect_number.py
This python program will check whether a number is **a Perfect number or not**.
> Added Python Program to Check Perfect Number

- maths/gaussian.py
I have added the parenthesis around the 2*sigma^2 term.
> Correcting the Gaussian Formula

- graphs/karger.py
I added an implementation of Karger's algorithm for partitioning a graph, as described here:
https://en.wikipedia.org/wiki/Karger%27s_algorithm
(It doesn't solve any issues)
> Karger's Algorithm

- arithmetic_analysis/intersection.py
> added type hints and doctests to arithmetic_analysis/intersection.py

- arithmetic_analysis/newton_method.py
Continuing #2128
Also changed some variable names, made them more descriptive.
> added type hints and doctests to arithmetic_analysis/newton_method.py

- arithmetic_analysis/lu_decomposition.py
- arithmetic_analysis/newton_method.py
Fixes #2257  I fixed the Bug in the arithmetic_analysis/lu_decomposition.py file.
**The Problem was:**
It seemed that the person who developed the algorithm had forgotten that range(i) will return [0, ... ,i-1]
Because of that the algorithm wasn't working properly, but  now it calculates correctly.
> Fixed bug with incorrect LU decomposition

- data_structures/linked_list/doubly_linked_list.py
> Fix doubly linked list algorithm

- other/scoring_algorithm.py
This is an algorithm which works based on a range based percentual proximity scoring principle. Initially I developed it for a personal project, however later I found out it is a form of Newton's method used in statistics to solve maximum likelihood equations numerically.
- code pythonization
- multiple improvements
- passed doctest
- passed flake8 test
> Procentual proximity scoring algorithm implemented

- maths/least_common_multiple.py
#2268
lowest_common_multiple_slow(): 105.55078284300001
lowest_common_multiple_fast(): 0.569782399999994
> More efficient least common multiple.

- graphs/karger.py
- other/scoring_algorithm.py
- requirements.txt
- web_programming/world_covid19_stats.py
> requirements.txt: Unpin numpy

- data_structures/binary_tree/basic_binary_tree.py
Adding static typing to basic_binary_tree.py towards issue #2128. If my changes are correct, I'll work on changes to more files
> adding static type checking to basic_binary_tree.py

- DIRECTORY.md
- conversions/temperature_conversions.py
- graphs/minimum_spanning_tree_kruskal2.py
- linear_algebra/src/test_linear_algebra.py
- sorts/merge_insertion_sort.py
- web_programming/daily_horoscope.py
> Added Kruskal's Algorithm (more organized than the one present)

- data_structures/stacks/dijkstras_two_stack_algorithm.py
> Created Dijkstra's Two Stack Algorithm

- .travis.yml
- matrix/matrix_operation.py
https://howchoo.com/g/mtblodnjzjc/how-to-measure-unit-test-execution-times-in-pytest helps us to find the individual tests that are slowing down our Travis CI checks.
```
============================= slowest 10 durations =============================
36.16s call     project_euler/problem_34/sol1.py::problem_34.sol1.compute
20.02s call     sorts/sleep_sort.py::sleep_sort.sleep_sort
5.86s call     project_euler/problem_43/sol1.py::problem_43.sol1.compute_sum
5.82s call     graphs/bidirectional_breadth_first_search.py::bidirectional_breadth_first_search.BreadthFirstSearch
5.04s call     project_euler/problem_27/problem_27_sol1.py::problem_27_sol1.solution
4.90s call     project_euler/problem_44/sol1.py::problem_44.sol1.compute_num
4.70s call …
```
> Travis CI: Identify our ten slowest pytests

- maths/perfect_square.py
> Perfect square using binary search

- other/triplet_sum.py
> Created triplet_sum in Python/other

- maths/prime_check.py
> Added type hints and doctest for maths/prime_check.

- machine_learning/word_frequency_functions.py
Added inverse document frequency smooth
> added idf-smooth

- data_structures/linked_list/circular_linked_list.py
* [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
> changed a typo

- graphs/depth_first_search.py
- The algorithm was passing tests but was exploring the vertices in a breadth-first approach even though it was using a stack.
- I can add an issue to implement a test for this in the future since the current test only checks the final output but not the search method itself.
> Fix Non Recursive Depth First Search

- file_transfer/send_file.py
- file_transfer/tests/test_send_file.py
- requirements.txt
I added tests for improving coverage as mentioned in #2128
> file-transfer: writing tests and ensuring that all is going well

- ciphers/enigma_machine2.py
- graphs/directed_and_undirected_(weighted)_graph.py
- graphs/minimum_spanning_tree_boruvka.py
- maths/chudnovsky_algorithm.py
- other/triplet_sum.py
- scheduling/shortest_job_first.py
fixes minor issues : variables assigned to themselves, for - else without any break, redundant redefinitions ...
> Fix some warnings from LGTM

- DIRECTORY.md
- data_structures/stacks/stack.py
> Updated Stack

- backtracking/hamiltonian_cycle.py
- backtracking/rat_in_maze.py
- boolean_algebra/quine_mc_cluskey.py
- cellular_automata/one_dimensional.py
I've been correcting some spelling in docstrings and applying PEP8 autoformatting to scripts i read. I didn't make a single PR per script as the review should be pretty straightforward from reading the diffs, and i didn't change much per file.
> Docstrings and formatting improvements

- project_euler/problem_06/sol1.py
- project_euler/problem_06/sol2.py
- project_euler/problem_06/sol3.py
- project_euler/problem_06/sol4.py
- project_euler/problem_06/test_solutions.py
> Updated problem_06 in Project Euler

- linear_algebra/src/polynom-for-points.py
> Added static type checking to polynom-for-points.py towards issue #2128

- strings/can_string_be_rearranged_as_palindrome.py
- strings/check_if_string_can_be_converted_to_palindrome.py
> Added a function that checks if given string can be rearranged to form a palindrome.

- DIRECTORY.md
- project_euler/problem_09/sol1.py
- project_euler/problem_09/sol3.py
- strings/can_string_be_rearranged_as_palindrome.py
> Optimization problem_10 in project_euler

- .travis.yml
As discussed in #2439 
Dividing Travis CI test into two jobs:
- First job will be testing everything except for the `project_euler` directory
- Second job will only run `pytest` on `project_euler` directory
**NOTE:** Before merging please tell me so that I can remove the `branches` section from `.travis.yml` file as that was done only for testing for which the results are here: https://travis-ci.org/github/dhruvmanila/Python/builds/729560689
**Extra:**
There's another error which I also wrote about in #2439 comment and I will paste it here:
The way `mypy` finds the python files are a bit tricky. In the Travis test, `mypy` isn't going inside the project_euler directory because there's no `__init__.py` file in it. We need to have the `__init__.py` file in every directory and subdirectory to …
> Config Travis CI for two jobs

- other/two_sum.py
> Add Python type hints and doctests to other/two_sum.py

- bit_manipulation/binary_and_operator.py
- bit_manipulation/binary_xor_operator.py
> Added binary_xor_operator.py and binary_and_operator.py

- bit_manipulation/binary_and_operator.py
- bit_manipulation/binary_xor_operator.py
- strings/reverse_words.py
> Fixed reverse words algorithm

- bit_manipulation/binary_and_operator.py
- bit_manipulation/binary_xor_operator.py
- strings/remove_duplicate.py
> Fixed remove duplicate

- project_euler/problem_54/sol1.py
Adding `solution()` function for problem 54 of Project Euler for the upcoming addition of solution testing.
> Add solution() for problem 54 of Project Euler

- DIRECTORY.md
- data_structures/linked_list/singly_linked_list.py
> Updated singly_linked_list

- backtracking/minimax.py
- data_structures/linked_list/singly_linked_list.py
> Fixed linked list bug

- bit_manipulation/binary_and_operator.py
- bit_manipulation/binary_xor_operator.py
- strings/lower.py
- strings/upper.py
> Updated lower and upper

- DIRECTORY.md
- data_structures/linked_list/circular_linked_list.py
> Updated circular_linked_list

- DIRECTORY.md
- bit_manipulation/binary_and_operator.py
- bit_manipulation/binary_xor_operator.py
- strings/check_pangram.py
> Optimization for pangram string

- arithmetic_analysis/newton_method.py
Small fix to arithmetic_analysis/newton_method.py
When you `raise` inside an `except` block you will get two traceback.
```python
>>> try:
...     a = 1/0
... except ZeroDivisionError:
...     raise ZeroDivisionError("Not possible")
...
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 4, in <module>
ZeroDivisionError: Not possible
```
Why? the except block is used to handle the exceptions, if you want to raise an exception inside it you need to use the from clause like so:
```python
>>> try:
...     a = 1/0
... except ZeroDivisionError:
...     raise ZeroDivisionError("Not possible") from None
...
Traceback …
```
> Small fix: arithmetic_analysis/newton_method.py

- .pre-commit-config.yaml
- requirements.txt
As mentioned in https://github.com/TheAlgorithms/Python/pull/2509#issuecomment-700778237
> Add pre-commit hook for TheAlgorithms/Python

- strings/min_cost_string_conversion.py
Added static type checking to min_cost_string_conversion.py towards issue #2128.
> added type hints to strings/min_cost_string_conversion.py

- sorts/bubble_sort.py
> Test using random input

- digital_image_processing/change_contrast.py
That PR fixs Pillow's deprecations warning for `digital_image_processing/test_digital_image_processing.py`
> Fix PIL DeprecationWarnings in pytest output

- maths/allocation_number.py
> Fixed allocation_number

- data_structures/linked_list/print_reverse.py
Update `make_linked_list` helper to use a generator expression instead of 
slicing the original `elements_list` to avoid creating a temporary list
to provide an example that works in O(1) space and O(n) time complexity.
This change is on [L46](https://github.com/TheAlgorithms/Python/pull/2792/files#diff-36ddde92b9f9d5f465b51b42a0ff4109R46).
I've also added doctests to this file to add test coverage for 
expected behaviour and edge cases. When adding the tests, I also
added an additional type check in `print_reverse` [L58](https://github.com/TheAlgorithms/Python/pull/2792/files#diff-36ddde92b9f9d5f465b51b42a0ff4109R58) as I discovered
the function would break when providing an argument that is not a
`Node` instance.
I've checked off "Fix a bug or typo in an existing algorithm" as it 
seems …
> Hacktoberfest: Update Linked List - `print_reverse` method

- searches/ternary_search.py
This PR adds type hints according to issue #2128.
> Add type hints for searches/ternary_search.py

- project_euler/problem_01/sol1.py
- project_euler/problem_01/sol2.py
- project_euler/problem_01/sol3.py
- project_euler/problem_01/sol4.py
- project_euler/problem_01/sol5.py
- project_euler/problem_01/sol6.py
- project_euler/problem_01/sol7.py
> Hacktoberfest 2020: Add typehints and default argument for project_euler/problem_01

- project_euler/problem_120/sol1.py
Added a solution to the Project Euler 120 - Square remainders
> Hactoberfest - Added a solution to Project Euler 120

- DIRECTORY.md
- strings/aho_corasick.py
- strings/boyer_moore_search.py
- strings/knuth_morris_pratt.py
- strings/levenshtein_distance.py
- strings/manacher.py
- strings/rabin_karp.py
This PR adds type hints into strings/ folder.
Related to issue #2128 
* [] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
> Add type hints for "strings" folder

- project_euler/problem_10/sol1.py
- project_euler/problem_10/sol2.py
- project_euler/problem_10/sol3.py
Style improvements for Project Euler Problem 10
- Rename the main solution functions to solution.
- Rename prime chec functions to is_prime.
- Add default args, typehints, expand variable names.
Related to https://github.com/TheAlgorithms/Python/issues/2786
> Project Euler Problem 10: style improvements

- project_euler/problem_25/sol1.py
- project_euler/problem_25/sol2.py
- project_euler/problem_25/sol3.py
> Hacktoberfest 2020 - Add typehints and default input for project_euler/problem_25

- maths/extended_euclidean_algorithm.py
> math/extended_euclidean_algorithm: add doctests and support for negative numbers

- project_euler/problem_20/sol1.py
- project_euler/problem_20/sol2.py
- project_euler/problem_20/sol3.py
- project_euler/problem_20/sol4.py
- Improved variable names
- Added type hints
- Added default argument values for validate_solutions script
> Add default args and type hints for Project Euler problem 20

- other/doomsday.py
Added a doomsday algorithm implementation in python.
> Add doomsday algorithm

- project_euler/problem_28/sol1.py
In reference to Issue #2786 
* Add default arguments
* Add typehints
* Rename solution function for Project Euler Problem 28
> Update code style for Project Euler Problem 28

- project_euler/problem_76/sol1.py
Signed-off-by: joan.rosellr <joan.rosellr@gmail.com>
> Address #2786 - Fix code style in Project Euler Problem 76 

- searches/simple_binary_search.py
What the title says.
* [ X All functions and variable names follow Python naming conventions.
> Fix: Corrected test. List in test must be ordered.

- project_euler/problem_55/sol1.py
Signed-off-by: joan.rosellr <joan.rosellr@gmail.com>
Adresses #2786 
* Renamed the function _compute_lychrel_numbers_ to _solution_
* Added default arguments to solution
* Updated problem description with the link to the official Project Euler site
* Replaced the f-string in the example call with a direct call to solution
----
> [Project Euler] Fix code style in Problem 55

- project_euler/problem_05/sol1.py
- project_euler/problem_05/sol2.py
- Added type hints
- Added default argument values for validate_solutions script
> Add type hints and default args for Project Euler problem 5

- searches/fibonacci_search.py
- Test lists were not ordered, this is required for Fibonacci search
- Place documentation of function inside function
- Create multiple different tests including, float, char and negatives
- Add type hints in line with #2128
> Fix: Multiple errors in fibonacci search.

- project_euler/problem_08/sol1.py
- project_euler/problem_08/sol2.py
- project_euler/problem_08/sol3.py
* Add default argument values
* Add type hints
* Expand variable names
* Add doctest or `str_eval`
> Add style improvements for Project Euler problem 8

- project_euler/problem_07/sol1.py
- project_euler/problem_07/sol2.py
- project_euler/problem_07/sol3.py
- Add default argument values
- Add type hints
- Change one letter variable names to a more descriptive one
- Add doctest for `solution()`
> Add default args and type hints for Project Euler problem 7

- project_euler/problem_41/sol1.py
Addresses #2786 
* Improved the problem description with a link
* Added solution function that calls the old function.
* Fixed some doctests, their use was inconsistent with the functions they tested
I have some questions @dhruvmanila :
1. Is it correct to use an assignment inside an f-string? PyCharm is complaining and I can't execute the tests with the current solution call, but I'm leaving it as I found it in the original file.
2. There is one test case (with n = 7) that is cumbersome to put in a doctest, as the call generates a huge list that wraps around many lines, I have left it out and tested directly the solution output, which passes the test case. Should I leave it as it was and undo the changes?
----
> [Project Euler] Fix code style in Problem 41

- project_euler/problem_09/sol1.py
- project_euler/problem_09/sol2.py
- project_euler/problem_09/sol3.py
* Add default argument value to `sol2.py`
* Add type hints
* Expand variable names
> [Project Euler] Add style improvements to problem 9

- DIRECTORY.md
- graphs/minimum_spanning_tree_kruskal.py
- graphs/tests/test_min_spanning_tree_kruskal.py
- searches/simple_binary_search.py
And also to increase the coverage as stated in #2128
> graphs/kruskal: add a test case to verify the correctness, fix styles

- project_euler/problem_39/sol1.py
Related to #2786
* Added solution function.
* Improve type hinting.
> Hacktoberfest 2020 - coding style for project_euler problem 39

- project_euler/problem_14/sol1.py
- project_euler/problem_14/sol2.py
Continuing #2786
- Added type hints
- Added default argument values for validate_solutions script
- Refactored the code
> [Project Euler] Added type hints and refactored the code a bit for Problem 14

- project_euler/problem_35/sol1.py
- project_euler/problem_36/sol1.py
Add project url. Add default argument values, typehints and doctests
Related: #2786
> Hacktoberfest 2020 - coding style changes for project_euler problem 36 and 35

- project_euler/problem_15/sol1.py
- project_euler/problem_34/sol1.py
> Changes functions name, add type hints and default args to problems 15 and 34

- other/max_sum_sliding_window.py
> Created max_sum_sliding_window in Python/other

- project_euler/problem_125/sol1.py
Name: Palindromic sums
The palindromic number 595 is interesting because it can be written as the sum of consecutive squares: 6^2 + 7^2 + 8^2 + 9^2 + 10^2 + 11^2 + 12^2.
There are exactly eleven palindromes below one-thousand that can be written as consecutive square sums, and the sum of these palindromes is 4164. Note that 1 = 0^2 + 1^2 has not been included as this problem is concerned with the squares of positive integers.
Find the sum of all the numbers less than 10^8 that are both palindromic and can be written as the sum of consecutive squares.
Reference: [https://projecteuler.net/problem=125](url)
> Added solution for Project Euler problem 125

- project_euler/problem_01/sol1.py
- project_euler/problem_01/sol2.py
- project_euler/problem_01/sol3.py
- project_euler/problem_01/sol4.py
- project_euler/problem_01/sol5.py
- project_euler/problem_01/sol6.py
- project_euler/problem_01/sol7.py
(replacing PR #2893)
* clean up docstrs
* improve coding-style
&nbsp;
Part of Issues: #2786, #2510
> Cleanup Project Euler Problem 01

- DIRECTORY.md
- backtracking/all_subsequences.py
> Added all sub sequence type hints [Hacktober Fest]

- DIRECTORY.md
- graphs/minimum_spanning_tree_prims2.py
> feat: added prim's algorithm v2

- conversions/temperature_conversions.py
- project_euler/problem_80/sol1.py
> Project Euler Problem 80

- .github/CODEOWNERS
Fixes: #3011 
This is the basic structure of the file as mentioned in the issue. All the directories have been separated out to ease up assigning it to the maintainers. We can also assign specific file type or single files as well such as the configuration files like `.travis.yml`, `.pre-commit-config.yml` and so on.
> Add CODEOWNERS file to TheAlgorithms/Python

- project_euler/problem_119/sol1.py
Name: Digit power sum
Problem Statement: The number 512 is interesting because it is equal to the sum of its digits raised to some power: 5 + 1 + 2 = 8, and 83 = 512. Another example of a number with this property is 614656 = 284.
We shall define an to be the nth term of this sequence and insist that a number must contain at least two digits to have a sum.
You are given that a2 = 512 and a10 = 614656.
Find a30
Reference: https://projecteuler.net/problem=119
reference: #2695
> Added solution for Project Euler problem 119

- project_euler/problem_191/sol1.py
> Add solution for Project Euler problem 191

- project_euler/problem_234/sol1.py
Fixes the Project Euler problem 234 by implementing a new working solution that doesn't use any `input()` calls.
This PR closes #3163
> Fixes: #3163 - Add new solution for problem 234

- project_euler/problem_69/sol1.py
- project_euler/problem_69/solution_69.py
For #hacktoberfest 
Added solution to Project Euler 69 for issue #2695
> Added solution to Project Euler 69

- web_programming/co2_emission.py
Added a Python script that fetches CO2 emission data from an API.
> Fetch CO2 emission information

- CONTRIBUTING.md
- DIRECTORY.md
> CONTRIBUTING.md Jupyter files belong in the Jupyter repo.

- ciphers/rail_fence_cipher.py
> Added rail fence cipher

- .travis.yml
- project_euler/validate_solutions.py
This was done only to reduce the message clutter produced by 60
failing tests. As that is fixed, we can produce the traceback in
short form and allow pytest to print the captured error message
output at the end of the test.
I am separating out the solution testing and doctest as validating
the solutions for the current number of solutions present is
taking 2 minutes to run which is purely due to the solutions provided.
> Start running validate_solutions script for Travis CI

- .github/CODEOWNERS
- DIRECTORY.md
> Update CODEOWNERS to add my preferences

- project_euler/problem_51/sol1.py
This pull request adds the Project Euler problem 51
> Hacktoberfest: Add project euler problem 51

- DIRECTORY.md
- quantum/q1.py
- quantum/single_qubit_measure.py
- requirements.txt
Add First Quantum Qiskit Code Tutorial
Fixes https://github.com/TheAlgorithms/Python/issues/2923
> Add First Quantum Qiskit Code Tutorial

- quantum/not_gate.py
- quantum/single_qubit_not_gate.py
> Add Qiskit Quantum NOT Gate Example Code

- .travis.yml
- DIRECTORY.md
I just noticed how long it is taking for Travis CI to run `Project Euler Solution` job and saw this:
- Without the latest change in `validate_solutions`: https://travis-ci.com/github/TheAlgorithms/Python/jobs/398271059#L213
- With the latest change in `validate_solutions`: https://travis-ci.com/github/TheAlgorithms/Python/jobs/398769857#L218
I think that after the [latest change](https://github.com/TheAlgorithms/Python/pull/3253), Travis used `pip install -r requirements.txt` to install `pytest`. This is to test whether that is true or not. If it is then the changes made in this PR should fix that.
> Fix Travis CI slow build on Project Euler Solution job

- DIRECTORY.md
- quantum/not_gate.py
> Fix errors in Quantum algorithm

- DIRECTORY.md
- data_structures/binary_tree/binary_tree_mirror.py
> Added binary tree mirror algorithm

- quantum/quantum_entanglement.py
#2923 
added script to perform quantum entanglement with a simple quantum circuit.
> added script to perform quantum entanglement

- conversions/decimal_to_binary_recursion.py
> Added decimal_to_binary_recursion.py

- .github/workflows/codespell.yml
- DIRECTORY.md
This Action does not use flake8 so do not install it.
> codespell.yml: Remove unused install of flake8

- DIRECTORY.md
- project_euler/problem_62/sol1.py
Adds a solution and explanation for Project Euler 62. Part of issue #2695.
> Project Euler 62 Solution

- project_euler/README.md
To see what it looks like: https://github.com/dhruvmanila/Python/blob/readme-pe/project_euler/README.md
In line with the following comments:
- https://github.com/TheAlgorithms/Python/pull/3215#issuecomment-706837753
- https://github.com/TheAlgorithms/Python/issues/2786#issuecomment-703365779
- https://github.com/TheAlgorithms/Python/issues/2695#issuecomment-703122388
> Update README.md for Project Euler

- project_euler/problem_113/sol1.py
Name : Non-bouncy numbers
Working from left-to-right if no digit is exceeded by the digit to its left it is called an increasing number; for example, 134468.
Similarly if no digit is exceeded by the digit to its right it is called a decreasing number; for example, 66420.
We shall call a positive integer that is neither increasing nor decreasing a "bouncy" number; for example, 155349.
As n increases, the proportion of bouncy numbers below n increases such that there are only 12951 numbers below one-million that are not bouncy and only 277032 non-bouncy numbers below 10^10.
How many numbers below a googol (10^100) are not bouncy?
Reference: [https://projecteuler.net/problem=113](url)
> Added solution for Project Euler problem 113

- .pre-commit-config.yaml
- data_structures/binary_tree/binary_tree_traversals.py
I have added some interesting binary tree traversing methods.
In data_structures/binary_tree repository I have added a new file that includes some interesting methods for traversing a binary tree.
> add binary_tree_traversals.py to data_structures

- .pre-commit-config.yaml
- DIRECTORY.md
We must continue to insist that algorithmic functions can not print() as discussed in CONTRIBUTING.md.
> Revert recent changes to .pre-commit-config.yaml

- DIRECTORY.md
- sorts/quick_sort.py
> Tighten up quicksort()

- project_euler/problem_074/sol1.py
- project_euler/problem_74/sol1.py
Name: Digit factorial chains
The number 145 is well known for the property that the sum of the factorial of its digits is equal to 145:
1! + 4! + 5! = 1 + 24 + 120 = 145
Perhaps less well known is 169, in that it produces the longest chain of numbers that link back to 169; it turns out that there are only three such loops that exist:
169 → 363601 → 1454 → 169
871 → 45361 → 871
872 → 45362 → 872
It is not difficult to prove that EVERY starting number will eventually get stuck in a loop. For example,
69 → 363600 → 1454 → 169 → 363601 (→ 1454)
78 → 45360 → 871 → 45361 (→ 871)
540 → 145 (→ 145)
Starting with 69 produces a chain of five non-repeating terms, but the longest non-repeating chain with a starting number below one million is sixty terms.
How many chains, with a starting number below …
> Added solution for Project Euler problem 74.

- DIRECTORY.md
- graphs/tests/test_min_spanning_tree_prim.py
> BROKEN BUILD: Fix a failing precommit test

- project_euler/problem_174/sol1.py
Counting the number of "hollow" square laminae that can form one, two, three, ... distinct arrangements
We shall define a square lamina to be a square outline with a square "hole" so that the shape possesses vertical and horizontal symmetry.
Given eight tiles it is possible to form a lamina in only one way: 3x3 square with a 1x1 hole in the middle. However, using thirty-two tiles it is possible to form two distinct laminae.
If t represents the number of tiles used, we shall say that t = 8 is type L(1) and t = 32 is type L(2).
Let N(n) be the number of t ≤ 1000000 such that t is type L(n); for example, N(15) = 832.
What is ∑ N(n) for 1 ≤ n ≤ 10?
Reference: [https://projecteuler.net/problem=174](url)
> Added solution for Project Euler problem 174.

- project_euler/problem_091/sol1.py
- project_euler/problem_91/sol1.py
Name: Right triangles with integer coordinates
The points P (x1, y1) and Q (x2, y2) are plotted at integer co-ordinates and are joined to the origin, O(0,0), to form ΔOPQ.
There are exactly fourteen triangles containing a right angle that can be formed when each co-ordinate lies between 0 and 2 inclusive; that is,
0 ≤ x1, y1, x2, y2 ≤ 2.
Given that 0 ≤ x1, y1, x2, y2 ≤ 50, how many right triangles can be formed?
Reference: [https://projecteuler.net/problem=91](url) 
> Added solution for Project Euler problem 91.

- project_euler/problem_075/sol1.py
- project_euler/problem_75/sol1.py
Name: Singular integer right triangles
It turns out that 12 cm is the smallest length of wire that can be bent to form an integer sided right angle triangle in exactly one way, but there are many more examples.
12 cm: (3,4,5)
24 cm: (6,8,10)
30 cm: (5,12,13)
36 cm: (9,12,15)
40 cm: (8,15,17)
48 cm: (12,16,20)
In contrast, some lengths of wire, like 20 cm, cannot be bent to form an integer sided right angle triangle, and other lengths allow more than one solution to be found; for example, using 120 cm it is possible to form exactly three different integer sided right angle triangles.
120 cm: (30,40,50), (20,48,52), (24,45,51)
Given that L is the length of the wire, for how many values of L ≤ 1,500,000 can exactly one integer sided right angle triangle be formed?
Reference: …
> Added solution for Project Euler problem 75.

- data_structures/linked_list/doubly_linked_list_two.py
https://github.com/TheAlgorithms/Python/pull/2573 
the second implementation of the Doubly linked list
> New doubly linkedlist  PR: pull/2573

- project_euler/problem_057/sol1.py
- project_euler/problem_57/sol1.py
This PR addresses issue #2695 and adds a solution to Project Euler Problem 57 - "Square root convergents"
**Created new directory for previously non-existent Project Euler solution**
**Doesn't seem relevant**
> Project Euler 57 - Square root convergents

- .gitattributes
With this set, Windows users will have text files converted from Windows style line endings (\r\n) to Unix style line endings (\n) when they’re added to the repository.
https://www.edwardthomson.com/blog/git_for_windows_line_endings.html
> Create .gitattributes for Cross OS compatibility

- ciphers/caesar_cipher.py
- ciphers/xor_cipher.py
- hashes/sha1.py
> Fixed typo in caesar_cipher.py

- DIRECTORY.md
- quantum/half_adder.py
> Fix the build -- 88 chars per line max.

- ciphers/beaufort_cipher.py
if you like my code, merge it and add the label as `hacktoberfest-accepted`
> create beaufort cipher

- ciphers/mono_alphabetic_ciphers.py
> create monoalphabetic cipher

- quantum/deutsch_jozsa.py
Signed-off-by: Abhishek Jaisingh <abhi2254015@gmail.com>
Implement Deutsch-Jozsa Algorithm In Qiskit
> Implement Deutsch-Jozsa Algorithm In Qiskit

- DIRECTORY.md
- quantum/deutsch_jozsa.py
> Fix broken build: Remove trailing spaces

- web_programming/slack_message.py
> Replace main with __main__

- DIRECTORY.md
- ciphers/simple_substitution_cipher.py
- ciphers/xor_cipher.py
- compression/lempel_ziv.py
- compression/lempel_ziv_decompress.py
- data_structures/binary_tree/segment_tree_other.py
- data_structures/heap/heap.py
- data_structures/linked_list/deque_doubly.py
- graphs/minimum_spanning_tree_boruvka.py
- machine_learning/astar.py
- machine_learning/k_means_clust.py
- maths/entropy.py
- maths/numerical_integration.py
- project_euler/problem_013/sol1.py
- project_euler/problem_018/solution.py
- project_euler/problem_042/solution42.py
- project_euler/problem_049/sol1.py
- project_euler/problem_054/sol1.py
- project_euler/problem_054/test_poker_hand.py
- project_euler/problem_063/sol1.py
- project_euler/problem_067/sol1.py
This PR was created by the following commands:
* `python3 -m pip install --upgrade pyupgrade`
* `pyupgrade --py38-plus **/*.py`
In this Pull Request we have made the following changes:
* Use [pyupgrade](https://github.com/asottile/pyupgrade) to automatically upgrade syntax for Python >= 3.8.
> Pyupgrade to python3.8

- DIRECTORY.md
- data_structures/linked_list/doubly_linked_list.py
> Update doubly linked list

- DIRECTORY.md
- data_structures/stacks/linked_stack.py
> Update Linked Stack

- maths/prime_check.py
Made small improvements and shortened prime_check.py
Shortened overall code and changed some of the comments/docstrings
For issue #3453
> Made small improvements and shortened prime_check.py

- project_euler/problem_038/sol1.py
- project_euler/problem_38/sol1.py
Name: Pandigital multiples
Take the number 192 and multiply it by each of 1, 2, and 3:
192 × 1 = 192
192 × 2 = 384
192 × 3 = 576
By concatenating each product we get the 1 to 9 pandigital, 192384576. We will call 192384576 the concatenated product of 192 and (1,2,3)
The same can be achieved by starting with 9 and multiplying by 1, 2, 3, 4, and 5, giving the pandigital, 918273645, which is the concatenated product of 9 and (1,2,3,4,5).
What is the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1,2, ... , n) where n > 1?
Reference: [https://projecteuler.net/problem=38](url)
> Added solution for Project Euler problem 38.

- graphs/bfs_zero_one_shortest_path.py
Finding the shortest path in 0-1-graph in O(E + V) which is faster than dijkstra.
0-1-graph is the weighted graph with the weights equal to 0 or 1.
Link: https://codeforces.com/blog/entry/22276
> Add 0-1-bfs.

- bit_manipulation/single_bit_manipulation_operations.py
> Add single bit manipulation operations.

- maths/combinations.py
I have made some improvements to combinations.py.
Added:
* A description at the top, which includes a wikipedia link
* Type hints to the combinations function
* Some more doctests, which include 0 and negative numbers
*  A check within the function so the function does not attempt to get factorials of negative numbers
* Some print statements in the main block which show some practical applications of the function
If you would like anything else, or if you don't like the changes, please let me know. Thanks!
> Made improvements to combinations.py

- CONTRIBUTING.md
- DIRECTORY.md
- project_euler/README.md
> Fix Project Euler Readme

- divide_and_conquer/convex_hull.py
~~Since the file didn't contain type hints at all, I didn't add them for this algorithm.~~
Is this file the correct place for the algorithm? It is not a divide and conquer algorithm, but it is a convex_hull algorithm.
> Implement the melkman anlgorithm for computing convex hulls

- sorts/radix_sort.py
I added a doctest to an existing file (radix_sort.py)
> Hacktoberfest: adding doctest to radix_sort.py file

- project_euler/problem_087/sol1.py
- project_euler/problem_87/sol1.py
Name: Prime power triples
The smallest number expressible as the sum of a prime square, prime cube, and prime fourth power is 28. In fact, there are exactly four numbers below fifty that can be expressed in such a way:
28 = 2^2 + 2^3 + 2^4
33 = 3^2 + 2^3 + 2^4
49 = 5^2 + 2^3 + 2^4
47 = 2^2 + 3^3 + 2^4
How many numbers below fifty million can be expressed as the sum of a prime square, prime cube, and prime fourth power?
Reference: [https://projecteuler.net/problem=87](url)
> Added solution for Project Euler problem 87.

- maths/greatest_common_divisor.py
> math/greatest_common_divisor: add support for negative numbers

- DIRECTORY.md
- data_structures/stacks/balanced_parentheses.py
> Balanced parentheses

- DIRECTORY.md
- project_euler/problem_301/sol1.py
- sorts/quick_sort.py
> Added solution to Project Euler problem 301

- DIRECTORY.md
- project_euler/problem_206/sol1.py
Adds a solution and explanation for Project Euler 206. Part of issue #2695 and duplicate of #3042.
> Project Euler 206 Solution

- divide_and_conquer/kth_order_statistic.py
> kth order statistic divide and conquer algorithm

- project_euler/problem_203/sol1.py
Added a solution to Project Euler Problem 203 "Squarefree Binomial Coefficients" [Link](https://projecteuler.net/problem=203).
The solution is based on three main pilars.
1. Calculate the unique coefficients of a Pascal's Triangle of depth `d` .
2. Calculate the prime numbers between `2` and the maximum coefficient `Cmax` using a variant of the Sieve of Eratosthenes [Link](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) and considering that the square of each prime must be less or equal than that `Cmax`. The calculation returns the square of those primes.
3. Calculate all squarefree numbers by decomposing each number `n` into `n = p * p * r` where `p` is a prime number calculated before and `r` is a positive integer. If no `r` can be found for all squared primes, then the number is …
> Added a solution for Project Euler Problem 203 "Squarefree Binomial Coefficients"

- project_euler/problem_064/sol1.py
This PR is for Hacktoberfest. #Hacktoberfest
Added Python solution to [Project Euler Problem 64.](https://projecteuler.net/problem=64)
Added my solution to the [Project Euler Problem 64.](https://projecteuler.net/problem=64)
Added a folder problem_064.
Added __init__.py file.
Added sol1.py file.
Fixes: #3705
> HACKTOBERFEST - Added solution to Euler 64.

- .github/workflows/pre-commit.yml
Add the ability to cache pre-commit workflow to be reused later.
> Cache pre-commit workflow

- project_euler/problem_123/sol1.py
Name: Prime square remainders
Let pn be the nth prime: 2, 3, 5, 7, 11, ..., and
let r be the remainder when (pn−1)^n + (pn+1)^n is divided by pn^2.
For example, when n = 3, p3 = 5, and 43 + 63 = 280 ≡ 5 mod 25.
The least value of n for which the remainder first exceeds 10^9 is 7037.
Find the least value of n for which the remainder first exceeds 10^10.
Reference: https://projecteuler.net/problem=123
reference: #2695
> Added solution for Project Euler problem 123

- strings/swap_case.py
This fixes 3847 - handling of non-ASCII characters in swap_case. 
Output before (buggy):
python3 swap_case.py                     
Please input sentence:äü
ÄäÜü
Output now (correct):
python3 swap_case.py                     
Please input sentence:äü
ÄÜ
=> It's not contained in the commit messages, but in the PR description. I hope this will suffice. Otherwise, I can of course add a dummy commit.
> Fix handling of non ascii characters in swap case (fixes: #3847)

- project_euler/problem_050/sol1.py
- project_euler/problem_50/sol1.py
This pull request adds the solution to Project Euler problem number 50
which can be found at the following url:
https://projecteuler.net/problem=50
> Hacktoberfest: Add project euler problem 50

- .github/workflows/stale.yml
Changed configuration for the stale action:
- Run every hour: The action uses the search API and the limit for making the calls is 30 per hour. The default value for `operations-per-run` for the stale action is also 30. So, it makes sense to run this action every hour.
- Add the number of days before stale and close. ***Open to discussion to reduce the value***
- Add stale and close pr and issue message.
I just noticed that our stale bot was configured to the default values which are 60 days until stale.
> Add more details for the stale bot

- other/davis–putnam–logemann–loveland.py
- other/dpll.py
> DPLL algorithm

- DIRECTORY.md
- conversions/molecular_chemistry.py
> Add molecular_chemistry.py

- DIRECTORY.md
- machine_learning/linear_discriminant_analysis.py
- strings/can_string_be_rearranged_as_palindrome.py
Tracking issue #2128
* [ X All functions and variable names follow Python naming conventions.
Not really know how to create doctests for this kind of input functions.
> Reduce complexity linear_discriminant_analysis.

- quantum/ripple_adder_classic.py
- requirements.txt
Only ripple_adder has doctests because it is the one intended to be used. The separate functions are there for the ease of explanation and understanding
> Add Quantum Full Adder circuit for classical integers

- machine_learning/similarity_search.py
adding similarity_search algorithm in machine_learning
> add similarity_search.py in machine_learning

- maths/sigmoid.py
> Add Maths / Sigmoid Function

- strings/upper.py
fixes: #3807 
This is just a word change in the comments section to make the comments look more readable. No other issues are expected as a part of this change.
> Modified comments on upper.py ,made it more clean

- DIRECTORY.md
- project_euler/problem_074/sol2.py
fixes: #3869 
- Optimize Project Euler's Problem 74's  Solution #2 using caches of factorials and sums of factorials of digits of a number
- Fix typo for Project Euler's Problem 74's  Solution #1 because of which it wasn't running on CI for running solutions
> Fixes: #3869: Optimize CI runtime of Project Euler's Problem 74's Solution 2

- project_euler/problem_188/sol1.py
> Add solution for Project Euler problem 188

- project_euler/problem_129/sol1.py
Name: Repunit divisibility
A number consisting entirely of ones is called a repunit. We shall define R(k) to be a repunit of length k; for example, R(6) = 111111.
Given that n is a positive integer and GCD(n, 10) = 1, it can be shown that there always exists a value, k, for which R(k) is divisible by n, and let A(n) be the least such value of k; for example, A(7) = 6 and A(41) = 5.
The least value of n for which A(n) first exceeds ten is 17.
Find the least value of n for which A(n) first exceeds one-million.
> Added solution for Project Euler problem 129.

- graphs/bfs_shortest_path.py
Updated the code to track visited Nodes with Set data structure instead of Lists to bring down the lookup time in visited  from O(N) to O(1)
as doing O(N) lookup each time in the visited List will become significantly slow when the graph grows
> Changed how the Visited nodes are tracked

- maths/sieve_of_eratosthenes.py
just for completeness of existing code to follow the (now compulsory) requirements of type hints
> math/sieve_of_eratosthenes: add type hints

- ciphers/base16.py
> Improve Base16 Codebase

- divide_and_conquer/max_difference_pair.py
> A divide and conquer method in finding the maximum difference pair

- web_programming/fetch_github_info.py
- web_programming/test_fetch_github_info.py
> Fixes: #3944 authentication error

- .github/stale.yml
- DIRECTORY.md
> Update stalebot to take 5 actions per hour

- data_structures/linked_list/__init__.py
Added a __str__() function to the Linked List class that will print the contents in the Linked List with arrows that point to the next value
see: #3960
> data_structures/linked_list: Adding __str__() function #3960

- CONTRIBUTING.md
Added pre-commit instructions to contributing.md (Most PRs get their tests fail with pre-commit)
fixes: #3887
> Update CONTRIBUTING.md with pre-commit plugin instructions

- DIRECTORY.md
- maths/lucas_series.py
> Fixed LGTM and typehint

- web_programming/instagram_video.py
Download Video and IGTV from Instagram
> Instagram Video and IGTV downloader

- backtracking/all_combinations.py
- backtracking/all_permutations.py
- backtracking/n_queens.py
- backtracking/rat_in_maze.py
- backtracking/sum_of_subsets.py
Fix `mypy` errors made in #2684.
> Fix mypy in #2684

- .github/workflows/build.yml
- .github/workflows/project_euler.yml
- scripts/validate_solutions.py
Messing around with GitHub Actions, trying to see if this is possible:
We will run checks only on the submitted Project Euler solution and not all.
> Validate only submitted Project Euler solution

- blockchain/chinese_remainder_theorem.py
- blockchain/diophantine_equation.py
- blockchain/modular_division.py
> Fix mypy in #3149

- electronics/electric_power.py
Used code from ohms_law algorithm, but now for power calculation
> Electric power

- DIRECTORY.md
- sorts/pigeon_sort.py
> Fix pre-commit error on master

- sorts/bitonic_sort.py
> Update bitonic_sort with type hints, doctest, snake_case names

- dynamic_programming/minimum_steps_to_one.py
> Implemented minimum steps to one using tabulation.

- searches/binary_search.py
Added missing type hints as described in this issue -> #2128
> Chore: Added type hints to searches/binary_search.py

- DIRECTORY.md
- project_euler/problem_085/sol1.py
Project euler problem 85: [Counting Rectangles](https://projecteuler.net/problem=85)
By counting carefully it can be seen that a rectangular grid measuring 3 by 2 contains eighteen rectangles.
Although there exists no rectangular grid that contains exactly two million rectangles, find the area of the grid with the nearest solution.
> Added solution for Project Euler problem 085

- linear_algebra/src/conjugate_gradient.py
This is an implementation of the conjugate gradient method for solving a linear system given an SPD matrix A.
> Initial commit of conjugate gradient method

- DIRECTORY.md
- project_euler/problem_086/sol1.py
Project Euler problem 86: [Cuboid route](https://projecteuler.net/problem=86)
A spider, S, sits in one corner of a cuboid room, measuring 6 by 5 by 3, and a fly, F, sits in the opposite corner. By travelling on the surfaces of the room the shortest "straight line" distance from S to F is 10 and the path is shown on the diagram.
However, there are up to three "shortest" path candidates for any given cuboid and the shortest route doesn't always have integer length.
It can be shown that there are exactly 2060 distinct cuboids, ignoring rotations, with integer dimensions, up to a maximum size of M by M by M, for which the shortest route has integer length when M = 100. This is the least value of M for which the number of solutions first exceeds two thousand; the number of solutions when M = …
> Added solution for Project Euler problem 86

- sorts/shell_sort.py
> Optimization for shell sort

- project_euler/problem_135/sol1.py
> Added first solution to problem 135

- arithmetic_analysis/in_static_equilibrium.py
- arithmetic_analysis/lu_decomposition.py
- arithmetic_analysis/newton_forward_interpolation.py
- arithmetic_analysis/newton_raphson.py
- arithmetic_analysis/secant_method.py
```console
$ mypy --strict arithmetic_analysis/
Success: no issues found in 11 source files
```
> [mypy] Fix type annotations for arithmetic analysis algorithms

- bit_manipulation/binary_and_operator.py
- bit_manipulation/binary_or_operator.py
- bit_manipulation/binary_xor_operator.py
- bit_manipulation/single_bit_manipulation_operations.py
```console
$ mypy --strict bit_manipulation/
Success: no issues found in 7 source files
```
> [mypy] Add/Fix type annotations for bit manipulation algorithms

- scheduling/first_come_first_served.py
- scheduling/round_robin.py
- scheduling/shortest_job_first.py
```
$ mypy --strict scheduling/ --ignore-missing-imports
Success: no issues found in 4 source files
```
> [mypy] Add/fix type annotations for scheduling algorithms

- data_structures/binary_tree/merge_two_binary_trees.py
**Merge two binary trees**
*Problem Description:* Given two binary tree, return the merged tree.
The rule for merging is that if two nodes overlap, then put the value sum of
both nodes to the new value of the merged node. Otherwise, the NOT null node
will be used as the node of the new tree.
> Added code to merge two trees

- machine_learning/similarity_search.py
$ mypy --strict machine_learning/similarity_search.py --ignore-missing-imports
Success: no issues found in 1 source file
> [mypy] Add/fix type annotations for similarity search in machine learning

- boolean_algebra/quine_mc_cluskey.py
> [mypy] Add/fix type annotations for boolean_algebra

- data_structures/binary_tree/binary_search_tree_recursive.py
- data_structures/binary_tree/lazy_segment_tree.py
- data_structures/binary_tree/treap.py
```
$ mypy --strict data_structures/binary_tree/treap.py data_structures/binary_tree/lazy_segment_tree.py data_structures/binary_tree/binary_search_tree_recursive.py 
Success: no issues found in 3 source files
```
> [mypy] Add/fix type annotations for binary trees in data structures

- sorts/odd_even_sort.py
* [x ] Add an algorithm?
* [ x] This pull request is all my own work -- I have not plagiarized.
* [ x] I know that pull requests will not be merged if they fail the automated tests.
* [ x] All filenames are in all lowercase characters with no spaces or dashes.
* [ x] All functions and variable names follow Python naming conventions.
* [ x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ x] All new algorithms have a …
> odd_even_sort.py

- bit_manipulation/count_number_of_one_bits.py
I have added an algorithm which counts the number of one (on bits) bits in a given positive integer.
> add count_number_of_one_bits.py

- sorts/quick_sort_3_partition.py
> Quick sort with lomuto partition

- sorts/quick_sort.py
Adding type annotations for the greater and lesser list types in the algorithm
* [x ] This pull request is all my own work -- I have not plagiarized.
* [x ] I know that pull requests will not be merged if they fail the automated tests.
* [x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x ] All filenames are in all lowercase characters with no spaces or dashes.
* [x ] All functions and variable names follow Python naming conventions.
* [x ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* …
> [mypy] Add/fix type annotations for quick_sort(#4085)

- data_structures/binary_tree/avl_tree.py
```
$ mypy --strict data_structures/binary_tree/avl_tree.py 
Success: no issues found in 1 source file
```
> [mypy] Add/fix type annotations for avl tree in data structures

- ciphers/rsa_cipher.py
- ciphers/rsa_key_generator.py
- compression/burrows_wheeler.py
- data_structures/binary_tree/non_recursive_segment_tree.py
- data_structures/binary_tree/red_black_tree.py
- data_structures/linked_list/deque_doubly.py
- dynamic_programming/climbing_stairs.py
- dynamic_programming/iterating_through_submasks.py
- machine_learning/knn_sklearn.py
- maths/3n_plus_1.py
- maths/quadratic_equations_complex_numbers.py
- matrix/nth_fibonacci_using_matrix_exponentiation.py
- matrix/sherman_morrison.py
- strings/levenshtein_distance.py
> Changes occurences of str.format to f-strings

- bit_manipulation/binary_shifts.py
- bit_manipulation/binary_twos_complement.py
… package
Added binary shifts (left logical, right logical, right arithmetic) and two's complement functions to bit manipulation package. Added both since used 2's complement in the shifts.
> Added binary shifts and twos complement functions to bit manipulation

- sorts/bucket_sort.py
- sorts/cocktail_shaker_sort.py
- sorts/patience_sort.py
- sorts/radix_sort.py
- sorts/recursive_insertion_sort.py
Completion of all mypy errors apart from a stub error. See #4222 for more detail. The errors were four type annotations, and the last was a return statement error found in the cocktail_shaker_sort algorithm which was fixed.
> [mypy]Correction of all errors in the sorts directory

- graphics/bezier_curve.py
> [mypy] Added/fixed type annotations for "graphics\bezier_curve.py"

- graphics/mandelbrot.py
> Add mandelbrot algorithm

- DIRECTORY.md
- project_euler/problem_109/sol1.py
In the game of darts a player throws three darts at a target board which is split into twenty equal sized sections numbered one to twenty.
￼
The score of a dart is determined by the number of the region that the dart lands in. A dart landing outside the red/green outer ring scores zero. The black and cream regions inside this ring represent single scores. However, the red/green outer ring and middle ring score double and treble scores respectively.
At the centre of the board are two concentric circles called the bull region, or bulls-eye. The outer bull is worth 25 points and the inner bull is a double, worth 50 points.
There are many variations of rules but in the most popular game the players will begin with a score 301 or 501 and the first player to reduce their running total to zero …
> Added solution for Project Euler problem 109

- DIRECTORY.md
- project_euler/problem_121/sol1.py
Project Euler 121: [Disc game prize fund](https://projecteuler.net/problem=121)
A bag contains one red disc and one blue disc. In a game of chance a player takes a disc at random and its colour is noted. After each turn the disc is returned to the bag, an extra red disc is added, and another disc is taken at random.
The player pays £1 to play and wins if they have taken more blue discs than red discs at the end of the game.
If the game is played for four turns, the probability of a player winning is exactly 11/120, and so the maximum prize fund the banker should allocate for winning in this game would be £10 before they would expect to incur a loss. Note that any payout will be a whole number of pounds and also includes the original £1 paid to play the game, so in the example given the …
> Problem 121
