TheAlgorithms/Python

- .github/workflows/build.yml
> build.yml: Run mypy --ignore-missing-imports

- cellular_automata/conways_game_of_life.py
- cellular_automata/one_dimensional.py
> [mypy] Fix type annotations for cellular_automata

- .github/workflows/build.yml
- machine_learning/forecasting/run.py
- machine_learning/k_means_clust.py
- machine_learning/word_frequency_functions.py
- neural_network/perceptron.py
- traversals/binary_tree_traversals.py
> [mypy] fix small folders 2

- .github/workflows/build.yml
> mypy: Use a --exclude list

- .github/workflows/build.yml
- .github/workflows/pre-commit.yml
- arithmetic_analysis/gaussian_elimination.py
- arithmetic_analysis/in_static_equilibrium.py
> [mypy] Fix directory arithmetic_analysis

- .github/workflows/build.yml
- ciphers/diffie_hellman.py
- ciphers/hill_cipher.py
- ciphers/mixed_keyword_cypher.py
- ciphers/mono_alphabetic_ciphers.py
- ciphers/morse_code_implementation.py
- ciphers/onepad_cipher.py
- ciphers/playfair_cipher.py
- ciphers/porta_cipher.py
- ciphers/rail_fence_cipher.py
- ciphers/rot13.py
- ciphers/rsa_cipher.py
- ciphers/rsa_factorization.py
- ciphers/shuffled_shift_cipher.py
- ciphers/simple_keyword_cypher.py
- ciphers/simple_substitution_cipher.py
- ciphers/trafid_cipher.py
- ciphers/transposition_cipher.py
- ciphers/transposition_cipher_encrypt_decrypt_file.py
- ciphers/vigenere_cipher.py
- ciphers/xor_cipher.py
Issue: #4052 
```console
❯ mypy --ignore-missing-imports --strict ciphers/
Success: no issues found in 39 source files
```
> fix(mypy): type annotations for cipher algorithms

- .github/workflows/build.yml
- conversions/binary_to_octal.py
- conversions/decimal_to_binary.py
- conversions/decimal_to_hexadecimal.py
- conversions/decimal_to_octal.py
- conversions/prefix_conversions.py
- conversions/weight_conversion.py
> fix(mypy): type annotations for conversions algorithms

- .github/workflows/build.yml
- linear_algebra/src/conjugate_gradient.py
- linear_algebra/src/lib.py
- linear_algebra/src/polynom_for_points.py
- linear_algebra/src/power_iteration.py
- linear_algebra/src/rayleigh_quotient.py
- linear_algebra/src/test_linear_algebra.py
- linear_algebra/src/transformations_2d.py
> fix(mypy): type annotations for linear algebra algorithms

- .github/workflows/build.yml
- mypy.ini
> feat: Add mypy configuration file

- .github/workflows/build.yml
- digital_image_processing/rotation/rotation.py
- mypy.ini
> Mypy fix rotation.py

- mypy.ini
- scripts/validate_filenames.py
- scripts/validate_solutions.py
> Fix mypy scripts

- DIRECTORY.md
- conversions/rgb_hsv_conversion.py
> Add rgb_hsv_conversion.py

- data_structures/binary_tree/binary_tree_traversals.py
> binary_tree_traversals.py: Simplify with dataclasses

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- data_structures/binary_tree/binary_search_tree.py
- data_structures/heap/heap.py
- data_structures/heap/max_heap.py
- data_structures/linked_list/deque_doubly.py
- data_structures/stacks/stack.py
- digital_image_processing/sepia.py
- hashes/md5.py
- machine_learning/linear_discriminant_analysis.py
- machine_learning/linear_regression.py
- maths/monte_carlo_dice.py
- other/least_recently_used.py
Ref:
- https://github.com/psf/black/pull/1740 (New formatting)
- https://github.com/psf/black/releases/tag/21.4b0
> fix(ci): Update pre-commit hooks and apply new black

- strings/check_pangram.py
Fix implementation bug for check_pangram_faster. The original code had a flawed doctest for check_pangram_faster. Took the uppercase characters into consideration
> [Fix bug] Fix check_pangram_faster in check_pangram.py

- data_structures/stacks/evaluate_postfix_notations.py
- data_structures/stacks/linked_stack.py
- data_structures/stacks/stack.py
I have kept it to only 3 files as per guidelines.
> [mypy] Fix type annotations for linked_stack.py, evaluate_postfix_notations.py, stack.py in data structures

- machine_learning/lstm/lstm_prediction.py
- requirements.txt
> Updated name from lstm_prediction.py_tf to lstm_prediction.py and also imported keras

- bit_manipulation/single_bit_manipulation_operations.py
Bit manipulation: get the bit at a given position
> Bit manipulation: get the bit at a given position

- sorts/msd_radix_sort.py
Added implementation for the MSD radix  sort algorithm. The sorting is based on the binary 
representation of the numbers.
> Added implementation for MSD radix sort algorithm based on binary representation

- sorts/recursive_mergesort_array.py
Add a recursive merge sort algorithm that accepts an array as input.
Add a recursive merge sort algorithm that accepts an array as input.
* [x ] Add an algorithm?
* [x ] All filenames are in all lowercase characters with no spaces or dashes.
* [x ] All functions and variable names follow Python naming conventions.
* [ x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x ] All new algorithms have a URL in its comments …
> Add a recursive merge sort algorithm that accepts an array as input.

- maths/armstrong_numbers.py
Armstrong number is not the sum of cube's of number digits, but
the sum of number's digits each raised to the power of the number of digits
Reference: https://en.wikipedia.org/wiki/Narcissistic_number
> Armstrong number definition fix

- CONTRIBUTING.md
* markdown used both `**` and `__` for bold as well as `*` and `_` for italics, changed all to use `*`
* used ` for methods and other code related things rather than bolding
not an algorithms therefore most of the items on this checklist is irrelevant to this pr so I'm just going to check everything off
> markdown consistency

- dynamic_programming/catalan_numbers.py
Excited to make my first contribution to The Algorithms! Catalan numbers are a sequence in mathematics that represent answers to many combinatorics problems. They can be calculated using a recurrence relation and we can use tabulation (similarly to how we can for the Fibonacci sequence). I thought this best fit in the "dynamic_programming" folder given we're using tabulation to compute the sequence.
All work is my own, but I did take a look at the existing [C++ Catalan number algorithm](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/dynamic_programming/catalan_numbers.cpp) and [Python Fibonacci algorithm ](https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/fibonacci.py) for inspiration and best practices. If this is approved, I hope to contribute to …
> Add catalan_numbers.py

- maths/average_mode.py
* Mistake in maths/average_mode.py fixed. The previous solution was to return the
value on the first loop iteration, which is not correct, more than that it
used to delete repeating values, so result's array and check array lost
relation between each other
* Type hint added
> Mistake in maths/average_mode.py fixed.

- maths/armstrong_numbers.py
Add a new algorithm for verify if a number is an Armstrong.
> Add new algorithm for Armstrong numbers

- backtracking/sudoku.py
After reviewing this code, I've noticed that the `is_completed` function is a redundant operation.
Increasing the number of loops required for each step of the sudoku solver. 
This should remove n² operations where n is the width of the grid.
> Remove redundent function in Backtracking Sudoku

- graphs/breadth_first_search.py
- graphs/depth_first_search.py
```bash
$ mypy --ignore-missing-imports graphs/breadth_first_search.py graphs/breadth_first_search_2.py graphs/depth_first_search.py graphs/depth_first_search_2.py
Success: no issues found in 4 source files
```
- Add/fix mypy type annoatation at BFS, DFS algo in graphs
Releated to
> Add/fix mypy type annotations at BFS, DFS in graphs

- DIRECTORY.md
- hashes/luhn.py
Perform Luhn validation on input string
Algorithm:
* Double every other digit starting from 2nd last digit.
* Subtract 9 if number is greater than 9.
* Sum the numbers
https://en.wikipedia.org/wiki/Luhn_algorithm
> Luhn algorithm

- maths/average_mean.py
Added doctests and type hints to average_mean
* Doctests added instead of assert function
* Type hints added
* Function name changed from average to mean to keep consistency
* Wikipedia link added
> Average mean refactor

- graphs/bellman_ford.py
- Add doctest and 
- fix mypy type annotation in bellman ford
related issue #4052
> Add doctest and fix mypy type annotation in bellman ford

- graphs/bfs_shortest_path.py
> Fix mypy error and add more doctest on bfs_shortest_path

- graphs/bfs_zero_one_shortest_path.py
> Fix mypy errors at bfs_zero_one_shortest_path

- graphs/minimum_spanning_tree_prims2.py
> Fix mypy errors at prims_algo_2

- graphs/minimum_spanning_tree_kruskal2.py
> Fix mypy errors at kruskal_2

- DIRECTORY.md
- project_euler/problem_144/sol1.py
In laser physics, a "white cell" is a mirror system that acts as a delay line for the laser beam. The beam enters the cell, bounces around on the mirrors, and eventually works its way back out.
The specific white cell we will be considering is an ellipse with the equation 4x<sup>2</sup> + y<sup>2</sup> = 100
The section corresponding to −0.01 ≤ x ≤ +0.01 at the top is missing, allowing the light to enter and exit through the hole.
The light beam in this problem starts at the point (0.0,10.1) just outside the white cell, and the beam first impacts the mirror at (1.4,-9.6).
Each time the laser beam hits the surface of the ellipse, it follows the usual law of reflection "angle of incidence equals angle of reflection." That is, both the incident and reflected beams make the same angle with …
> Added solution for Project Euler problem 144

- graphs/bidirectional_breadth_first_search.py
> Fix mypy errors at bidirectional_bfs

- compression/huffman.py
This removes lambdas, improves readability and processing time when it finds bitstring to print out.
> Improves readability and processing time

- strings/indian_phone_validator.py
- strings/phone_validator.py
> add phone_validator method

- graphs/bidirectional_a_star.py
Fix mypy errors at bidirectional_a_star
> Fix mypy errors at bidirectional_a_star

- graphs/graph_list.py
> Fix mypy errors at graph_list

- graphs/strongly_connected_components.py
Fix mypy errors at strongly connected component
> Fix mypy errors at strongly connected component

- graphs/gale_shapley_bigraph.py
Fix mypy errors at gale_shapely_bigraph
> Fix mypy errors at gale_shapely_bigraph_algo

- arithmetic_analysis/lu_decomposition.py
fixing LGTM on ```arithmetic_analysis/lu_decomposition.py``` by:
- fixing module ```numpy``` is imported with both 'import' and 'import from'
- commented ```from numpy import ndarray```
- change ```ndarray``` to ```np.ndarray```
> [fixed] module 'numpy' is imported with both 'import' and 'import from'

- graphs/breadth_first_search_shortest_path.py
Fix mypy errors at bfs_shortest_path algo
> Fix mypy errors at bfs_shortest_path algo

- graphs/greedy_best_first.py
Fix mypy errors at greedy best first algo
> Fix mypy errors at greedy best first algo

- graphs/minimum_spanning_tree_kruskal.py
- graphs/tests/test_min_spanning_tree_kruskal.py
Fix mypy errors at mst_kruskal
> Fix mypy errors at mst_kruskal

- maths/double_factorial_recursive.py
The double factorial recursive algorithm was added.
> Adding the double factorial algorithm

- strings/alternative_string_arrange.py
> add alternative_string_arrange method

- maths/check_valid_ip_address.py
Added program: _**check_valid_ip_address**_ for checking valid IP address
> Created check_valid_ip_address.py

- graphs/basic_graphs.py
Refactor graph_initialization at basic_graph.py
> Refactor graph initializations at basic_graph.py

- graphs/multi_heuristic_astar.py
Fix multi heuristic astar algo
> Fix multi heuristic astar algo

- strings/naive_string_search.py
Fixed mypy error for strings/naive_string_search.py
> [mypy] Fix type annotations for strings/naive_string_search.py

- maths/greedy_coin_change.py
- maths/triplet_sum.py
- maths/two_sum.py
> Fix mypy error at maths

- other/date_to_weekday.py
- strings/alternative_string_arrange.py
> add date_to_weekday finder method

- strings/can_string_be_rearranged_as_palindrome.py
- strings/levenshtein_distance.py
- strings/word_occurrence.py
- strings/word_patterns.py
> [mypy] Fix type annotations for strings

- graphs/boruvka.py
> Added Borůvka's algorithm.

- DIRECTORY.md
- graphs/boruvka.py
Python f-strings simplify the code and [should speed up execution](https://www.scivision.dev/python-f-string-speed). 
I don’t know graphs… ~Are `components` and `nodes` the same things or different things?
If they are the same thing, then we should only use one name in the code and drop the other.~
I looked it up.
@srkchowdary2000 Your review, please.
> boruvka.py: A few simplifications and f-strings

- matrix/nth_fibonacci_using_matrix_exponentiation.py
- matrix/spiral_print.py
- other/fischer_yates_shuffle.py
fixed unused variable, and using ``if __name__ == "__main__"``, and imported doctest module for following style code
> [fixed] unused variable, standalone running, import doctest module

- dynamic_programming/integer_partition.py
Fix type annotations for integer_partition.py
> [mypy] Fix type annotations for integer_partition.py

- graphs/eulerian_path_and_circuit_for_undirected_graph.py
- graphs/frequent_pattern_graph_miner.py
- maths/radix2_fft.py
https://docs.python-guide.org/writing/gotchas/
[flake8-bugbear](https://pypi.org/project/flake8-bugbear) ___B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.___
> Avoid mutable default arguments

- other/linear_congruential_generator.py
- quantum/ripple_adder_classic.py
Use linter directive `# noqa: B0008` for these functions because they set a seed value and `BaseBackend` is reused across all calls and `LinearCongruentialGenerator.__init__()` is only called once for each instance.
[flake8-bugbear](https://pypi.org/project/flake8-bugbear) ___B008 Do not perform function calls in argument defaults.  The call is performed only once at function definition time. All calls to your function will reuse the result of that definition-time function call.  If this is intended, assign the function call to a module-level variable and use that variable as a default value.___
> Approve functions used as default arguments

- project_euler/problem_034/sol1.py
Fix typos in Project Euler problem 034 solution 1:
* Fix comment
* Fix output
> Fix typos in Project Euler problem 034 solution 1

- project_euler/problem_009/sol1.py
Improve Project Euler problem 009 solution 1 - the top 4 slowest solution on Travis CI logs (under `slowest 10 durations`: `14.61s call     scripts/validate_solutions.py::test_project_euler[problem_009/sol1.py]`):
* Improve solution (locally 10+ times - from 10+ seconds to ~1 second)
* Uncomment code that has been commented due to slow execution affecting Travis (now it should be quite fast execution and not affect Travis)
> Improve Project Euler problem 009 solution 1

- DIRECTORY.md
- ciphers/a1z26.py
- ciphers/enigma_machine2.py
- ciphers/trafid_cipher.py
- ciphers/xor_cipher.py
from __future__ import annotations
> from __future__ import annotations

- project_euler/problem_014/sol2.py
Improve Project Euler problem 014 solution 2 - the top 2 slowest solution on Travis CI logs (under `slowest 10 durations`: `24.81s call     scripts/validate_solutions.py::test_project_euler[problem_014/sol2.py]`):
* Improve solution (locally 1.3+ times - from ~20 seconds to ~15 seconds)
> Improve Project Euler problem 014 solution 2

- backtracking/coloring.py
I spellchecked the comments and corrected the grammar.
> Fix grammar of comments in backtracking/coloring.py

- backtracking/hamiltonian_cycle.py
I corrected some grammar mistakes in backtracking/hamiltonian_cycle.py
> Correct grammar in hamiltonian_cycle.py

- sorts/bead_sort.py
- sorts/odd_even_transposition_single_threaded.py
- sorts/topological_sort.py
- strings/prefix_function.py
> Fix word typos in comments

- graphs/breadth_first_search.py
- graphs/breadth_first_search_2.py
- graphs/check_bipartite_graph_bfs.py
Popping the first element of a list takes O(n) time.
Using a cyclic queue takes O(1) time.
> Update queue implementation

- project_euler/problem_070/sol1.py
Improve Project Euler problem 070 solution 1:
* Change `has_same_digits` `doctest` (replace `has_same_digits(123, 12)` with similar `has_same_digits(123, 23)` which failed in current implementation)
* Improve `has_same_digits` function (it passes changed test)
> Improve Project Euler problem 070 solution 1

- data_structures/binary_tree/non_recursive_segment_tree.py
> [mypy] Fix type annotations in `data_structures/binary_tree/non_recursive_segment_tree.py`

- strings/is_contains_unique_chars.py
> added is_contains_unique_chars()

- data_structures/heap/skew_heap.py
Describe your change:
- Add Abstract Base Class `Comparable`
- [mypy] add and fix type annotations (strict mode)
-  Fix a typo
> [mypy] Add/fix type annotations in `data_structures/heap/skew_heap.py`

- strings/credit_card_validator.py
Fix spellings in credit card validator
> Credit Card Validator: Fix spellings

- other/alternative_list_arrange.py
> Added alternative_list_arrange method

- strings/check_anagrams.py
> Improve checking anagrams in O(n) with dictionary

- ciphers/decrypt_caesar_with_chi_squared.py
Fixed case sensitive not working in decrypt_casear_with_chi_squared.py
> Make decrypt_caesar_with_chi_squared work with upper case letters

- data_structures/heap/randomized_heap.py
> [mypy] Fix type annotations in `data_structures/heap/randomized_heap.py`

- dynamic_programming/fibonacci.py
- maths/series/hexagonal_numbers.py
I rewrote `fibonacci.py` as it was requested in #5665. The changes I made include: 
* Separated the logic to calculate Fibonacci numbers into the `get` method. 
* Removed `Out of Bound`, by calculating the missing numbers with the stored sequence. 
* Created `main` function with new prompt.
* Changed `get` method documentation.
Fixes: #5665
> Rewrote fibonacci.py (#5665)

- project_euler/problem_012/sol1.py
Improve Project Euler problem 012 solution 1 - the top 10 slowest solution on Travis CI logs (under `slowest 10 durations`: `3.41s call     scripts/validate_solutions.py::test_project_euler[problem_012/sol1.py]`):
* Improve solution (locally 6+ times - from 3+ seconds to ~0.5 seconds)
* Uncomment code that has been commented due to slow execution affecting Travis (now it should be quite fast execution and not affect Travis)
> Improve Project Euler problem 012 solution 1

- web_programming/search_books_by_isbn.py
> Add search book via ISBN using openlibrary.org API

- conversions/weight_conversion.py
I have added a new unit of measurement to the weight conversion algorithm. The new unit is "stone". 
I've added some tests in the docs using an external calculator. Not sure if they pass.
> Add stone unit of measuring weight

- digital_image_processing/filters/gabor_filter.py
Add the Gabor filter, which can extract  and analyze image textures.
> Add gabor filter

- maths/nevilles_method.py
> Added nevilles algorithm for polynomial interpolation

- data_structures/queue/circular_queue_linked_list.py
> [mypy] fix type annotations in `data_structures/queue/circular_queue_linked_list.py`

- bit_manipulation/gray_code_sequence.py
> Added a gray_code_sequence.py file to the bit_manipulation folder

- project_euler/problem_009/sol3.py
Uncomment doctest in Project Euler problem 009 solution 3:
* Uncomment code that has been commented due to slow execution affecting Travis (it executes quite fast and doesn't affect Travis)
> Uncomment doctest in Project Euler problem 009 solution 3

- other/davisb_putnamb_logemannb_loveland.py
+ As per usage examples, clause literals are a list of strings.
+ Note: symbols extracted from literals are expected to be exactly two characters.
+ self.literal boolean values are initialized to None, so must be optional
+ model values should be Booleans, but aren't guaranteed to be non-None
in the code.
+ uses newer '... | None' annotation for Optional values
+ clauses are passed to the Formula initializer as both lists and sets, they
are stored as lists.  Returned clauses will always be lists.
+ use explicit tuple annotation from __future__  rather than using (..., ...)
in return signatures
+ mapping returned by dpll_algorithm is optional per the documentation.
Related to #4052
Clone of #5648
```bash
% git checkout master
Switched to branch 'master'
% mypy …
```
> [mypy] Fixes typing errors in other/dpll

- data_structures/binary_tree/lowest_common_ancestor.py
-  In `data_structures/binary_tree/lowest_common_ancestor.py`:
-  [mypy] Fix and add type annotations
- Refactor line: `53`
-  Update import on line: `6`
-  Related issue: #4052
> [mypy] Fix type annotations in `data_structures/binary_tree/lowest_common_ancestor.py`

- arithmetic_analysis/README.md
- audio_filters/README.md
- backtracking/README.md
- bit_manipulation/README.md
- boolean_algebra/README.md
> Add README files 1/7

- dynamic_programming/all_construct.py
> Add all_construct dynamic programming implementation

- web_programming/reddit.py
> Added reddit.py to get data from reddit

- project_euler/problem_014/sol1.py
Improve Project Euler problem 014 solution 1 - the top 2 slowest solution on Travis CI logs (under `slowest 10 durations`: `13.91s call     scripts/validate_solutions.py::test_project_euler[problem_014/sol1.py]`):
* Improve solution (locally 10+ times - from 15+ seconds to ~1.5 seconds)
* Uncomment code that has been commented due to slow execution affecting Travis (now it should be quite fast execution and not affect Travis)
> Improve Project Euler problem 014 solution 1

- data_structures/binary_tree/red_black_tree.py
> [mypy] Fix type annotations in `data_structures/binary_tree/red_black_tree.py`

- maths/volume.py
>  Added 2 shapes in volume.py

- graphs/finding_bridges.py
Previous implementation have had a bugs in conditions, for second graph it returned `[[0, 6]]`.
I have fixed conditions and improved code a bit.
> Fix `graphs/finding_bridges.py` algorithm + doctests

- DIRECTORY.md
- project_euler/problem_043/sol1.py
Improve Project Euler problem 043 solution 1 - the top 10 slowest solution on GitHub Actions logs (under `slowest 10 durations`: `3.50s call     scripts/validate_solutions.py::test_project_euler[problem_043/sol1.py]`):
* Fix typo
* Improve solution (locally 3+ times - from 3+ seconds to ~1 second)
> Improve Project Euler problem 043 solution 1

- data_structures/stacks/next_greater_element.py
- In `data_structures/stacks/next_greater_element.py`:
- [mypy] fix type annotations
-  Refactor functions: 
-  `next_greatest_element_slow`
-   `next_greatest_element`
- Related issue: #4052
> [mypy] Fix type annotations in `data_structures/stacks/next_greater_element.py`

- DIRECTORY.md
- financial/equated_monthly_installments.py
> Add equated_monthly_installments.py in Financials

- maths/average_mode.py
- maths/gamma_recursive.py
- maths/proth_number.py
- maths/series/geometric_series.py
- maths/series/p_series.py
- mypy.ini
> [mypy] Fix type annotations for maths directory

- computer_vision/flip_augmentation.py
- computer_vision/mosaic_augmentation.py
I want to contribute the algorithms of image augmentation for computer vision task
> ADD the algorithms of image augmentation

- DIRECTORY.md
- graphs/boruvka.py
- mypy.ini
> [mypy] Fix type annotations in `graphs/boruvka.py`

- graphs/finding_bridges.py
- graphs/random_graph_generator.py
- mypy.ini
> [mypy] Type annotations for `graphs/finding_bridges.py` and `graphs/random_graph_generator.py`

- graphs/breadth_first_search.py
- graphs/breadth_first_search_2.py
- graphs/check_cycle.py
- graphs/greedy_min_vertex_cover.py
- mypy.ini
> [mypy] Type annotations for graphs directory

- DIRECTORY.md
- maths/volume.py
- project_euler/problem_205/sol1.py
Add Project Euler problem 205 solution 1:
* Add solution
> Add Project Euler problem 205 solution 1

- matrix/matrix_operation.py
- mypy.ini
- searches/simulated_annealing.py
- searches/ternary_search.py
> [mypy] Type annotations for searches directory

- project_euler/problem_145/sol1.py
> Added solution for Project Euler problem 145

- DIRECTORY.md
- matrix/matrix_operation.py
- mypy.ini
Related to #4052 
Replacement for #5806
> [mypy] Fix `matrix_operation.py`

- mypy.ini
- other/lfu_cache.py
- other/lru_cache.py
Annotation and improvements for lru_cache and lfu_cache.  
These contain a lot of duplicated code so I have put them into a single PR.
+ Annotates existing lru_cache algorithm
+ Adds tests for the internal double linked list
+ Expands algorithm annotations to be generic of key and value types
+ Added __repr__ to enable clean doctests and clarity in the repl
+ mypy required using `setattr` rather than creating an attr through assignment.
+ Makes analogous changes to lfu_cache.
PR is broken into multiple commits each handling a logical chunk and is meant to be clear when viewing each commit individually.
```
% git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
% mypy --ignore-missing-imports --install-types lru_cache.py …
```
> [mypy] Annotate other/lru_cache and other/lfu_cache

- maths/persistence.py
Added a persistence algorithm that determines the persistence of a number.
> Created new persistence algorithm

- computer_vision/pooling.py
- computer_vision/pooling_functions.py
> Adding Pooling Algorithms 

- DIRECTORY.md
- data_structures/linked_list/__init__.py
- data_structures/linked_list/circular_linked_list.py
- data_structures/linked_list/has_loop.py
- data_structures/linked_list/middle_element_of_linked_list.py
- maths/pollard_rho.py
https://www.python.org/dev/peps/pep-0563/
> Replace typing.optional with new annotations syntax

- .gitignore
- other/password_generator.py
> Lowercase g --> Capital G

- maths/fibonacci.py
> Added memoization function in fibonacci

- boolean_algebra/quine_mc_cluskey.py
I made some variables more descriptive on simple functions and changed some syntax of the following (inside Booleans):
`
return 1 == 1
instead of
if 1 == 1:
return True
else:
return False
`
and
`
while True:
instead of 
while 1
`
* [] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
> Improve Quine–McCluskey algorithm

- .github/workflows/build.yml
- DIRECTORY.md
When running with no cache the first time, mypy fails to get missing imports because the cache is missing.
An empty cache solves the issue.
https://github.com/TheAlgorithms/Python/pull/5917#issuecomment-1013850922
> ci: add mkdir step for mypy

- DIRECTORY.md
- web_programming/currency_converter.py
The use of locals in the function is unnecessary. It makes the code harder to follow because you have to check what goes in it, the locals line doesn't save any lines, and the rename of `from_` to `from` has no benefit. 
Also the types can be inferred from constants so no need to say 1.0 is a float.
> Refactor currency_converter.py

- web_programming/fetch_anime_and_play.py
> Scrape anime and play episodes on browser without ads from terminal

- .github/workflows/build.yml
- .pre-commit-config.yaml
- arithmetic_analysis/in_static_equilibrium.py
- web_programming/fetch_well_rx_price.py
> pyupgrade --py310-plus and run mypy in precommit, not build

- maths/points_are_collinear_3d.py
I'm not sure if /maths directory is suitable for this algorithm so if there is a better place for it please let me know in the comments.
> Add points are collinear in 3d algorithm to /maths

- .pre-commit-config.yaml
black==22.1.0 is breaking the hook. Updating it to 22.3.0 fixes all the issue
Please refer : https://github.com/python-poetry/poetry/issues/5375
> fix : black version

- .pre-commit-config.yaml
- arithmetic_analysis/in_static_equilibrium.py
- strings/ngram.py
> feat: added ngram algorithm

- data_structures/binary_tree/binary_tree_traversals.md
- sorts/normal_distribution_quick_sort.md
I fixed the quicksort documentation following the markdown best practices.
> Fix quicksort doc

- conversions/prefix_conversions_string.py
> fix black at prefix string

- project_euler/problem_145/sol1.py
- Created new directory as per Project Euler guidelines https://github.com/TheAlgorithms/Python/tree/master/project_euler/README.md
- There is no URL for the explanation of this algorithm, I have programmed it myself, it is a straightforward algorithm with necessary comments
> Solution to Problem 145 of Project Euler

- computer_vision/horn_schunck.py
> Added implementation of the Horn-Schunck algorithm

- project_euler/problem_686/sol1.py
While reading this code I noticed some typos in the doc strings and wanted to fix them.
> Fix some typos in solution 1 of euler 686

- arithmetic_analysis/gaussian_elimination.py
- arithmetic_analysis/in_static_equilibrium.py
- arithmetic_analysis/jacobi_iteration_method.py
- arithmetic_analysis/lu_decomposition.py
> fixed mypy annotations for arithmetic_analysis

- project_euler/problem_074/sol2.py
Improve Project Euler problem 074 solution 2 - the top 3 slowest solution on GitHub Actions logs (under `slowest 10 durations`: `13.77s call     scripts/validate_solutions.py::test_project_euler[problem_074/sol2.py]`):
* Fix statement
* Improve solution (locally 7+ times - from 14+ seconds to ~2 seconds)
> Improve Project Euler problem 074 solution 2

- strings/autocomplete_using_trie.py
- strings/detecting_english_programmatically.py
- strings/frequency_finder.py
- strings/word_occurrence.py
- strings/z_function.py
> Add missing type annotations for `strings` directory

- ciphers/enigma_machine2.py
- ciphers/hill_cipher.py
- data_structures/hashing/number_theory/prime_numbers.py
- divide_and_conquer/strassen_matrix_multiplication.py
- dynamic_programming/rod_cutting.py
- hashes/enigma_machine.py
- maths/integration_by_simpson_approx.py
- matrix/matrix_operation.py
- project_euler/problem_067/sol1.py
- sorts/external_sort.py
> Improve Code

- maths/sin.py
> Add sin function to /maths

- conversions/octal_to_decimal.py
- sorts/iterative_merge_sort.py
> Fix `iter_merge_sort` bug

- graphs/minimum_path_sum.py
Added an algorithm that takes a 2 dimensional grid of numbers, and finds the path starting from the top left and ending at the bottom right with the lowest possible sum of numbers along the path. It then returns the sum of all numbers along that path. 
For Example:
Input: [
[1,3,1],
[1,5,1],
[4,2,1]
]
Expected output: 7
fixes #4796
> Minmum path sum

- scheduling/multi_level_feedback_queue.py
> Add Multi-Level-Feedback-Queue scheduling algorithm

- scheduling/highest_response_ratio_next.py
> add highest_response_ratio_next.py

- .github/workflows/build.yml
- .github/workflows/directory_writer.yml
- .github/workflows/pre-commit.yml
- .github/workflows/project_euler.yml
- .pre-commit-config.yaml
- DIRECTORY.md
> Upgrade GitHub Actions

- .github/workflows/pre-commit.yml
- DIRECTORY.md
- project_euler/problem_101/sol1.py
> Get rid of the Union

- DIRECTORY.md
- data_structures/hashing/double_hash.py
- data_structures/hashing/number_theory/prime_numbers.py
- maths/prime_check.py
- maths/primelib.py
I refactored some functions in order to fix #5434. More specifically,
1. I changed the name of some function in order to agree with naming conventions.
2. I changed the implementation of a primality checking function in order to have a `O(sqrt(n))` time complexity algorithm.
There are some more functions that are related to primality checking namely the [lucas_lehmer_primality_test.py](https://github.com/TheAlgorithms/Python/blob/master/maths/lucas_lehmer_primality_test.py) and [miller_rabin.py](https://github.com/TheAlgorithms/Python/blob/master/maths/miller_rabin.py) but I did not change these since they are specific algorithms.
I have searched for every mention of the word `prime` in all of the files and except from the [project_euler](https://github.com/TheAlgorithms/Python/tree/master …
> Unify primality checking

- maths/miller_rabin.py
- maths/prime_check.py
1. Incorrect function was being imported from the module
2. Testing for exception was not done correctly
> fix: test failures

- DIRECTORY.md
- project_euler/problem_145/sol1.py
Improve Project Euler problem 145 solution 1 - the top 1 slowest solution on GitHub Actions logs (under `slowest 10 durations`: `803.76s call     scripts/validate_solutions.py::test_project_euler[problem_145/sol1.py]`):
* Improve solution (~30 times - from 900+ seconds to ~30 seconds)
> Improve Project Euler problem 145 solution 1

- project_euler/problem_005/sol2.py
Fixed naming convention as described in Contribution.md
> Expand acronyms because gcd() is hard to understand but greatest_common_divisor() is not.
> renamed gcd() to greatest_comman_divisor()

- DIRECTORY.md
- project_euler/problem_587/sol1.py
Add Project Euler problem 587 solution 1:
> Add Project Euler problem 587 solution 1

- DIRECTORY.md
- project_euler/problem_115/sol1.py
Add Project Euler problem 115 solution 1:
> Add Project Euler problem 115 solution 1

- data_structures/binary_tree/maximum_fenwick_tree.py
And test for bugs in Max Fenwick Tree and modifications to fix them.
Using 1-based-indexing operations: `(index | (index + 1))` for a 0-based fenwick tree requires handling edge cases and is the cause for the bugs. Replacing with 0-based-indexing operations.
> Fix Max Fenwick Tree

- project_euler/problem_003/sol1.py
- project_euler/problem_007/sol1.py
- project_euler/problem_007/sol2.py
- project_euler/problem_007/sol3.py
- project_euler/problem_010/sol1.py
- project_euler/problem_010/sol2.py
- project_euler/problem_027/sol1.py
- project_euler/problem_037/sol1.py
- project_euler/problem_041/sol1.py
- project_euler/problem_046/sol1.py
- project_euler/problem_049/sol1.py
- project_euler/problem_058/sol1.py
I changed the implementation of is_prime functions inside project_euler in order to have a unified implementation. There are some cases where the solution uses the Eratosthenes' sieve method. In some cases there is no specific gain from using that method so I changed it to the O(sqrt(n)) algorithm, but in other cases the sieve method is used in the core structure of the solution, hence I did not touch those.
fixes #5434
> Unify `O(sqrt(N))` `is_prime` functions under `project_euler`

- matrix/inverse_of_matrix.py
I have fixed a minor typo in a comment within ìnverse_of_matrix.py` as well as added a simple check to ensure the provided matrix has the correct dimension (in this case only 2x2). 
Since this implementation only works for 2x2 matrices, we want to make sure to give a warning when calling it with 2x3, 3x3, etc., otherwise the function returns false results. I have also added a short comment for clarity.
> Fix minor typo and add matrix dimension check

- DIRECTORY.md
- matrix/inverse_of_matrix.py
- project_euler/problem_116/sol1.py
Add Project Euler problem 116 solution 1:
> Add Project Euler problem 116 solution 1

- sorts/radix_sort.py
> Fix docstring

- web_programming/fetch_quotes.py
fetches quotes from zenquotes.io api
> Added fetch_quotes.py

- compression/run_length_encoding.py
Added run length encoding (compression algorithm)
> Run length encoding

- maths/segmented_sieve.py
Improved code complexity for segmented sieve - [segmented_sieve.py](https://github.com/TheAlgorithms/Python/blob/master/maths/segmented_sieve.py)
Tested code complexity using [radon tool](https://pypi.org/project/radon/)
Previously the CC rank was C, now it is B
To check the improvement use
```
radon cc Python/maths/segmented_sieve.py -a
```
> Improved code complexity for segmented sieve

- sorts/quick_sort.py
As described in #6095, this reduces the chances to observe a O(n^2) complexity.
Here, `collection.pop(pivot_index)` is avoided for performance reasons.
> refactor: pivot is randomly chosen

- DIRECTORY.md
- maths/catalan_number.py
> Add Catalan number to maths

- greedy_methods/job_sequencing_with_deadline.py
- scheduling/job_sequencing_with_deadline.py
In this PR, I have written an optimized algorithm for the issue "Job Sequencing with Deadlines". This problem required a greedy approach so I have created a new python file "job_sequencing_with_deadlines" in the "greedy_methods" directory.
> Job sequencing with deadlines

- data_structures/heap/heap_generic.py
> Add typing to data_structures/heap/heap_generic.py

- data_structures/hashing/hash_table.py
> Add typing to data_structures/hashing/hash_table.py

- data_structures/queue/queue_on_pseudo_stack.py
hacktoberfest
* [] Add an algorithm?
> Add typing to data_structures/queue/queue_on_pseudo_stack.py

- maths/area.py
> Add surface area of cuboid, conical frustum

- DIRECTORY.md
- README.md
> README.md: Lose LGTM badge because we don't use it

- strings/snake_case_to_camel_pascal_case.py
> Convert snake_case to camelCase or PascalCase (#7028)

- DIRECTORY.md
- data_structures/binary_tree/inorder_tree_traversal_2022.py
> Binary Search Tree Inorder Traversal Algorithm

- README.md
added some refinements to readme.md
> refined readme.md

- .flake8
- .pre-commit-config.yaml
> refactor: move flake8 config

- conversions/astronomical_length_scale_conversion.py
Added a script that enable conversion with the astronomical length units, inspired by `length_conversion.py`.
> Added astronomical_length_scale_conversion.py

- data_structures/binary_tree/binary_search_tree.py
- data_structures/heap/heap_generic.py
- data_structures/trie/trie.py
- graphs/frequent_pattern_graph_miner.py
- maths/greedy_coin_change.py
- other/davisb_putnamb_logemannb_loveland.py
- project_euler/problem_107/sol1.py
- searches/tabu_search.py
- sorts/msd_radix_sort.py
- strings/aho_corasick.py
Replace all `list()` and `dict()` calls with literal `[]` and `{}`s
> refactor: Replace `list()` and `dict()` calls with literals

- .github/ISSUE_TEMPLATE/feature_request.yml
- DIRECTORY.md
> chore: remove checkbox in feature issue template

- DIRECTORY.md
- data_structures/binary_tree/binary_tree_node_sum.py
Implements #7020 
Algorithm to get the sum of all tree nodes
> feat: Binary tree node sum (#7020)

- .pre-commit-config.yaml
- ciphers/onepad_cipher.py
- ciphers/rail_fence_cipher.py
- data_structures/hashing/hash_table.py
- data_structures/linked_list/merge_two_lists.py
- dynamic_programming/fractional_knapsack.py
- graphs/bellman_ford.py
- graphs/frequent_pattern_graph_miner.py
- hashes/enigma_machine.py
- maths/primelib.py
- matrix/spiral_print.py
- other/davisb_putnamb_logemannb_loveland.py
- project_euler/problem_042/solution42.py
- project_euler/problem_052/sol1.py
- project_euler/problem_062/sol1.py
- project_euler/problem_067/sol1.py
- project_euler/problem_109/sol1.py
- project_euler/problem_551/sol1.py
- sorts/radix_sort.py
- strings/aho_corasick.py
> Add Flake8 comprehensions to pre-commit

- data_structures/binary_tree/binary_search_tree.py
Update the typehints in `data_structures/binary_tree/binary_tree_search.py`
> types: Update binary search tree typehints

- fractals/julia_sets.py
- fractals/sierpinski_triangle.py
- machine_learning/lstm/lstm_prediction.py
- machine_learning/sequential_minimum_optimization.py
- maths/matrix_exponentiation.py
- maths/test_prime_check.py
- neural_network/input_data.py_tf
- physics/n_body_simulation.py
- strings/frequency_finder.py
- web_programming/crawl_google_results.py
- web_programming/crawl_google_scholar_citation.py
- web_programming/current_weather.py
- web_programming/giphy.py
> Change to https.

- maths/volume.py
added some more comments (to formulas which need it) which make the code more readable and understandable. might make a list of all the formulas on the top, later
> Added some more comments to volume.py in maths folder

- bit_manipulation/count_1s_brian_kernighan_method.py
- machine_learning/sequential_minimum_optimization.py
- physics/n_body_simulation.py
My previous PR, #7277, broke some of the links. This PR is to fix those.
> Fix broken links by PR #7277

- maths/gaussian_error_linear_unit.py
- maths/gelu.py
> Implemented Gelu Function

- quantum/quantum_random.py
- requirements.txt
> Add quantum_random.py

- maths/maclaurin_sin.py
- Added a function to determine an approximation of sin(x) in radians via the Maclaurin series
> Maclaurin series approximation of sin

- maths/sum_of_harmonic_series.py
Here in this code the formula for Harmonic sum is not used, Sum of the series is calculated by creating a list of the elements in the given Harmonic series and adding all the elements of that list !
**A list l1 is created which contains the elements of the Arithmetic Progression to which the given Harmonic Progression is linked and then a list l2 is created which contains the reciprocal of all the elements of list l1 which means list l2 contains all the elements of the given Harmonic Series.**
[Wikipedia link for better understanding of Harmonic Series](https://en.wikipedia.org/wiki/Harmonic_progression_(mathematics))
> Created sum_of_harmonic_series.py

- genetic_algorithm/basic_string.py
Grammar check and fix for genetic_algorithm/basic_string.py
> Basic string grammar fix

- maths/signum.py
> Add signum function

- requirements.txt
- web_programming/get_top_billioners.py
Using the Forbes API to get the top ten real-time billionaires and present in a [rich](https://github.com/Textualize/rich) table.
Here's the sample output:
> Add web program to fetch top 10 real time billionaires using the forbes API.

- conversions/pressure_conversions.py
- electronics/carrier_concentration.py
- electronics/electric_power.py
- maths/nevilles_method.py
Replace `File "/usr/bin..."` with `...`
> Fix doctest tracebacks

- DIRECTORY.md
- strings/is_palindrome.py
> My favorite palindrome

- DIRECTORY.md
- project_euler/problem_073/sol1.py
Add Project Euler problem 073 solution 1:
> feat: add Project Euler problem 073 solution 1

- boolean_algebra/xor_gate.py
> Add function for xor gate

- matrix/cramers_rule_2x2.py
- matrix/system_of_linear_equation_in_2_variables.py
Fixes #7122 
* [] Documentation change?
> Add Cramer's rule for solving system of linear equations in two variables

- dynamic_programming/longest_common_substring.py
> Add longest common substring

- maths/area.py
Added a function to calculate the area of n sided regular polygons
> Included area of n sided regular polygon

- ciphers/base16.py
According to CONTRIBUTING.md:
"Algorithms in this repo should not be how-to examples for existing Python packages."
The previous "implementation" for base16 imported and used a library to do it (it was just a demonstration of the `base64` library), so I wrote an implementation to replace it.
> Write a proper implementation for base16

- machine_learning/xgboost_classifier.py
> refactor: Fix matrix display deprecation

- strings/detecting_english_programmatically.py
> Refactoring the syntax using list comprehension

- .pre-commit-config.yaml
- DIRECTORY.md
- ciphers/enigma_machine2.py
- data_structures/linked_list/doubly_linked_list_two.py
- dynamic_programming/fibonacci.py
- machine_learning/sequential_minimum_optimization.py
- strings/indian_phone_validator.py
Adopt Python >= 3.8 [assignment expressions](https://docs.python.org/3/whatsnew/3.8.html) using https://pypi.org/project/auto-walrus/
> Adopt Python >= 3.8 assignment expressions using auto-walrus

- .pre-commit-config.yaml
- DIRECTORY.md
- data_structures/binary_tree/non_recursive_segment_tree.py
- digital_image_processing/index_calculation.py
- genetic_algorithm/basic_string.py
- maths/prime_sieve_eratosthenes.py
I have noticed that yesqa is not working as the flake8 plugin.  
It should be installed as a separate hook.  
To have exactly the same flake8 setting plugins should be installed on both hooks. 
I added a YAML anchor to keep plugins declaration in a single place.  
Fix warnings that were raised by this hook across the repo.
> Fix yesqa hook

- electronics/electric_conductivity.py
- physics/sheer_stress.py
added new algorithm for calculating electric conductivity
> add electric conductivity algorithm

- electronics/electrical_impedance.py
- electronics/resonant_frequency.py
> Resonant Frequency & Electrical Impedance

- machine_learning/similarity_search.py
> Added cosine similarity

- neural_network/simple_neural_network.py
```
Trying:
res = forward_propagation(32, 10000000)
Expecting nothing
ok
Trying:
res > 31 and res < 33
Expecting:
True
ok
Trying:
res = forward_propagation(32, 1000)
Expecting nothing
ok
Trying:
res > 31 and res < 33
Expecting:
False
ok
Trying:
sigmoid_function(3.5)
Expecting:
0.9706877692486436
ok
Trying:
sigmoid_function(3.5, True)
Expecting:
-8.75
ok
1 items had no tests:
simple_neural_network
2 items passed all tests:
4 tests in simple_neural_network.forward_propagation
2 tests in simple_neural_network.sigmoid_function
6 tests in 3 items.
6 passed and 0 failed.
Test passed.
```
> Add simple neural network

- strings/anagrams.py
Increased Readability Of Variables
* [ Yes] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ Yes] This pull request is all my own work -- I have not plagiarized.
* [ Yes] I know that pull requests will not be merged if they fail the automated tests.
* [ Yes] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ Yes] All new Python files are placed inside an existing directory.
* [ Yes] All filenames are in all lowercase characters with no spaces or dashes.
* [ Yes] All functions and variable names follow Python naming conventions.
* [ Yes] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ Yes] …
> Increased Readability Of Variables

- maths/manhattan_distance.py
Added an algorithm to calculate Manhattan distance,
Added the algorithm twice, one in a mor traditional way and other using a one-liner.
Fixes: #7776
> Added Manhattan distance algorithm

- quantum/quantum_teleportation.py
This code is for the #hacktoberfest
This circuit run the teleportation circuit using Qiskit. You can change the teleported state as preference.
I add the quantum teleportation algorithm using qiskit. This is my first Pull Request let me know if I did it well.
Best,
* [ X] Add an algorithm?
* [ X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ X] This pull request is all my own work -- I have not plagiarized.
* [ X] I know that pull requests will not be merged if they fail the automated tests.
* [ X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ X] All new Python files are placed inside an existing directory.
* [ X] All filenames are in all lowercase characters with no …
> quantum_teleportation.py

- dynamic_programming/climbing_stairs.py
Improve current solution to the climbing stairs problem by reducing memory footprint.
Just to be sure I haven't broken the original solution (new version is `climb_stairs_new` in the following test snippet):
```python
>>> from hypothesis import given
>>> from hypothesis.strategies import integers
>>> 
>>> @given(integers(min_value=1, max_value=200))
>>> def test_fast(n: int) -> None:
>>>     assert climb_stairs(n) == climb_stairs_new(n)
>>> 
>>> test_fast()
```
> Simplify climbing stairs and use constant memory

- physics/ideal_gas_law.py
> Add Ideal Gas Law for physics

- physics/rms_speed_of_molecule.py
> Add root mean square speed of gas molecules to physics

- sorts/bubble_sort.py
In this change I have initialized a variable p with the value of (1e9+7) and then took the modulus of process time with it . This modification gives better time taken by the process . Firstly it was giving answer in the exponential now it gives in the integer form.
Fixed a small problem.
> For the better understanding of time taken.

- hashes/elf.py
> Adding ELFHash Algorithm

- physics/archimedes_principle.py
> Added archimedes principle (physics)

- maths/sum_of_digits.py
n = -n if n < 0 else n --> n = abs(n)
n = n // 10 --> n //= 10
> refactor: use abs() and inplace operation

- electronics/builtin_voltage.py
- hashes/elf.py
> Added Builtin Voltage

- machine_learning/linear_regression.py
> Added mean absolute error in linear regression

- dynamic_programming/min_distance_up_bottom.py
Levinstein distance with Dynamic Programming: up -> down approach. some tests are copied from https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/edit_distance.py#L61 .
> add Levinstein distance with Dynamic Programming: up -> down approach

- dynamic_programming/palindrome_partitioning.py
> Added code for palindrome partitioning problem under dynamic programming

- electronics/resistor_equivalence.py
Hi all, 
I added the equivalent_resistance package to the electronics folder!
This is my first time contributing to open source so please let me know if you have any suggestions!
> Created equivalent_resistance under Electronics

- maths/print_multiplication_table.py
> Add print_multiplication_table.py

- data_structures/trie/radix_tree.py
> Added Radix Tree in data structures

- maths/area.py
- sorts/README.md
Adds an algorithm to calculate the surface area of a Torus
> Added Torus surface area

- maths/volume.py
Adds an algorithm to calculate the volume of a Torus
> Torus volume

- physics/hubble_parameter.py
> Added a Hubble Parameter calculator file

- DIRECTORY.md
- maths/sum_of_digits.py
```
sum_of_digits(262144)                                    = 19 -- 0.3103 seconds
sum_of_digits_recursion(262144)                          = 19 -- 0.3417 seconds
sum_of_digits_compact(262144)                            = 19 -- 0.6018 seconds
sum_of_digits(1125899906842624)                          = 76 -- 0.8055 seconds
sum_of_digits_recursion(1125899906842624)                = 76 -- 0.8442 seconds
sum_of_digits_compact(1125899906842624)                  = 76 -- 1.2490 seconds
sum_of_digits(1267650600228229401496703205376)           = 115 -- 1.6378 seconds
sum_of_digits_recursion(1267650600228229401496703205376) = 115 -- 1.7176 seconds
sum_of_digits_compact(1267650600228229401496703205376)   = 115 -- 2.2484 second
```
> maths/sum_of_digits.py: Streamline benchmarks

- bit_manipulation/is_power_of_two.py
> Is power of two

- .flake8
- other/graham_scan.py
Reduce the complexity of other/graham_scan.py from 20 to 14
> Reduce the complexity of other/graham_scan.py

- DIRECTORY.md
- data_structures/arrays/prefix_sum.py
> add prefix sum

- quantum/bb84.py
- requirements.txt
Added an algorithm that simulates the BB84 quantum key-distribution protocol.
> BB84 QKD algorithm

- maths/pronic_number.py
> feat: Add pronic number implementation

- DIRECTORY.md
- ciphers/atbash.py
> atbash.py: Tighten up the benchmarks

- DIRECTORY.md
- data_structures/binary_tree/distribute_coins.py
> add distribute coins

- conversions/decimal_to_any.py
- data_structures/linked_list/__init__.py
- matrix/matrix_class.py
fixes: #7987 
Note that `matrix/matrix_class.py` had CRLF line endings, that was converted to LF line endings and that's the major diff you're seeing. The actual diff is:
```diff
diff --git a/matrix/matrix_class.py b/matrix/matrix_class.py
index a73e8b92..2b4edc3c 100644
--- a/matrix/matrix_class.py
+++ b/matrix/matrix_class.py
@@ -345,7 +345,7 @@ class Matrix:
if other == 0:
return self.identity()
if other < 0:
-            if self.is_invertable:
+            if self.is_invertable():
return self.inverse() ** (-other)
raise ValueError(
"Only invertable matrices can be raised to a negative power"
```
> fix: mypy 0.991 issues

- maths/juggler_sequence.py
> algorithm: Add juggler sequence

- DIRECTORY.md
- bit_manipulation/count_1s_brian_kernighan_method.py
> Fix argument validation for count_1s_brian_kernighan_method

- DIRECTORY.md
- backtracking/word_search.py
> Add backtrack word search in matrix

- .flake8
- sorts/merge_insertion_sort.py
Reduce the complexity of sorts/merge_insertion sort.py from 19 to 9
> Reduce the complexity of sorts/merge_insertion_sort.py

- DIRECTORY.md
- dynamic_programming/word_break.py
> add word_break dynamic approach up -> down.

- DIRECTORY.md
- machine_learning/local_weighted_learning/local_weighted_learning.py
Fixes #7307 by refactoring [machine_learning/local_weighted_learning/local_weighted_learning.py](https://github.com/TheAlgorithms/Python/blob/master/machine_learning/local_weighted_learning/local_weighted_learning.py) to use `np.array` rather than `np.matrix`. This ~~should silence~~ silences the pytest warnings about `np.matrix` being due to be depreciated.
> Refactor `local_weighted_learning.py` to use `np.array`

- DIRECTORY.md
- fractals/sierpinski_triangle.py
- Updated header documentation and added link to source Wikipedia article
- Added type hints
- Refactored some code for clarity
The original code was taken almost exactly from a website cited in the header doc, so I wanted to improve upon the code so that it's at least not _entirely_ copied.
> Refactor `sierpinski_triangle.py`

- maths/fibonacci.py
> Create cached fibonacci algorithm

- maths/gcd_of_n_numbers.py
Greatest common divisor for n numbers
> gcd_of_n_numbers

- DIRECTORY.md
- physics/lorentz_transformation_four_vector.py
Fixed type hints to resolve `mypy` errors in `physics/lorentz_transformation_four_vector.py` (see #8070), added documentation, and refactored some things
> Fix `mypy` errors in `lorentz_transformation_four_vector.py`

- README.md
Updated the image for Line 25.
* [ X] Documentation change?
> New contribution: fix_ci_badge

- electronics/circular_convolution.py
> Add circular convolution

- .flake8
- backtracking/word_search.py
Reduce the complexity of backtracking/word_search.py from 18 to 10
> Reduce the complexity of backtracking/word_search.py

- data_structures/hashing/hash_map.py
- data_structures/hashing/tests/test_hash_map.py
Add hash map data structure. 
Another name for a hash map is a hash table. And there is a file with such name.
The difference with `hash_table.py` file. 
- `hash_table.HashTable` implements API similar to Hash Set, it works only with values.  My implementation implement MutableMapping ](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping)interface  
- `hash_table.HashTable` uses a Python dictionary under the hood: `self._keys: dict = {}`.  My implementation does not use another implementation of a hash map inside.
> Add hash map

- DIRECTORY.md
- electronics/circular_convolution.py
- project_euler/problem_100/sol1.py
Add Project Euler problem 100 solution 1:
> Add Project Euler problem 100 solution 1

- CONTRIBUTING.md
- audio_filters/equal_loudness_filter.py.broken.txt
- data_structures/binary_tree/red_black_tree.py
- digital_image_processing/change_contrast.py
- maths/is_square_free.py
- maths/mobius_function.py
- other/linear_congruential_generator.py
- pyproject.toml
- quantum/ripple_adder_classic.py
> Replace flake8 with ruff

- .github/stale.yml
- CONTRIBUTING.md
- README.md
- project_euler/README.md
The link <https://gitter.im/TheAlgorithms> as used in the `README.md` and `CONTRIBUTING.md` files is invalid and returns the error `404 Not Found`.
I fixed the link to the working version <https://gitter.im/TheAlgorithms/community>.
This PR fixes issue #8197
> Fix broken links to Gitter community

- data_structures/linked_list/circular_linked_list.py
- data_structures/linked_list/doubly_linked_list.py
- data_structures/linked_list/merge_two_lists.py
- data_structures/linked_list/singly_linked_list.py
Following #5315 and #5320, I was convinced that it's better to calculate `__len__` each time on demand. But current implementation has "*space*" complexity problem when dealing with a huge linked list. That temporary `tuple` is unnecessary.  A one-line change using built-in `sum()` and a generator expression would solve it without breaking existing codes.
> change space complexity of linked list's __len__ from O(n) to O(1)

- data_structures/linked_list/doubly_linked_list.py
I reduced the number of calls to `__len__` by storing the result into a local variable as it's currently a costly method( O(N) ).
To elaborate more: Suppose we insert an item at the tail like:
```python
l = DoublyLinkedList()
l.insert_at_tail("foo")
l.insert_at_tail("boo")   # <------- Here
```
The second call to `insert_at_tail` causes `__len__` to be called three times:
1. inside `self.insert_at_nth(len(self), data)` (because of delegating to `insert_at_nth`)
2. one at `if not 0 <= index <= len(self)` inside `insert_at_nth`
3. one at `elif index == len(self)` inside `insert_at_nth`
Same thing happens in `delete_at_nth`.
---
> Remove extra `len` calls in doubly-linked-list's methods

- physics/grahams_law.py
> Graham's Law

- data_structures/queue/queue_by_two_stacks.py
- data_structures/queue/queue_on_two_stacks.py
Here is the implementation of Queue using two stacks. It has O(1) time complexity for en-queuing and *Amortized* O(1) for de-queuing. The worst case time complexity for de-queuing is O(n) though.  The rationale behind this and its use-cases are mentioned [here](https://stackoverflow.com/a/2050402/13944524) and [here](https://stackoverflow.com/a/7395431/13944524).
I also included *doctest* for methods. It's formatted using "Black" and checked by "Mypy".
---
> Queue implementation using two Stacks

- data_structures/hashing/bloom_filter.py
> Bloom Filter

- ciphers/rsa_cipher.py
- machine_learning/linear_discriminant_analysis.py
> Update linear_discriminant_analysis.py and rsa_cipher.py

- financial/present_value.py
I added a financial algorithm that calculates the present value of a stream of yearly cash flows at a given discount rate.
> Added an algorithm to calculate the present value of cash flows

- DIRECTORY.md
- financial/present_value.py
@dhruvmanila Please review this mistake that I made.
> Fix docstring in present_value.py

- maths/remove_digit.py
this algorithm returns the biggest possible result that can be achieved by removing one digit from the given number.
> adding the remove digit algorithm

- maths/odd_sieve.py
> Added odd_sieve.py

- DIRECTORY.md
- other/h_index.py
> Add h index

- DIRECTORY.md
- maths/dual_number_automatic_differentiation.py
Added an algorithm to differentiate an equation to find the exact solution using dual numbers.
Note this only works for basic functions, f(x) where the power of x is positive.
https://en.wikipedia.org/wiki/Automatic_differentiation#Automatic_differentiation_using_dual_numbers
https://blog.jliszka.org/2013/10/24/exact-numeric-nth-derivatives.html
> Dual Number Automatic Differentiation

- DIRECTORY.md
- divide_and_conquer/strassen_matrix_multiplication.py
Fixes #8733
Fixes type error in `divide_and_conquer/strassen_matrix_multiplication.py` by ensuring that matrix dimensions are passed into `max` as ints and not tuples
> Fix type error in `strassen_matrix_multiplication.py`

- web_programming/currency_converter.py
> Pytest locally fails due to API_KEY env variable

- data_structures/binary_tree/binary_search_tree.py
> Fix removing the root node in binary_search_tree.py removes the whole tree

- financial/interest.py
In almost every scenario financial institutions will give the APR for a loan or credit card. This function allows you to calculate the interest without having to calculate the effective interest rate from the APR.
> Added apr_interest function to financial

- backtracking/power_sum.py
- pyproject.toml
Add new solution to a problem named power sum. The problem is from [here](https://www.hackerrank.com/challenges/the-power-sum/problem).
>  Add power sum problem

- arithmetic_analysis/newton_raphson.py
Fixes: #8864
Fix failing ruff tests by adding `# noqa: S307`
> Fix failing tests from ruff/newton_raphson (ignore S307 "possibly insecure function")

- .pre-commit-config.yaml
- cellular_automata/game_of_life.py
- data_structures/binary_tree/red_black_tree.py
- data_structures/trie/radix_tree.py
- divide_and_conquer/convex_hull.py
- graphs/directed_and_undirected_(weighted)_graph.py
- graphs/edmonds_karp_multiple_source_and_sink.py
- maths/factorial.py
- maths/primelib.py
- other/davisb_putnamb_logemannb_loveland.py
- project_euler/problem_009/sol3.py
- quantum/ripple_adder_classic.py
- strings/min_cost_string_conversion.py
- web_programming/convert_number_to_words.py
Fixes all errors shown in the failing tests here
https://github.com/TheAlgorithms/Python/actions/runs/5629561962/job/15254651560?pr=8875
Fixes #8876 
Fixes #8877 
Fixes #8878 
Fixes #8880
> [Upgrade Ruff] Fix all errors raised from ruff

- CONTRIBUTING.md
Following #8866, I've added a paragraph to `CONTRIBUTING.md` explicitly asking contributors to not ask to be assigned to issues. Although we don't assign issues in this repo, this was never actually stated in the contributing guidelines.
> Add note in `CONTRIBUTING.md` about not asking to be assigned to issues

- data_structures/trie/radix_tree.py
Fixes: 8888
Consider a word, and a copy of that word, but with the last letter repeated twice. (e.g., ["ABC", "ABCC"])
When adding the second word's last letter, it only compares the previous word's prefix—the last letter of the word already in the Radix Tree: 'C'—and the letter to be added—the last letter of the word we're currently adding: 'C'. So it wrongly passes the "Case 1" check, marks the current node as a leaf node when it already was, then returns when there's still one more letter to add.
The issue arises because `prefix` includes the letters of the node itself. (e.g., `nodes: {'C' : RadixNode()}, is_leaf: True, prefix: 'C'`) It can be easily circumvented by simply adding the `is_leaf` check, as the code already assumes you only input new words.
- Test Case: `"A AA AAA AAAA …
> Fix `radix_tree.py` insertion fail in ["*X", "*XX"] cases

- digital_image_processing/dithering/burkes.py
Hello there,
I've used your algorithm to re-implement it in C for a side-project of mine, and noticed two little bugs in it:
1) the luminance calculation is incorrect - according to Internet, it's either (0.2126*R + 0.7152*G + 0.0722*B) or (0.299*R + 0.587*G + 0.114*B). Here, we had a mix of both (and the greyscale value could never reach 255.
2) the current_error setting used inverted coordinates.
Hope this helps!
> Fix greyscale computation and inverted coords

- data_structures/binary_tree/binary_tree_traversals.py
Simply added "reverse inorder traversal" to the list of traversals. It's particularly useful with binary search tree in which it gives the items in *descending* order as opposed to inorder traversal which gives the items in *ascending* order.
> add reverse_inorder traversal to binary_tree_traversals.py

- DIRECTORY.md
- graphs/eulerian_path_and_circuit_for_undirected_graph.py
- physics/newtons_second_law_of_motion.py
Fix graphs/eulerian_path_and_circuit_for_undirected_graph.py and physics/newtons_second_law_of_motion.py, which are causing ruff to fail
> Ruff fixes

- searches/jump_search.py
Here are a few minor improvements to the current implementation of [jump_search.py](https://github.com/TheAlgorithms/Python/blob/master/searches/jump_search.py) algorithm.
1. `int(math.floor(math.sqrt(n)))` is the same thing as `int(math.sqrt(n))` and it can be calculated once.
2. Better naming for variables.
3. Add type hints which indicates that this function can also work with other sequence types as long as they are comparable.
4. `prev = prev + 1` --> `prev += 1`
> improvements to jump_search.py

- web_programming/current_stock_price.py
> updated the URL and HTML tags for scrapping yahoo finance

- linear_algebra/src/polynom_for_points.py
- pyproject.toml
Reduce the complexity of linear_algebra/src/polynom_for_points.py from 17 to 13
> Reduce the complexity of linear_algebra/src/polynom_for_points.py

- DIRECTORY.md
- machine_learning/forecasting/ex_data.csv
- machine_learning/forecasting/run.py
…tion
Fixes [#7305]
I have modified the run.py and it runs without any errors locally. 
-  Removed headers argument from `read_csv` as it caused errors in Normalization.
-  Renamed the train and test column variables as it wasn't easily comprehensible
- Added a Type check condition in case of passing wrong type as arguments in `data_safety_checker` function.
> Update run.py in machine_learning/forecasting

- DIRECTORY.md
- machine_learning/forecasting/run.py
Fixes [#7305] [#8780]
The numpy Runtime warning was due to the 0 in `seasonal_order` tuple and regarding the ARIMA models. For estimation, it needs more observations to work well and the User Warning are raised because of the sample test `>>> sarimax_predictor([4,2,6,8], [3,1,2,4], [2])` used by doctests.
> Fixed Pytest warnings for machine_learning/forecasting

- computer_vision/flip_augmentation.py
> Remove a slash in path to save the file correctly on Linux

- graphs/greedy_best_first.py
> Fix greedy_best_first

- DIRECTORY.md
- boolean_algebra/quine_mc_cluskey.py
Reduce the complexity of boolean_algebra/quine_mc_cluskey.py from 17 to 13
> Reduce the complexity of boolean_algebra/quine_mc_cluskey.py

- physics/n_body_simulation.py
Upon executing `physics/n_body_simulation.py` the error occured:
```
Traceback (most recent call last):
File "/home/simon/Documents/pythonProjects/educational/TheAlgorithms-Python/physics/n_body_simulation.py", line 341, in <module>
plot("Figure-8 solution to the 3-body-problem", example_1(), -2, 2, -2, 2)
File "/home/simon/Documents/pythonProjects/educational/TheAlgorithms-Python/physics/n_body_simulation.py", line 229, in plot
fig.canvas.set_window_title(title)
AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title'
```
The `set_window_title` method has been deprecated in Matplotlib 3.4. Apparently, a quick fix is to use `fig.canvas.manager.set_window_title` instead.
> Quick fix: fig.canvas.set_window_title deprecated

- maths/continued_fraction.py
- Per [comment](https://github.com/TheAlgorithms/Python/pull/6846#discussion_r1295767887) on #6846, I've added doctests to `continued_fractions.py` for 0 and negative numbers
- Fixed the implementation to work for negative numbers by replacing `int()` call with `floor()`: the algorithm requires a rounding down to the nearest int, but `int()` rounds to 0, not down
> Fix continued_fraction.py to work for negative numbers

- arithmetic_analysis/gaussian_elimination.py
Utilize numpy.dot to calculate the dot product, enhancing both conciseness and performance
> Refactorings

- sorts/insertion_sort.py
Fixes #9002.
- type hints added.
- I left the return value untouched as other sorting algorithms are all returning the mutated list.
> fixes #9002; improve insertion_sort algorithm

- maths/harshad_numbers.py
> Created harshad_numbers.py

- neural_network/activation_functions/scaled_exponential_linear_unit.py
Added Scaled Exponential Linear Unit Activation (SELU) Function under TheAlgorithms/Python/neural_network/activation_functions. Description of SELU taken from reference link provided in the top comment section in scaled_exponential_linear_unit.py
Fixes #9010
> Added Scaled Exponential Linear Unit Activation Function

- CONTRIBUTING.md
- data_structures/linked_list/__init__.py
This pull request adds the `add_at_position` function to the linked list implementation. This function allows inserting an item at a specified position within the linked list.
> Added an add at position subroutiune to linked list

- ciphers/base32.py
Fixes #8966
Fixes #8965
See #6216
> Rewrite of base32.py algorithm

- ciphers/base85.py
Fixes #8966
Fixes #8965
See #6216
> Rewrite of base85.py algorithm

- maths/sum_of_two_positive_numbers_bitwise.py
- Add single function to calculate sum of two positive numbers using bitwise operator
> feat(maths): add function to perform calculation

- neural_network/back_propagation_neural_network.py
- strings/knuth_morris_pratt.py
Returning the index of first occurrence of a match in knuth_morris_pratt algorithm. The return type is converted from boolean to int. The function name parameters are aligned to Python naming conventions. 
Fixes #9077
> Returning Index instead of boolean in knuth_morris_pratt (kmp) function, making it compatible with str.find().

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- other/word_search.py
Create a word search algorithm
> Create word search algorithm

- machine_learning/local_weighted_learning/local_weighted_learning.py
Recent build logs (e.g., [this one](https://github.com/TheAlgorithms/Python/actions/runs/6367653954/job/17286407238#step:6:750)) show that `machine_learning/local_weighted_learning/local_weighted_learning.py` produces a DeprecationWarning:
```
machine_learning/local_weighted_learning/local_weighted_learning.py::machine_learning.local_weighted_learning.local_weighted_learning.local_weight_regression
machine_learning/local_weighted_learning/local_weighted_learning.py::machine_learning.local_weighted_learning.local_weighted_learning.local_weight_regression
machine_learning/local_weighted_learning/local_weighted_learning.py::machine_learning.local_weighted_learning.local_weighted_learning.local_weight_regression
/home/runner/work/Python/Python/machine_learning/local_weighted_learning/local_wei …
```
> Fix DeprecationWarning in local_weighted_learning.py

- machine_learning/local_weighted_learning/local_weighted_learning.py
My previous PR #9165 didn't resolve the warning because `np.dot()` was still returning an `np.ndarray` rather than a scalar. I added a `.item()` call to explicitly extract the `np.ndarray`'s scalar entry.
> Fix DeprecationWarning in local_weighted_learning.py (Attempt 2)

- data_structures/binary_tree/binary_tree_traversals.py
Fixes #8725.
Made ```binary_tree_traversals.py``` memory-friendly using generators based travels.
> Made binary_tree_treaversals.py memory-friendly using generators based travels. Fixes #8725

- data_structures/binary_tree/binary_tree_traversals.py
Fixes #8725.
PR #9208 made some changes to ```binary_tee_traversal.py```. This is an extension to that as it extends same method (Generator-based traversal) to other three functions also.
>  binary_search_traversals.py made memory-friendly using generators. Fixes #8725 completely.

- arithmetic_analysis/lu_decomposition.py
- project_euler/problem_072/sol1.py
Application of vector operations  to reduce calculation time and refactoring numpy.
With limit: int = 1_000_000, the calculation of the new algorithm is 40% faster, limit: int = 10_000_000 is almost twice as fast.
<details>
<summary>code test</summary>
```
import datetime
import numpy as np
"""
Problem 72 Counting fractions: https://projecteuler.net/problem=72
Description:
Consider the fraction, n/d, where n and d are positive integers. If n<d and HCF(n,d)=1,
it is called a reduced proper fraction.
If we list the set of reduced proper fractions for d ≤ 8 in ascending order of size, we
get: 1/8, 1/7, 1/6, 1/5, 1/4, 2/7, 1/3, 3/8, 2/5, 3/7, 1/2, 4/7, 3/5, 5/8, 2/3, 5/7,
3/4, 4/5, 5/6, 6/7, 7/8
It can be seen that there are 21 elements in this set.
How many elements would be contained in the …
```
> Euler072 - application of vector operations to reduce calculation time and refactoring numpy

- data_structures/linked_list/reverse_k_group.py
> add reverse k group linkedlist

- .pre-commit-config.yaml
- DIRECTORY.md
% `pre-commit autoupdate`
```
[https://github.com/astral-sh/ruff-pre-commit] updating v0.0.291 -> v0.0.292
[https://github.com/tox-dev/pyproject-fmt] updating 1.1.0 -> 1.2.0
```
% `pre-commit run --all-files`
> pre-commit autoupdate && pre-commit run --all-files

- physics/newtons_law_of_gravitation.py
> Update newtons_law_of_gravitation.py : Typo(Space Removed)

- physics/coulombs_law.py
distance is positive non zero real number (float type) hence corrected docs which says only integer.
> Update coulombs_law.py docs

- data_structures/linked_list/circular_linked_list.py
- data_structures/linked_list/swap_nodes.py
- requirements.txt
Few files does not have any comments so I added it.
> Add Comments

- matrix/median_matrix.py
> add median of matrix

- data_structures/arrays/median_two_array.py
> add median of two sorted array

- physics/photoelectric_effect.py
Photoelectric effect is one of the demonstration of quanta of energy. 
This PR addes algorithm for calculating maximum kinetic energy of photoelectron.
> Added Photoelectric effect equation

- maths/bell_numbers.py
New algorithm for generating Bell numbers.
> [New Algorithm] - Bell Numbers

- hashes/fletcher16.py
> Fletcher 16

- bit_manipulation/largest_pow_of_two_le_num.py
> Added largest_pow_of_two_le_num

- arithmetic_analysis/lu_decomposition.py
- maths/fermat_little_theorem.py
> Fermat_little_theorem type annotation

- greedy_methods/gas_station.py
Added a new algorithm to solve the gas station problem. I added the file `gas_station.py` to the `greedy_methods` directory. I have also added docstrings for the function with an explanation and doctests.
> add gas station

- data_structures/queue/double_ended_queue.py
I found a bug in double_ended_queue.py:
There is an error when popping the queue with only one element.
Code:
```python
dq = Deque([3])
dq.popleft()
```
Error in dq.popleft()
> self._front.prev_node = None
> AttributeError: 'NoneType' object has no attribute 'prev_node'
same as the pop:
code:
```python
dq = Deque([3])
dq.pop()
```
Error in dq.pop()
> self._back.next_node = None
> AttributeError: 'NoneType' object has no attribute 'next_node'
The fixing is to set both front and back pointers to None if there is only one element left in the queue before popping
I have written the test cases in the code and the tests are passed.
> [bug fixing] Edge case of the double ended queue 

- dynamic_programming/largest_divisible_subset.py
> largest divisible subset

- maths/prime_numbers.py
I reduced the test cases, so it will run faster than before.
> Updated prime_numbers.py testcases.

- graphs/deep-clone-graph.py
- graphs/deep_clone_graph.py
> Added algorithm to deeply clone a graph

- electronics/wheatstone_bridge.py
> Added Wheatstone Bridge Algorithm

- divide_and_conquer/strassen_matrix_multiplication.py
> Mention square matrices in strassen docs and make it more clear

- dynamic_programming/minimum_partition.py
> Add doctests, type hints; fix bug for dynamic_programming/minimum_partition.py

- ciphers/fractionated_morse_cipher.py
Added the Fractionated Morse Cipher implementation in Python an added the file `fractionated_morse_cipher.py` to the `ciphers` directory. I have also added references to learn more about the cipher, docstrings for every function with an explanation and doctest.
Fixes #9691
> Added fractionated_morse_cipher

- neural_network/activation_functions/squareplus.py
> Added Squareplus Activation Function

- greedy_methods/best_time_to_buy_and_sell_stock.py
This PR is to add the Best time to buy and sell stock program under greedy methods. 
Fixes #10113
> add : Best time to buy and sell stock program under GREEDY methods

- maths/combinations.py
…
for example:
5 C 3 = 5! / (3! * (5-3)! )
= (5 * 4 * 3 * 2 * 1)/[(3 * 2 * 1) * (2 * 1)]
=(5 * 4 * 3)/(3 * 2 * 1)
so running a loop k times will reduce the time complexity to O(k)
> In place of calculating the factorial several times we can run a loop k times to calculate the combination

- data_structures/arrays/equilibrium_index_in_array.py
> equilibrium index in an array

- neural_network/activation_functions/soboleva_modified_hyperbolic_tangent.py
- neural_network/activation_functions/sobovela_modified_hyperbolic_tangent.py
> Add Soboleva Modified Hyberbolic Tangent function

- DIRECTORY.md
- neural_network/activation_functions/binary_step.py
> Add binary step activation function

- data_structures/linked_list/is_palindrome.py
This PR adds DocTests to the functions in is_palindrome.py to increase its codecoverage from 0% to 96%.
Tested this change locally and can verify that they are passing.
Ref #9943
> Add DocTests to is_palindrome.py

- other/magicdiamondpattern.py
This PR adds DocTests to the functions in is_palindrome.py to increase its codecoverage from 0% to 93%.
Tested this change locally and can verify that they are passing.
Ref #9943
> Add DocTests to magicdiamondpattern.py

- arithmetic_analysis/lu_decomposition.py
- digital_image_processing/test_digital_image_processing.py
Replaced lena.jpg with lena_small.jpg to make tests faster.
pull request 10161 before:
`file_path = "digital_image_processing/image_data/lena.jpg"`
after: 
`file_path = "digital_image_processing/image_data/lena_small.jpg"`
> test_digital_image_processing -> test_local_binary_pattern replacing a large image with a smaller one

- maths/chebyshev_distance.py
> Added the Chebyshev distance function

- maths/minkowski_distance.py
> Added the Minkowski distance function

- arithmetic_analysis/lu_decomposition.py
- backtracking/word_search.py
Contributes to https://github.com/TheAlgorithms/Python/issues/9718
I replaced  in this pull request 10188, the example in doctest with a less resource-intensive.
Before:
```
>>> word_exists([["A","A","A","A","A","A"],
...              ["A","A","A","A","A","A"],
...              ["A","A","A","A","A","A"],
...              ["A","A","A","A","A","A"],
...              ["A","A","A","A","A","B"],
...              ["A","A","A","A","B","A"]],
...             "AAAAAAAAAAAAABB")
False
```
After:
```
>>> word_exists([["B", "A", "A"], ["A", "A", "A"], ["A", "B", "A"]], "ABB")
False
```
> backtracking -> word_search - replacing the example in doctest

- maths/number_of_digits.py
> TypeError for non-integer input 

- physics/reynolds_number
- physics/reynolds_number.py
> Added the algorithm to compute Reynolds number in the physics section

- machine_learning/loss_functions/categorical_cross_entropy.py
Added `categorical_cross_entropy.py` in `machine_learning/loss_functions`
> Added categorical_crossentropy loss function

- arithmetic_analysis/gaussian_elimination.py
- arithmetic_analysis/lu_decomposition.py
Contributes to #9718.
before: `x[row, 0] = (vector[row] - total) / coefficients[row, row]`
after: `x[row, 0] = (vector[row][0] - total[0]) / coefficients[row, row]`
Remove warning: 
```
arithmetic_analysis/gaussian_elimination.py: 10 warnings
/home/runner/work/Python/Python/arithmetic_analysis/gaussian_elimination.py:37: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
x[row, 0] = (vector[row] - total) / coefficients[row, row]
```
> Gaussian_elemination - change to remove warning

- data_structures/stacks/infix_to_prefix_conversion.py
> Add tests for infix_2_postfix() in infix_to_prefix_conversion.py

- maths/primelib.py
> Add doctests to primelib.py

- data_structures/stacks/infix_to_prefix_conversion.py
> Fix bug and edit doctests for infix_to_prefix_conversion

- .pre-commit-config.yaml
- DIRECTORY.md
- blockchain/diophantine_equation.py
- ciphers/xor_cipher.py
- conversions/decimal_to_hexadecimal.py
- data_structures/binary_tree/binary_search_tree_recursive.py
- data_structures/hashing/tests/test_hash_map.py
- data_structures/linked_list/circular_linked_list.py
- digital_image_processing/test_digital_image_processing.py
- graphs/graph_adjacency_list.py
- graphs/graph_adjacency_matrix.py
- hashes/sha256.py
- knapsack/tests/test_greedy_knapsack.py
- knapsack/tests/test_knapsack.py
- linear_algebra/src/lib.py
- linear_algebra/src/schur_complement.py
- linear_algebra/src/test_linear_algebra.py
- machine_learning/dimensionality_reduction.py
- machine_learning/k_means_clust.py
- maths/least_common_multiple.py
- maths/modular_division.py
- maths/prime_check.py
- matrix/sherman_morrison.py
- matrix/tests/test_matrix_operation.py
- project_euler/problem_054/test_poker_hand.py
- pyproject.toml
- strings/knuth_morris_pratt.py
- strings/rabin_karp.py
* https://docs.astral.sh/ruff/rules/#pandas-vet-pd
* https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
---
> Add Ruff rules for pandas-vet and pytest-style

- maths/carmichael_number.py
Related to
* #9943 
Added Doctests to Carmichael_number.py
> Add doctests to carmichael_number.py

- financial/exponential_moving_average.py
> Adds exponential moving average algorithm

- boolean_algebra/imply_gate.py
Added imply gate to boolean algebra.
> Added imply gate to boolean algebra

- maths/solovay_strassen_primality_test.py
> Add Solovay-Strassen Primality test

- strings/damerau_levenshtein_distance.py
> Add Damerau-Levenshtein distance algorithm

- strings/lower.py
> Modified comments on lower.py

- strings/title.py
convert lower or upper case string to title case
> Add Title Case Conversion

- project_euler/problem_145/sol1.py
> Performance: 80% faster Project Euler 145

- strings/upper.py
Updated Comments on upper.py for better understanding.
> Updated Comments on upper.py

- requirements.txt
Disable unused dependencies in `requirements.txt` to try to reduce build times:
- Keras is a TensorFlow frontend, so I've also marked it as `python_version < '3.12'`. There's no reason to install Keras in every build when TensorFlow can't be used.
- projectq, scikit-fuzzy, and yulewalker are only used by broken (and thus disabled) files, so I've commented them out. If/when those broken files are fixed, we can uncomment them.
> Disable unused dependencies

- maths/rkf45.py
Add an algorithm (rkf45) to TheAlgorithms / Python/maths
> added rkf45 method

- project_euler/problem_187/sol1.py
> Performance: 75% faster Project Euler 187

- pyproject.toml
Our current `pytest` command for our builds is the following:
```
pytest --ignore=quantum/q_fourier_transform.py --ignore=project_euler/ --ignore=scripts/validate_solutions.py --cov-report=term-missing:skip-covered --cov=. .
```
Since we're not testing files in the `project_euler/` or `scripts/` directories, we should exclude them from our builds' coverage reports as well. `project_euler/` files in particular significantly clutter the reports.
> Omit `project_euler/` from coverage reports

- data_structures/stacks/stack_using_two_queues.py
> added implementing stack using two queues

- dynamic_programming/wildcard_matching.py
- maths/solovay_strassen_primality_test.py
This PR adds the wildcard matching program under dynamic programming.
Wildcard Matching :
> [Add] : Wildcard Matching program under DYNAMIC PROGRAMMING

- dynamic_programming/subset_generation.py
Changes the code to return the tuples. So, we can add doctests in it after it. Change the whole code now code using dynamic programming as it header says
#10189
> Changes the code To return the list in dynamic_programming/subset_generation.py

- DIRECTORY.md
- dynamic_programming/matrix_chain_multiplication.py
P.s. I would like to add that I started by trying to add doctests to matrix_chain_order.py script under Python/dynamic_programming/matrix_chain_order in order to improve its test coverage. However, I found the functions poorly written. Instead of changing the code, I have written a separate script with bug free code, problem explanation and required doctests. Moderators may consider deleting matrix_chain_order.py. Creating new PR by deleting #10549 and #10561.
> Dynamic programming/matrix chain multiplication

- sorts/tree_sort.py
Related to https://github.com/TheAlgorithms/Python/issues/9943
> add tests for tree_sort

- maths/volume.py
Added function to find volume of a regular Icosahedron
Added the functionality of finding the volume of a regular Icosahedron which is a convex polyhedron with 20 faces, 30 edges and 12 vertices. It is one of the five Platonic solids.
Wikipedia Reference: https://en.wikipedia.org/wiki/Regular_icosahedron
> Update volume.py with volume of Icosahedron

- boolean_algebra/and_gate.py
- boolean_algebra/imply_gate.py
- boolean_algebra/nand_gate.py
- boolean_algebra/nimply_gate.py
- boolean_algebra/not_gate.py
- boolean_algebra/or_gate.py
- boolean_algebra/xnor_gate.py
- boolean_algebra/xor_gate.py
Turned tests into doctests in the Boolean Algebra section for consistency and as an improved way of testing.
> Converted tests into doctests

- arithmetic_analysis/lu_decomposition.py
Replacing the generator on numpy vector operations from [lu_decomposition.](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/lu_decomposition.py)
before: `total = sum(lower[i][k] * upper[k][j] for k in range(j))`
after: `total = np.sum(lower[i, :i] * upper[:i, j])`
In 'total', the necessary data is extracted through slices and the sum of the products is obtained.
Moreover, as the array size increases, the ratio of the calculation time of the original algorithm 
growing towards the new. As a result, with an array size of n x n 1000, the calculation time for the 
original algorithm is almost 7 minutes, and the new one is 12 seconds(time in tests is seconds).
The tests generate n x n arrays. To prevent it from triggering:
`raise ArithmeticError("No LU decomposition …
> Refactoring and optimization of the lu_decomposition algorithm

- maths/armstrong_numbers.py
The while loop is removed and simple length calculation is used so the task of minimization of while loop is achieved
> Minimization of while loop in Armstrong Numbers

- DIRECTORY.md
- sorts/tree_sort.py
This test runs superfast on my M1 Mac but takes 5+ sec on GitHub Actions!
> Tree_sort.py: Disable slow doctest

- data_structures/binary_tree/segment_tree.py
* [x ] This pull request is all my own work -- I have not plagiarized.
* [x ] I know that pull requests will not be merged if they fail the automated tests.
* [x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x] All filenames are in all lowercase characters with no spaces or dashes.
* [x ] All functions and variable names follow Python naming conventions.
* [ x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ x] All functions have …
> update segmenttree docstrings Fixes #9943

- conversions/octal_to_hexadecimal.py
…ectory
Added Octal Number to Hexadecimal Number Conversion Algorithm under 'conversions' directory
> Hacktoberfest: Added Octal Number to Hexadecimal Number Conversion Algorithm

- backtracking/all_combinations.py
Fixes #9943. More test cases and documentation addition to clarify inputs
> Test cases for all_combinations

- strings/is_polish_national_id.py
The algorithm to validate Polish ID number (PESEL). 
It verifies:
- overall range of numbers
- day, month and century designation
- checksum
all according to government documentation. Direct PR, no issue assigned.
> feat: Polish ID (PESEL) checker added

- financial/exponential_moving_average.py
- machine_learning/loss_functions/hinge_loss.py
- Adding Hinge loss function which is useful loss function in Support Vector Machine (SVM) for calculating loss.
> Adds hinge loss function algorithm

- strings/edit_distance.py
Added an algorithm to perform string matching using Edit Distance Algorithm.
Helps to find the minimum number of operations to move from one string to another.
* [ x] Add an algorithm?
> Edit Distance Algorithm for String Matching

- machine_learning/loss_functions/mean_squared_logarithmic_error.py
I have added MSLE loss function which is very useful when dealing with regression problems involving skewed or large-value targets.
> Added Mean Squared Logarithmic Error (MSLE) Loss Function

- graphs/basic_graphs.py
*added docstring and doctest for edglist
*added docstring and doctest for adjm
Contributes to #9943
> Add doctest to graphs/basic_graphs.py

- DIRECTORY.md
- machine_learning/fp_growth.py
- machine_learning/frequent_pattern_growth.py
Added FP Growth Algorithm for finding frequent Itemset.
> Add: FP Growth Algorithm

- physics/center_of_mass.py
> adding new physics algorithm: center of mass

- DIRECTORY.md
- conversions/time_conversions.py
This PR add the Time unit conversion function. 
[chart source](https://en.wikipedia.org/wiki/Unit_of_time)
> Add: Time Conversion Function

- backtracking/n_queens.py
Enhanced readability and added comments to the `n_queens.py` code. Replaced repeated `len(board)` with a single variable `n` for efficiency in the `is_safe` function.
This pull request improves the readability of the `n_queens.py` code and optimizes the `is_safe` function by replacing repeated calls to `len(board)` with a single variable `n`. These changes make the code more understandable and efficient.
> Enhance readability of N Queens

- ciphers/playfair_cipher.py
Contributes to #9943 
1) Added description of cipher to playfair_cipher.py
2) Added doctests to playfair_cipher.py
> added doctest to playfair_cipher.py

- sorts/double_sort.py
- Don't need to return list because list is mutable
- use advantage of python in swapping
- filter blank inputs from input list
- minor changes
> code enhancement in `sort.double_sort`

- financial/simple_moving_average.py
This commit adds a Python script for calculating the Simple Moving Average (SMA) of a time series data.
The script also includes a doctest that verifies the correctness of the SMA calculations for a sample dataset.
Usage:
- Run the script with your own time series data and specify the window size for SMA calculations.
> Add Simple Moving Average (SMA) Calculation

- backtracking/minimax.py
Added function docstring and comments explaining the base case, maximizer and minimizer turns.
> Enhance readability of Minimax

- data_structures/linked_list/floyds_cycle_detection.py
Add new algorithm for detecting the cycle in a linked list.
> Add Floyd's Cycle Detection Algorithm

- conversions/rgb_cmyk_conversion.py
Popular RGB to CMYK conversion algorithm. Accepts RGB values, returns percentages of CMYK paint.
Direct PR, no Issue created.
> feat: RGB to CMYK color converter

- other/nested_brackets.py
> Added doctests , type hints for other/nested_brackets.py

- maths/binomial_coefficient.py
Added few changes in the binomial_coefficient
> Tried new TESTS for the binomial_coefficient

- networking_flow/ford_fulkerson.py
Enhance the code by including function docstrings, comments, and type hints to improve readability, documentation, and code understanding.
* [] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".
> Add function docstrings, comments and type hints

- sorts/binary_insertion_sort.py
> Code enhancements in binary_insertion_sort.py

- data_structures/binary_tree/binary_search_tree.py
Add dataclasses to binary_search_tree.py
* Adds tests but does not modify or delete existing tests.
---
> Add dataclasses to binary_search_tree.py

- maths/prime_check.py
Despite is_prime() already having an error message for invalid inputs, the doctest doesn't include any tests displaying invalid inputs. This PR adds two examples which cover this and also rephrases the error message for more consistent grammar.
> Add error tests in doctest and fix error message

- graphs/tarjans_scc.py
> Add doctests and type hints

- maths/numerical_analysis/runge_kutta_gills.py
> added runge kutta gills method to maths/ numerical_analysis

- physics/lens_formulae.py
* [] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".
> Added Lens formulae to the Physics repository

- computer_vision/haralick_descriptors.py
> Fix typo in haralick_descriptors.py

- data_structures/hashing/hash_table.py
> Added doctest to hash_table.py

- CONTRIBUTING.md
> Fix Typo & Grammatical Errors in CONTRIBUTING.md

- data_structures/hashing/quadratic_probing.py
> Added doctest & docstring to quadratic_probing.py

- machine_learning/loss_functions.py
- Perplexity loss function which is used in NLP (Natural language processing) for finding accuracy of the model based on how much certain the model is on its predictions.
> Add perplexity loss algorithm

- data_structures/hashing/double_hash.py
> Added doctest to double_hash.py

- graphs/dijkstra_algorithm.py
Ref #9943 
Add doctests to `dijkstra_algorithm.py` to improve code coverage
Bug fixed where required to execute and pass doctests
Moved method declaration comments to doc strings for methods doc strings are added to for the doctests
> Code coverage improved from `16%` to `85%` (or `100%` when not including the main block)
> Increase code coverage for dijkstra algorithm

- sorts/odd_even_transposition_parallel.py
Contributes to #9943. It should be noted that there is currently a bug in this algo as described in https://github.com/TheAlgorithms/Python/issues/10925. Will fix in a separate PR after this gets merged.
> Tests for odd_even_transposition_parallel

- hashes/hamming_code.py
Added a doctest to hashes/hamming_code.py to increase test coverage to 100%
> Add a doctest to hashes/hamming_code.py

- machine_learning/gradient_boosting_classifier.py
> Added Gradient Boosting Classifier

- data_structures/heap/heap.py
> Added doctest to heap.py

- pyproject.toml
- strings/bitap_string_match.py
> Add bitap_string_match algo

- maths/integer_square_root.py
Implemented the Integer Square Root algorithm for efficiently calculating the square root of a non-negative integer 'x' rounded down to the nearest integer. The algorithm uses binary search to find the integer square root without using any
built-in exponent functions or operators.
> Add Integer Square Root Algorithm

- ciphers/running_key_cipher.py
Add algorithm for running key cipher, reference link: [Running key cipher](http://practicalcryptography.com/ciphers/classical-era/running-key/)
> Add running key cipher

- maths/josephus_problem.py
> Add Josephus Problem

- data_structures/binary_tree/serialize_deserialize_binary_tree.py
> serialize deserialize binary tree

- machine_learning/decision_tree.py
> Added doctest to decision_tree.py

- data_structures/binary_tree/binary_search_tree.py
> Added doctest to binary_search_tree.py

- strings/string_switch_case.py
> Added doctest to string_switch_case.py

- data_structures/heap/randomized_heap.py
> Added doctest to randomized_heap.py

- data_structures/stacks/stack.py
> Added doctest to stack.py

- graphs/ant_colony_optimization_algorithms.py
A simple example uses the ant colony optimization algorithm to solve the classic TSP problem.
> add graphs/ant_colony_optimization_algorithms.py

- backtracking/all_combinations.py
Input Validation: Added checks to handle cases where `n` or `k` are negative or where `k` is greater than `n`. In such scenarios, the function now returns an empty list, avoiding invalid recursive calls.
> Bug fix combinations

- .github/workflows/build.yml
- web_programming/get_top_billionaires.py
The doc-tests of [`calculate_age`](https://github.com/TheAlgorithms/Python/blob/9caf4784aada17dc75348f77cc8c356df503c0f3/web_programming/get_top_billionaires.py#L23) can fail depending on _current time_ - all of the builds fail now (i.e. 01.2024). I suggest to simplify the `calculate_age` in such a way, that it will not take months into account (in general: _the test is a specification of the function_, so such approach is justified).
When this will be merged, I will _rebase_ #11233, so the CI there will pass.
> fix: consider months and days in `years_old`

- .github/workflows/build.yml
- .github/workflows/ruff.yml
- .pre-commit-config.yaml
[`ruff.yml`](https://github.com/TheAlgorithms/Python/blob/ffb93adf46971be35699e7642d79e90284b3c7f1/.github/workflows/ruff.yml#L14) has some bad indentation. This PR fixes it.
> style: use proper indentation in `ruff.yml`

- .github/.github/dependabot.yml
- .pre-commit-config.yaml
- audio_filters/butterworth_filter.py
- conversions/convert_number_to_words.py
- digital_image_processing/filters/gabor_filter.py
- graphs/eulerian_path_and_circuit_for_undirected_graph.py
- physics/n_body_simulation.py
- project_euler/problem_056/sol1.py
https://docs.astral.sh/ruff/formatter
> Use ruff format as the pre-commit formatter

- data_structures/heap/skew_heap.py
> Added doctest to skew_heap.py

- machine_learning/loss_functions.py
- Categorical focal cross-entropy (CFCE) loss is a generalization of binary focal cross-entropy for multi-class classification. It addresses class imbalance by focusing on hard examples.
> Add categorical focal cross-entropy loss algorithm

- machine_learning/loss_functions.py
- The [Smooth L1 Loss](https://pytorch.org/docs/stable/generated/torch.nn.SmoothL1Loss.html#torch.nn.SmoothL1Loss) is less sensitive to outliers than the L2 Loss and is often used in regression problems, such as object detection.
> Add smooth l1 loss algorithm

- fractals/vicsek.py
> Add Vicsek to fractals

- DIRECTORY.md
- other/gauss_easter.py
- pyproject.toml
> Enable ruff DTZ001 rule

- other/gauss_easter.py
- pyproject.toml
- web_programming/instagram_pic.py
- web_programming/instagram_video.py
> Enable ruff DTZ005 rule

- data_structures/binary_tree/binary_tree_traversals.py
Added doctests for the functions: level_order, get_nodes_from_left_to_right, get_nodes_from_right_to_left, and zigzag.
> Added some doctests in binary_tree_traversal.py

- backtracking/crossword_puzzle_solver.py
- cellular_automata/game_of_life.py
- ciphers/decrypt_caesar_with_chi_squared.py
- data_structures/binary_tree/avl_tree.py
- data_structures/binary_tree/binary_search_tree.py
- data_structures/binary_tree/binary_search_tree_recursive.py
- data_structures/binary_tree/red_black_tree.py
- data_structures/binary_tree/treap.py
- data_structures/heap/max_heap.py
- data_structures/stacks/infix_to_prefix_conversion.py
- data_structures/trie/radix_tree.py
- divide_and_conquer/convex_hull.py
- graphs/graph_list.py
- graphs/minimum_spanning_tree_prims.py
- graphs/multi_heuristic_astar.py
- machine_learning/forecasting/run.py
- maths/largest_of_very_large_numbers.py
- maths/pollard_rho.py
- matrix/cramers_rule_2x2.py
- project_euler/problem_019/sol1.py
- pyproject.toml
- searches/hill_climbing.py
- searches/interpolation_search.py
- strings/min_cost_string_conversion.py
> Enable ruff PLR5501 rule

- audio_filters/butterworth_filter.py
- data_structures/binary_tree/basic_binary_tree.py
- data_structures/binary_tree/non_recursive_segment_tree.py
- data_structures/binary_tree/red_black_tree.py
- data_structures/binary_tree/segment_tree.py
- data_structures/heap/min_heap.py
- dynamic_programming/longest_common_subsequence.py
- dynamic_programming/longest_increasing_subsequence_o_nlogn.py
- graphs/articulation_points.py
- graphs/dinic.py
- other/sdes.py
- project_euler/problem_011/sol2.py
- pyproject.toml
- strings/manacher.py
> Enable ruff RUF100 rule

- data_structures/arrays/sudoku_solver.py
- data_structures/stacks/balanced_parentheses.py
- graphs/a_star.py
- graphs/bi_directional_dijkstra.py
- other/davis_putnam_logemann_loveland.py
- project_euler/problem_033/sol1.py
- project_euler/problem_037/sol1.py
- project_euler/problem_107/sol1.py
- project_euler/problem_207/sol1.py
- pyproject.toml
- scheduling/shortest_job_first.py
- scripts/validate_solutions.py
- web_programming/emails_from_url.py
> Enable ruff SIM102 rule

- pyproject.toml
- web_programming/recaptcha_verification.py
> Enable ruff S105 rule

- electronics/circular_convolution.py
- neural_network/activation_functions/mish.py
- pyproject.toml
- requirements.txt
> Enable ruff INP001 rule

- data_structures/binary_tree/binary_search_tree.py
- dynamic_programming/subset_generation.py
- maths/odd_sieve.py
- pyproject.toml
> Enable ruff RUF005 rule

- compression/huffman.py
- data_structures/binary_tree/binary_search_tree.py
- data_structures/linked_list/rotate_to_the_right.py
- fractals/mandelbrot.py
- graphics/bezier_curve.py
- maths/entropy.py
- matrix/spiral_print.py
- matrix/tests/test_matrix_operation.py
- project_euler/problem_092/sol1.py
- project_euler/problem_104/sol1.py
- pyproject.toml
- scripts/validate_filenames.py
- scripts/validate_solutions.py
- web_programming/covid_stats_via_xpath.py
- web_programming/recaptcha_verification.py
> Enable ruff PGH003 rule

- pyproject.toml
> Do not fix ruff EXE001 rule

- data_structures/queue/circular_queue.py
- data_structures/queue/circular_queue_linked_list.py
> Added documentations

- data_structures/binary_tree/non_recursive_segment_tree.py
- data_structures/binary_tree/segment_tree.py
- data_structures/heap/min_heap.py
- dynamic_programming/longest_common_subsequence.py
- dynamic_programming/longest_increasing_subsequence_o_nlogn.py
- graphs/articulation_points.py
- graphs/dinic.py
- machine_learning/sequential_minimum_optimization.py
- maths/pi_generator.py
- other/sdes.py
- project_euler/problem_011/sol2.py
- pyproject.toml
- strings/jaro_winkler.py
- strings/manacher.py
> Enable ruff E741 rule

- genetic_algorithm/basic_string.py
> Add doctests in all functions in basic_string.py

- fuzzy_logic/fuzzy_operations.py
- physics/basic_orbital_capture.py
- physics/malus_law.py
- pyproject.toml
> Enable ruff RUF001 rule

- dynamic_programming/fast_fibonacci.py
- graphs/ant_colony_optimization_algorithms.py
- machine_learning/polynomial_regression.py
- pyproject.toml
- strings/credit_card_validator.py
> Enable ruff RUF003 rule

- machine_learning/linear_discriminant_analysis.py
- pyproject.toml
> Fix ARG005 per file ignore

- data_structures/arrays/sudoku_solver.py
- neural_network/input_data.py
> Enable ruff UP031 rule

- matrix/matrix_equalization.py
Adding a matrix equalization algorithm, which equalizes all elements of the input vector to a common value, by making the minimal number of "updates" under the constraint of a step size (k).
This algorithm has practical use in scenarios where you need to achieve uniformity across elements of an array under specific constraints and with minimal changes. For example:
- resource allocation (this algorithm provides a way to complete the task efficiently)
- game theory (this algorithm may help in devising fair strategies using minimal moves)
- signal processing (the algorithm might be applied where signal adjustments are constrained by step size).
> adding a matrix equalization algorithm

- sorts/odd_even_transposition_parallel.py
Set the start method to `spawn` before any multiprocess context is read.
Resolves: https://github.com/TheAlgorithms/Python/pull/769#issuecomment-2088985744
cc @cclauss
> Use `spawn` start method in multiprocessing programs

- bit_manipulation/binary_and_operator.py
> use format to remove '0b'

- machine_learning/sequential_minimum_optimization.py
#11150 
Ensure explicit column selection and data type setting in data reading process.
> issue #11150 Ensure explicit column selection and data type setting in data reading process.

- backtracking/all_permutations.py
- backtracking/all_subsequences.py
Added doctest test cases for `backtracking/all_permutations.py` and `backtracking/all_subsequences.py`
> Fixes #9943

- physics/rainfall_intensity.py
> Add rainfall intensity calculation function

- computer_vision/haralick_descriptors.py
- graphs/strongly_connected_components.py
- maths/points_are_collinear_3d.py
- neural_network/convolution_neural_network.py
> chore: fix typos

- searches/interpolation_search.py
Contributes to https://github.com/TheAlgorithms/Python/issues/9943
> Add doctests to interpolation_search.py

- scripts/close_pull_requests_with_awaiting_changes.sh
- scripts/close_pull_requests_with_failing_tests.sh
- scripts/close_pull_requests_with_require_descriptive_names.sh
- scripts/close_pull_requests_with_require_tests.sh
- scripts/close_pull_requests_with_require_type_hints.sh
Each year we prepare for Hacktoberfest by clearing out old pull requests to simplify things for project maintainers.
We had 211 open pull requests; after running these scripts, we have 126.  ~40% of our Open PRs were closed.
@MaximSmolskiy Your review, please.
> Scripts for closing pull requests for Hacktoberfest

- DIRECTORY.md
- backtracking/word_ladder.py
Implemented the **Word Ladder** algorithm in the **Backtracking** folder.
The **Word Ladder** problem involves transforming a start word into a target word by changing one letter at a time, where each intermediate word must be a valid word from a given list. The challenge is to find a transformation sequence from the start word to the end word. In this backtracking approach, we attempt to explore all possible transformations, ensuring that each transformation is valid and leading us towards the end word.
1. Start with the `begin_word` and recursively explore all valid transformations.
2. At each step, change one letter at a time to generate new words.
3. If the transformation results in the `end_word`, the process is complete, and the transformation sequence is returned.
4. If no …
> Add word ladder algorithm in backtracking

- data_structures/binary_tree/symmetric_tree.py
The code was improved by enhancing the docstrings for all functions and adding detailed explanations of parameters, return values, and procedures. Doctests were included to validate the correctness of each function, following the `ruff` specifications. The `Node` class now includes an example of usage, demonstrating how to create nodes and access their attributes. The `make_symmetric_tree` and `make_asymmetric_tree` functions were updated with doctests to ensure the trees are constructed correctly. Additional tests were added for `is_symmetric_tree` and `is_mirror`, showcasing how these functions behave with both symmetric and asymmetric trees.
> Improve comments, add doctests in symmetric_tree.py

- data_structures/linked_list/has_loop.py
`visited` variable is declared as a `list`, hence `node in visited` takes a TC of O(n). This issue is fixed by declaring `visited` as a `set` reducing the lookup TC to O(1).
> Updated has_loop lookup from O(n) to O(1)

- backtracking/word_break.py
The **Word Break Problem** determines if a given string can be segmented into valid dictionary words. It uses a backtracking approach to explore all possible segmentations and ensures an optimal, non-greedy solution. The algorithm is implemented with proper type hints, docstrings, and doctests to conform to the repository's standards.
> Add Word Break algorithm

- graphs/kahns_algorithm_topo.py
The improvements to the code include adding a more detailed **docstring** that explains the purpose, **parameters,** return values, and the use of **Kahn's Algorithm** for topological sorting. The docstring now includes doctests, providing example usage and **handling edge cases** such as graphs with cycles. Inline comments clarify key steps like indegree calculation, queue initialization, and the BFS process. Additionally, explicit handling and explanation of cycle detection were added, making the code more readable and understandable while ensuring that it is easy to validate using the provided test cases.
> Improve comments, add doctests for kahns_algorithm_topo.py

- data_structures/binary_tree/symmetric_tree.py
- strings/min_cost_string_conversion.py
I added doctests to the min_cost_string_conversion.py in the strings directory file as part of Hacktoberfest 2024 contributions. I also made a small change to the code by removing the ':c' specifier which made the code fail to run, and seemed necessary only if used on integers for unicode converson, not strings. 
This PR contributes to #9943.
> Added doctests to min_cost_string_conversion.py and removed :c specifier

- data_structures/stacks/lexicographical_numbers.py
> Added new algorithm to generate numbers in lexicographical order

- linear_algebra/src/polynom_for_points.py
- Add test cases of the polynom_for_points one of the linear algebra algorithms and coverage increase by 5%
> feat: add testcase of polynom_for_points

- data_structures/binary_tree/max_sum_BST.py
- data_structures/binary_tree/maximum_sum_bst.py
> Added max_sum_bst.py

- ciphers/gronsfeld_cipher.py
Added a new file in the ciphers directory implementing the Gronsfeld cipher encryption as part of my contribution to Hacktoberfest 2024.  Encryption is based on a numeric key as opposed to letters used in a Vigenere cipher.
> added gronsfeld cipher implementation

- ciphers/autokey.py
- Add test cases in cipher's autokey algorithms and increase the coverage by around 10%
> feat: add test cases in cipher's autokey

- scripts/find_git_conflicts.sh
> Add scripts/find_git_conflicts.sh

- .github/workflows/build.yml
- .github/workflows/project_euler.yml
- .github/workflows/ruff.yml
- .github/workflows/sphinx.yml
- .pre-commit-config.yaml
- pyproject.toml
- requirements.txt
- uv.lock
> Use Astral uv

- physics/horizontal_projectile_motion.py
Fix sphinx/build_docs warnings for physics/horizontal_projectile_motion
> Fix sphinx/build_docs warnings for physics/horizontal_projectile_motion

- graphs/check_bipatrite.py
Fix sphinx/build_docs warnings for graphs/check_bipatrite
> Fix sphinx/build_docs warnings for graphs/check_bipatrite

- data_structures/binary_tree/mirror_binary_tree.py
Fix sphinx/build_docs warnings for data_structures/binary_tree/mirror_binary_tree
> Fix sphinx/build_docs warnings for data_structures/binary_tree/mirror_binary_tree

- maths/special_numbers/bell_numbers.py
- maths/special_numbers/hamming_numbers.py
- maths/special_numbers/harshad_numbers.py
> #9943 Improve coverage special_numbers

- machine_learning/linear_regression.py
> Added test to linear regression #9943

- electronics/electric_power.py
> adding test to electronics/electric_power.py #9943

- linear_algebra/src/lib.py
> compare-method added to Vector class in lib.py

- strings/split.py
This pull request includes enhancements to the `split` function in the `strings/split.py` file to handle cases where the separator appears at the end of the input string. The most important changes include adding new test cases and modifying the function logic to append an empty string when the input string ends with the separator.
Enhancements to `split` function:
* [`strings/split.py`](diffhunk://#diff-5392b2ff300ccd1d0e76c32d21b63fbc21e6a473f7b0aa15910f20a11fa4338bR17-R19): Added a test case for input strings where the separator appears at the beginning and end of the string.
* [`strings/split.py`](diffhunk://#diff-5392b2ff300ccd1d0e76c32d21b63fbc21e6a473f7b0aa15910f20a11fa4338bR31-L33): Modified the function logic to append an empty string to the result list if the input string ends …
> Fix split function to handle trailing delimiters correctly

- strings/join.py
The issue was that join() function was not working as the join method of string due to strip method which truncates from end 
now whenever we have empty strings in our separated list it was just adding multiple terminator and all the terminator where getting strip which was different form the join method so a for loop was run for the entire list except the last element in which case it just add the last element and it also take care of the case when the list is empty
It fixes the bug in the join.py file
Fixes #12408
> fixed the issue in strings/join.py

- physics/newtons_second_law_of_motion.py
Fix sphinx/build_docs warnings for physics/newtons_second_law_of_motion
> Fix sphinx/build_docs warnings for physics/newtons_second_law_of_motion

- maths/zellers_congruence.py
Fix sphinx/build_docs warnings for maths/zellers_congruence
> Fix sphinx/build_docs warnings for maths/zellers_congruence

- physics/speeds_of_gas_molecules.py
Fix sphinx/build_docs warnings for physics/speeds_of_gas_molecules
> Fix sphinx/build_docs warnings for physics/speeds_of_gas_molecules

- maths/is_ip_v4_address_valid.py
> fix is_ip_v4_address_valid.py

- web_programming/current_stock_price.py
> current_stock_price test added #9943 

- dynamic_programming/all_construct.py
- dynamic_programming/combination_sum_iv.py
- dynamic_programming/fizz_buzz.py
- dynamic_programming/knapsack.py
- dynamic_programming/longest_common_substring.py
- dynamic_programming/longest_increasing_subsequence.py
- dynamic_programming/matrix_chain_multiplication.py
- dynamic_programming/max_product_subarray.py
- dynamic_programming/minimum_squares_to_represent_a_number.py
- dynamic_programming/regex_match.py
- dynamic_programming/rod_cutting.py
- dynamic_programming/subset_generation.py
- dynamic_programming/viterbi.py
Fix sphinx/build_docs warnings for dynamic_programming
> Fix sphinx/build_docs warnings for dynamic_programming

- graphs/lanczos_eigenvectors.py
Fixes: #12386
This pull request introduces a new algorithm for approximating the largest eigenvalues and eigenvectors of a symmetric matrix in the context of graphs, using the Lanczos method. The implementation leverages adjacency list representation to handle sparse graphs effectively and includes the following:
**Initial Commit: Add Lanczos Eigenvector Algorithm for Graph-based Eigenvalue Computation**
- Implemented `find_lanczos_eigenvectors` for efficient computation of k-largest eigenvalues and eigenvectors in sparse graphs.
- Developed `lanczos_iteration` for constructing tridiagonal matrices.
- Added `multiply_matrix_vector` for efficient adjacency-list matrix-vector multiplication.
- Ensured code meets PEP 8 standards and passed `ruff` linting.
- Included a comprehensive …
> Lanczos Eigenvector

- data_structures/arrays/monotonic_array.py
Contributes to #9943
Addeded doctest in the if __name__. Checks for negaitves and an array of same integers
Added a call to doctest in tests. Added test for all same integers. Added tests for negatives.
> Contributes to #9943 by adding tests to monotonic_array.py

- sorts/heap_sort.py
related to https://github.com/TheAlgorithms/Python/issues/9528
> add some documentation for heap sort

- dynamic_programming/longest_increasing_subsequence.py
Fix #12510 
* [✔] Fix a bug or typo in an existing algorithm?
* [✔] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [✔] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [✔] This pull request is all my own work -- I have not plagiarized.
* [✔] I know that pull requests will not be merged if they fail the automated tests.
* [✔] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [✔] All new Python files are placed inside an existing directory.
* [✔] All filenames are in all lowercase characters with no spaces or dashes.
* [✔] All functions and variable names follow Python naming conventions.
* [✔] All function parameters and …
> Fix #12510

- graphics/butterfly_pattern.py
- graphics/test_butterfly_pattern.py
> Add butterfly pattern implementation #12151

- other/doomsday.py
Replace `!=` in `(year % 400) != 0` (line 49) with `==`
Justification: Years that are divisible by 100 (centurian == 100) but not by 400 (year % 400 != 0) are skipped and NOT leap year.
> Doomsday Algorithm: Fix leap year check

- data_structures/binary_tree/avl_tree.py
Fix #11502 
The fix addresses the issue where the left and right child nodes were not being properly updated after a deletion operation in the AVL tree. By adding lines to refetch these child nodes, the AVL tree maintains correct balancing and node references.
> Fix issue #11502 Error in del_node function

- backtracking/n_queens.py
Fix wrong solution for n-queens problem which in backtrace folder.
There is an issue about **n_queens.py**.  If I run this script, it will print the wrong result which is different with **n_queens_math.py**. I think it's enough to check  **left upper diagonal**,  **right upper diagonal** and **the same column** here. Here are the last few lines of the correct output with my changes:
```bash
. . . . . . . Q
. . . Q . . . .
Q . . . . . . .
. . Q . . . . .
. . . . . Q . .
. Q . . . . . .
. . . . . . Q .
. . . . Q . . .
The total number of solutions are: 92
```
> Fix n-queens problem

- genetic_algorithm/basic_string.py
- Multi-threading (despite being commented out) had a tiny bug: missing target argument (2nd argument).
- Commented out code was also slightly hard to understand, added (Option 1/2) in comments to clarify where a user may choose between 2 implementations.
> Genetic Algorithm: Fix bug in multi-threading

- data_structures/stacks/prefix_evaluation.py
- **prefix_evaluation: Add alternative recursive implementation**
- **improve doc**
- **better variable name calc->operators**
> prefix_evaluation: Add alternative recursive implementation

- data_structures/linked_list/doubly_linked_list_two.py
Related to #12647
Bug was when calling `insert_at_position` method on empty list
```
239 >>> linked_list = LinkedList()
240 >>> linked_list.insert_at_position(position=1, value=10)
UNEXPECTED EXCEPTION: AttributeError("'NoneType' object has no attribute 'next'")
```
> Fix bug for data_structures/linked_list/doubly_linked_list_two.py

- dynamic_programming/bitmask.py
> fix: correct typo "util" to "until"

- linear_algebra/matrix_inversion.py
- Added `matrix_inversion.py` in `linear_algebra/` directory
- Used NumPy to compute the inverse of a square matrix
- Included test code and exception handling for singular matrices
> Add matrix inversion algorithm using NumPy

- project_euler/problem_136/sol1.py
> Solution for the Euler Project problem 136

- project_euler/problem_164/sol1.py
> Add solution for the Euler project problem 164.

- project_euler/problem_345/sol1.py
> Add solution for the Euler project problem 345

- project_euler/problem_095/sol1.py
> Add solution for the Euler project problem 95.

- data_structures/binary_tree/lowest_common_ancestor.py
Contributes to https://github.com/TheAlgorithms/Python/issues/9943 
Added doctests to all functions in lowest_common_ancestor.py
> Added/Improved doctests for lowest_common_ancestor.py

- searches/quick_select.py
> Add median() function using Quickselect

- backtracking/sum_of_subsets.py
> Add tests and cleanup sum_of_subsets algorithm

- dynamic_programming/matrix_chain_order.py
Add test, fix typo for the matrix chain order dynamic programming algorithm.
> Update matrix_chain_order calculation with more details and test.

- financial/straight_line_depreciation.py
> feat: create straight_line_depreciation

- maths/test_factorial.py
- web_programming/current_stock_price.py
> Add unit tests for factorial.py

- DIRECTORY.md
- ciphers/hill_cipher.py
- data_structures/binary_tree/non_recursive_segment_tree.py
- data_structures/hashing/hash_map.py
- data_structures/heap/heap.py
- data_structures/heap/randomized_heap.py
- data_structures/heap/skew_heap.py
- data_structures/linked_list/skip_list.py
- data_structures/queues/queue_by_list.py
- data_structures/queues/queue_by_two_stacks.py
- data_structures/stacks/stack.py
- data_structures/stacks/stack_with_doubly_linked_list.py
- data_structures/stacks/stack_with_singly_linked_list.py
- graphs/graph_adjacency_list.py
- graphs/graph_adjacency_matrix.py
- graphs/graph_list.py
- graphs/minimum_spanning_tree_kruskal2.py
- graphs/minimum_spanning_tree_prims2.py
- matrix/matrix_class.py
- other/least_recently_used.py
- other/lfu_cache.py
- other/lru_cache.py
- pyproject.toml
- sorts/insertion_sort.py
- sorts/tim_sort.py
Make changes required to pass current ruff tests.
> Various ruff fixes

- strings/capitalize.py
* Removed dependency on string.ascii_lowercase and string.ascii_uppercase and Replaced string-based capitalization with manual ASCII offset
* Reduced function complexity and branching
* Added basic unit tests to ensure correctness
* Eliminated external module dependency (string) for better portability and reduced overhead
* Improved performance (5× faster in benchmarks)
* More efficient implementation
* Maintains readability and correctness
* Code compiles without errors
* Performance verified with benchmarks
> Simplify Capitalize Function

- boolean_algebra/imply_gate.py
This pull request introduces a new function, `recursive_imply_list`, which calculates the implication of a list of boolean values (0 or 1) by applying the implication operation recursively from left to right.
It builds upon the existing `imply_gate` function.
> feat: Add recursive implication function for lists

- data_structures/linked_list/from_sequence.py
> Update Linked List from sequence script to use doctests

- graphs/check_bipatrite.py
- strings/boyer_moore_search.py
* Iteration over `graph` mutated by `defaultdict` neighbours caused  
`RuntimeError: dictionary changed size during iteration`.  
– Iterate over `list(graph)` in both DFS and BFS helpers.  
* Corrected `if __name__ == "__main__":` typo.  
* Updated two doctests that now succeed after the fix.  
All doctests now pass (`30/30`), eliminating a critical runtime failure and improving reliability of the graph algorithms.
> Fix RuntimeError in bipartite-check DFS/BFS and clean up doctests

- DIRECTORY.md
- project_euler/problem_009/sol4.py
Pre-compute the squares and use the look up in the set to check squares property.
> Add new solution for the euler project problem 9 

- maths/numerical_analysis/weierstrass_method.py
- Implements Durand-Kerner (Weierstrass) method for polynomial root finding
- Accepts user-defined polynomial function and degree
- Uses random perturbation of complex roots of unity for initial guesses
- Handles validation, overflow clipping, and includes doctest
This pull request adds an implementation of the Weierstrass (Durand–Kerner) method to numerically approximate all complex roots of a given polynomial. The function accepts a user-defined polynomial, its degree, and an optional initial guess for the roots. The implementation includes:
1. Type annotations and detailed docstring
2. Doctest to validate correctness
3. Optional support for custom initial guesses
4. Numerical safeguards (e.g., overflow clipping)
5. A Wikipedia reference for further explanation
This method is useful in …
> Weierstrass Method

- strings/palindrome.py
Fix #12941 : Corrected base case in is_palindrome_recursive in strings/palindrome.py of Python directory.
Previously, the base case used `if len(s) <= 2: return True`, which incorrectly treated any 2-character string as a palindrome (for example, "AB" returned True). Updated the base case to `len(s) <= 1` so that two-character strings are compared for equality and only empty/single-character strings auto-pass.
> Fix is_palindrome_recursive logic in strings/palindrome.py

- .github/workflows/build.yml
- .github/workflows/directory_writer.yml
- .github/workflows/project_euler.yml
- .github/workflows/sphinx.yml
- ciphers/gronsfeld_cipher.py
- machine_learning/xgboost_classifier.py
- maths/largest_of_very_large_numbers.py
- pyproject.toml
> Test Python 3.14
